### ISSUE TITLE
Regex not working.

### ISSUE THREAD

**Issue by SJ50** [filebrowser/filebrowser#1034]
I wanted to create separate user with limited number of folder access.

So I added  regex  `^(?:(?!Foo|Bar).)*$\r?\n?` to allow folder named "Foo" and "Bar" but it does not work.
I get message "Something really went wrong."

I do not want to disallow all the folder individually. 

![image](https://user-images.githubusercontent.com/4822384/87630847-74a28680-c779-11ea-979b-980abbfc8b70.png)

**Comment by o1egl** [comment]
Your regexp is not valid https://play.golang.org/p/-QM2-bgDO3u

**Comment by thomaschampagne** [comment]
Hi! Same kind of issue for me. Trying to "disallow all paths expect 2 folders" for a user. For this we could use regex "negation" pattern (see this: https://stackoverflow.com/questions/1687620/regex-match-everything-but-specific-pattern)

But standard Golang regex seems not support it... Okay. (https://stackoverflow.com/questions/26771592/negative-look-ahead-go-regular-expressions)

Actually i tried the "negative way" because the "positive way" didn't worked as i could expect:

![image](https://user-images.githubusercontent.com/151973/89130359-ad29ba80-d504-11ea-8405-bcfd0a4c89c3.png)

I expected to not see the *homes* folder :(

I think @SJ50 and me are trying to do the same thing: How to give access *only* to a list of folders?

Thanks,

Thomas

**Comment by SJ50** [comment]
@thomaschampagne use the following rules 
![image](https://user-images.githubusercontent.com/4822384/89135329-1db9f100-d570-11ea-84e6-63a488d12b57.png)

first one is disallowing everything and following after that rules allows "Foo" and "Bar".

@o1egl  Please add this to wiki, I found this solution in closed issue answer.  This solution is very handy when you have 100s of folder but want to allow few folder to users.

**Comment by thomaschampagne** [comment]
@SJ50 Thanks for the tip.

I needed to apply the similiar behavior with a inner folder.

**The use case:** I want alice to a have access to "downloads" folder and only his home folder  **/homes/alice**. Access to folder  **/homes/bob** must be denied for **alice**

Here's is the working config for this **usual** case:

![image](https://user-images.githubusercontent.com/151973/89176231-73e75e00-d589-11ea-8458-2984dd1a2cdc.png)

These usuals use cases should be added to wiki too.

**Comment by o1egl** [comment]
@thomaschampagne @SJ50 you are welcome to make a PR https://github.com/filebrowser/docs :wink:
