### ISSUE TITLE
A java script has a medium security vulnerability

### ISSUE THREAD

**Issue by teerapat45** [filebrowser/filebrowser#1054]
**Description**

We try to integrate FileBrowser into our web application, we have deployed FileBrowser as is then run OWASP ZAP to scan FileBrowser for vulnerability and found one below is considered should be fixed.

But however, we have no skill to fix it.

![image](https://user-images.githubusercontent.com/32411895/89029667-208ec900-d359-11ea-93d1-35b3263895fe.png)

**Comment by o1egl** [comment]
If I understand correctly the scanner is complaining about the line "Internal server error" which is a false positive. I think you can safely ignore it.

**Comment by sutees** [comment]
I think @teerapat45 reported that the FileBrowser project includes a Javascript that renders a page that contains an error/warning message that may disclose sensitive information like the location of the file that produced the unhandled exception.

**Comment by ramiresviana** [comment]
Just a false positive, the alert was triggered because the string 'Internal Server Error' on this part of the code:
https://github.com/filebrowser/filebrowser/blob/a2fb499a205d4ebdcabd9f355f403b4ad4e32544/frontend/src/router/index.js#L106-L110

There some cases that internal server errors can provide sensitive information, but is not the case of the Filebrowser. When the backend encounters an error, it returns only the http status code, without further information.

**Comment by teerapat45** [comment]
@ramiresviana  thank you so much.
