### ISSUE TITLE
Strange double click behavior on mobile

### ISSUE THREAD

**Issue by potados99** [filebrowser/filebrowser#1160]
Thank you very much to all you guys for this awesome app!!

**Description**
Let's say, file tree is like below:

~~~
root
  L dir
    L subdir
      L files...
~~~

When double-clicking `dir`, it enters `dir`, however it does not stop there: it keeps navigating into `subdir`.

It acts just like I had a qudraple click at a time.

**Expected behaviour**
Double click is expected to be consumed on first navigation.

**What is happening instead?**
I found ways to get rid of this strange behavior:

- Instead of tap-release-tap-release, do tap-release-tap-hold(or slide)

- Tap any file/folder other than a target folder, then do a double tap on the target folder.

**Additional context**
Tested on iOS Safari, and Android Chrome.

**How to reproduce?**
Open `filebrowser` on mobile browser and perform a double click on a non-empty folder.

**Comment by o1egl** [comment]
This PR https://github.com/filebrowser/filebrowser/pull/1139 will probably solve your issue

**Comment by jhagerer** [comment]
This issue is apparently not solved when you share a folder via public link which is then opened by a third person without account. Even when the global setting _Use single clicks to open files and directories_ is activated, an external person has to double tap (I say tapping here because that's what most of my friends do when I send them files). This in turn yields the already denoted unexpected behaviour of jumping into sub-subdirectories.

Can maybe somebody tell me if I oversaw something?
