### ISSUE TITLE
LDAP Integration

### ISSUE THREAD

**Issue by alex2ndg** [filebrowser/filebrowser#1164]
It'd be great to have LDAP integration with local Active Directories so we only have to set up the permissions on filebrowser' side but set an OU to have access.

**Comment by nambrosch** [comment]
Yes, it would be nice.  For now most people use apache's ldap auth.  You can search closed issues for examples or if that doesn't help I can provide some examples.

**Comment by alex2ndg** [comment]
Hello nambrosch.

I guess that you are speaking about #301 and #489. Unfortunately, I don't know where the html/php code for this is located when running, maybe you can provide that example?

Thanks.

**Comment by defkev** [comment]
I just stumbled upon this project looking for a simple file browser for a WebDAV server w/ LDAP.

Will the proxy authentication in file browser works you only get as far as the API throwing a 403 (which isn't very helpful) as the user passed along in your header doesn't exist in file browser (explaining the 403) - of course the user doesn't exist since users are stored in LDAP, its what LDAP is for.

Now you can either modify the project to add full LDAP integration so it gets all its user properties (scope, language, permissions, etc.) including authentication/authorization from LDAP or change the proxy authentication to create the users, using the /api/signup endpoint when the API returns a 403 if `auth.method=proxy`.

Tho that would be a rather hackish solution and nothing i would put into a PR.

Its a nice project but that's a real blocker.

**Comment by o1egl** [comment]
LDAP support is out of the scope of this project. Let's keep it simple

**Comment by SuitDeer** [comment]
I have written a small tutorial on how to integrate LDAP authentication into filebrowser:

[https://github.com/filebrowser/filebrowser/discussions/3702](https://github.com/filebrowser/filebrowser/discussions/3702)
