### ISSUE TITLE
Running docker image: standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by rutgersmit** [filebrowser/filebrowser#1242]
**Description**
I am trying to run filebrowser in Docker and I followed the instructions. I did:
- create the root dir /data/disk1/filebrowser
- created an empty file filebrowser.db via touch
- created a basic config file .filebrowser.json (copy of https://raw.githubusercontent.com/filebrowser/filebrowser/master/.docker.json)
- create a compose file with this content: 
- `version: '3.3'
services:
    filebrowser:
        volumes:
            - '/data/disk1/filebrowser:/srv'
            - '/data/disk1/filebrowser/config/filebrowser.db:/database.db'
            - '/data/disk1/filebrowser/config/.filebrowser.json:/.filebrowser.json'
        ports:
            - '80:80'
        image: filebrowser/filebrowser`
- start the cotainer via docker-compose up

**Expected behaviour**
I expect that the container starts and I can browse 192.168.x.y

**What is happening instead?**
Docker logs the error _standard_init_linux.go:211: exec user process caused "exec format error"_
It is not in the compose file, when I run it on the command line I get the same error. If I go 1 version back (v2.10.0-alpine), I still get the same issue.
I did chown the /data/disk1/filebrowser from root to the logged in user, no effect. 

**How to reproduce?**
Folow the steps in the description

Well... I think I have a fair amount of Docker knowledge, so I'm afraid I'm missing a very simple thing here.

**Comment by pavel-alay** [comment]
I've faced the same issue. Seems that something wrong with mounting files, not directories.

I found a workaround: start it as a docker container, it will create everything, and then you may start it via compose.

And as mentioned in the manual, it's important to create these files beforehand: `/<your-path>/filebrowser.db` and `/<your-path>/.filebrowser.json`, otherwise docker creates directories. I've copy pasted [default config](https://github.com/filebrowser/filebrowser/blob/master/.docker.json) into `/<your-path>/.filebrowser.json` in addition. 

My docker run command:
```
docker run \
    -v /srv:/srv \
    -v /<your-path>/filebrowser.db:/database.db \
    -v /<your-path>/.filebrowser.json:/.filebrowser.json \
    -p 9200:80 \
    --user 1000:1000 \
    filebrowser/filebrowser
    ```
