### ISSUE TITLE
Video & Picture Thumbnails

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#128]
_From @nwgat on November 2, 2016 23:47_

you can use ffmpeg on the server if its installed

_Copied from original issue: hacdias/filemanager-old#40_

**Comment by berglh** [comment]
Picture thumbnails would be ace :+1: :100:

**Comment by atecey** [comment]
👍would like to see this feature too

**Comment by arteta22000** [comment]
very practical, that would be great.

**Comment by palitu** [comment]
Yep - i would love picture thumbnails.  Even better if they would be cached.

**Comment by palitu** [comment]
Also , resize the image prior to displaying it in screen.

hell - whilst i am at it, i stumbled upon filebrowser whilst looking for a way to display my photos over the net, with the system just publishing them as they sit on the filesystem...

**Comment by max3163** [comment]
Any milestone for this great feature ?

**Comment by Equim-chan** [comment]
ffmpeg is good at this stuff, but of course it requires ffmpeg to be installed in the host. Maybe we can integrate this feature if ffmpeg is detected on run time. Any idea?

**Comment by YasserDRIF** [comment]
Any updates on the feature?

**Comment by vitaliy-kuzmich** [comment]
here it is : https://github.com/vitaliy-kuzmich/filebrowser , just need to integrate with windows...

**Comment by YasserDRIF** [comment]
Any idea or tuto on how to do that ... can you also open a pull request so that it gets added to the main code

**Comment by vitaliy-kuzmich** [comment]
See readme, it is modified. Just install 3 dependencies that mentioned, all the other steps as described in original filebrowser tutor. Basically I just call sh script from program, its okay if that dependencies would be missed, there will be bash errors that  it would not be found. Also put '-v' path to the previews, make sure it is not in the same folder as user scope. Also it will not work in windows at the moment, because of bash script call.

**Comment by YasserDRIF** [comment]
What i'm asking about is how to make everything into an executable file to use on windows ... just like the releases published earlier
@hacdias  any suggestions ?

**Comment by berglh** [comment]
These guys seem to have had a similar problem, looks like they've found the least worst approaching using cgo for packaging https://github.com/livepeer/lpms/issues/47

**Comment by CircuitCoder** [comment]
@vitaliy-kuzmich I've tried our your fork, the thumbnails got generated successfully for images, and I'm still debugging with videos. But the thumbnails doesn't show up in the frontend. Is that expected, or is there something wrong with my setup?

I also saw that you need a maintainer for the Vue frontend implementation. I would really love to help with that.

**Comment by CircuitCoder** [comment]
@vitaliy-kuzmich Oh so I just have to update the submodule. Trying that out.
 
I just update the submodule with:
```
cd frontend
git pull origin master
cd ..
git add .
git commit
```
Then it points to the latest commit in the upstream repo (210fef).

**Comment by vitaliy-kuzmich** [comment]
@CircuitCoder  git pull origin master
From https://github.com/vitaliy-kuzmich/frontend
 * branch            master     -> FETCH_HEAD
Already up to date.

**Comment by vitaliy-kuzmich** [comment]
@CircuitCoder  issue with github tree solved. Please try to pull...

**Comment by CircuitCoder** [comment]
@vitaliy-kuzmich OK I got it working. Thanks a lot!

**Comment by vitaliy-kuzmich** [comment]
@CircuitCoder https://github.com/filebrowser/frontend/pull/42#issuecomment-442281169 is it possible to do it in VUE ? Because I know it is possible in angular. Would it impact on performance ? Thanks.

**Comment by CircuitCoder** [comment]
@vitaliy-kuzmich I'm not sure. Having a look at the code. But I'm quite sure it's possible.

Performance shouldn't be a problem either. I will open a PR when I get it done in your repo and we may have further discussions there.

**Comment by vitaliy-kuzmich** [comment]
@CircuitCoder  got it, thanks

**Comment by ndandanov** [comment]
Hi! I think this feature is essential to such application and would be quite useful. I saw in #574 that it was planned for version 2.0, but I did not find a way to enable it once I ran the latest stable version.

So are the steps to introduce @vitaliy-kuzmich's changes to the latest versions too complicated?
If not, what are they?
If yes, how can one build everything from @vitaliy-kuzmich's fork into one executable file as are the official releases? It seems that there is the `wizard.sh` shell script for building the current versions of `filebrowser`, however it is not present in https://github.com/vitaliy-kuzmich/filebrowser.

Thank you in advance!

**Comment by vitaliy-kuzmich** [comment]
@ndandanov  hey, I've open new project : https://github.com/browsefile, currently it is in progress. I left backend from version 1.x and took frontend from the 2.x. from filebrowser. Since I am not strong with VUE, some chinese gentleman promised to help me with front, but unfortunately I have to work by my own, thats why it took so long. Android part would be much faster. 

Changes not committed yet, I will commit once it wold be logically finished.

- merge WEB with new version from filebrowser
- files share feature as usual browsing(not download only), include access managing for different users. So you can view shared files in browser
- settings not messed in different places, now it is only 1 json file, cut possibility to modify settings from CMD, cut database.
- reworked thumbnail generation, 
- settings for 'my shares' feature are still in progress
- started working on android client, it would be lightweight analog to the nextcloud, on the first iteration only files sync, on the second view, so on...
- added authentication by IP

overall my project would be aimed to the embedded devices, like routers with USB. Currently it runs on my router(256 RAM, 60 taken by backend, which is very good) with external HDD. Need to rework backend in future in order to minimize RAM consumption.

**Comment by ndandanov** [comment]
Thank you very much for your hard work, @vitaliy-kuzmich! I opted for using filebrowser on a Raspberry-like single-board computer with limited resources where the speed and efficient resource utilization of filebrowser are of huge benefit.
However, for my use case I would need the image/video preview and file sharing (e.g., via link) features.

When is a stable release of browsefile expected? I am looking forward to it! Thank you for your hard work!

**Comment by nambrosch** [comment]
@vitaliy-kuzmich i'm assuming if you complete your media preview features that you'll contribute back to the filebrowser project?

**Comment by ndandanov** [comment]
I just tested release v0.1.8 of @vitaliy-kuzmich's [browsefile](https://github.com/browsefile/backend) which supports image preview with the help of [the libvips image processing library](https://jcupitt.github.io/libvips/).
I think it would be great to have this feature integrated in the official filebrowser code base. :-)

**Comment by vitaliy-kuzmich** [comment]
@nambrosch well, bf are has different purpose. It is not designed to run on windows. It is quite complicate to support win/nix platforms. Already bf has too much changes in order to merge in original... Unfortunately it is not simple.
@ndandanov  I've added more features, include webdav protocol, shares also works in dav. There are external links feature. It would be nice if you test it, and report if you find any issues.

**Comment by nambrosch** [comment]
@vitaliy-kuzmich While it looks like you've done good work please stop repeatedly advertising your new project here, especially if you are unwilling to contribute back to the project that you took the original code from.  It would have been more productive to work on a single project instead of fragmenting this one.

**Comment by vitaliy-kuzmich** [comment]
@nambrosch got it, I just shared that I have updates, well, okay then, I will not send any message anymore. I wish to contribute! but I am not part of this project, when I tried to contribute, I waited for more then 1 month to receive answer, after created fork, and start new project, still without answer for my question. If you like to wait, for a years, please I would not disturb this thread anymore. Just check, this ticket still open form 2016....

**Comment by nambrosch** [comment]
@vitaliy-kuzmich i'm sure @hacdias would love to have you working on the main branch.  maybe you could post in https://github.com/filebrowser/filebrowser/issues/532

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
