### ISSUE TITLE
"Il"legal characters result in location cannot be reached

### ISSUE THREAD

**Issue by cascaabreu** [filebrowser/filebrowser#1332]
**Description**
Starting from Windows version 2.12.0+ cannot open paths with "il"legal characters such as (, ), !, etc.

**Expected behaviour**
Folder should open and list files.

**What is happening instead?**
Instead an error message is presented: Location cannot be reached.

**Additional context**
![image](https://user-images.githubusercontent.com/80730065/111247078-4d999e80-85ff-11eb-8737-fbab52fd9572.png)

**How to reproduce?**
Run filebrowser, create a folder like "blabla (2021)", try to open the folder on your browser, fails to do so.
Rename to just "blabla", folder will open and present all files in it.

**Comment by ramiresviana** [comment]
It's not clear what is causing that issue, we'll need your help to find out. Please provide the following information:

- Versions of operational system and web browser.
- HAR file or screenshot of requests tab on browser DevTools.
- Output of the Filebrowser console window.
- Are you using a web proxy?
- What is latest version of Filebrowser without that issue?

**Comment by cascaabreu** [comment]
Versions of operational system and web browser.
Windows 10 20H2 fully updated and latest Chrome 89.

HAR file or screenshot of requests tab on browser DevTools.
[filebrowser2.13.0HAR.zip](https://github.com/filebrowser/filebrowser/files/6149769/filebrowser2.13.0HAR.zip)

Output of the Filebrowser console window.
"2021/03/16 14:26:34 Listening on 127.0.0.1:8080"

Are you using a web proxy?
Not sure about this question, but i'm doing a reverse proxy via caddy webserver.

What is latest version of Filebrowser without that issue?
Version 2.11.0

**Comment by M4he** [comment]
Seems to be an issue with reverse proxy configuration for v2.12 and up, see also https://github.com/filebrowser/filebrowser/discussions/1334

I'm facing the same issue when using an nginx reverse proxy configuration and a `baseURL` that is set accordingly.  
Any HTTP requests (e.g. `DELETE`) sent for a URL path that contains characters like parantheses will 404 if a reverse proxy setup is used. For example:
```
DELETE https://www.example.com/filebrowser/api/resources/test%20(1).txt
```
where `baseURL` in filebrowser's config is set to `filebrowser` and the nginx reverse proxy is configured for the location `/filebrowser`.

Above request works with v2.11.0 but will **404** on any later version. Does not seem to be related to Windows specifically since I'm running this on Linux.

**Comment by chllivein** [comment]
#1312 I have the same problem. Finally rolled back to 2.11 to solve.
