### ISSUE TITLE
Loading problem

### ISSUE THREAD

**Issue by Zynismus16** [filebrowser/filebrowser#1426]
Hello, developer, I really like this program you developed.
Although the program is open source, but because I do not have the corresponding development capabilities.
Here are some feedback and suggestions, I hope you can adopt them.
When previewing files online, the preview window does not pop up directly, but the window pops up after adding the preview file name in the address bar, which causes the file in the folder to be loaded again after the preview is completed.
Secondly, when there are a large number of files or folders in a folder, the loading of the program will become very slow. I think it is caused by the waterfall flow layout. I hope to solve this problem.
Finally, the video preview hopes to change the player or increase the playback speed option and plug-in subtitle customization option.
The above is the problem that the program is considered to be flawed and hope to be adopted.
I wish the developers a happy life, the program is getting better and better.

**Comment by ramiresviana** [comment]
1. Previews are not displayed on a popup window, opening a file with supported format will display the preview of it in the same window. When adding the `inline=true` param to the download url, the browser will try to display the file instead of downloading it. Currently there's no support for preview on the share view.
2. The file listing does not make use of waterfall flow layout. The listing is optimized to render only the quantity of items necessary to fill the window initially. Unfortunately, on the currently implementation, all the file information is still transferred, which can cause the server to take some time to process the request.
3. The video player makes uses browser built-in implementation, so its features are limited by the browser.

**Comment by Soneji** [comment]
Hi there,

Is there any update/tracked issue on the implementation of having all the file information being transferred?
Maybe it would be better to run a `ls` (or equivalent) for the initial transfer, use that data to load the page and then asynchronously request the remainder of the content, details, etc.

I have a filebrowser with lots of files and I find it to be somewhat slow which I think could be in part due to this issue and in part due to filebrowser trying to load data from a HDD (not SSD). I think this would definitely help in scenarios where disk speeds are slow, such as my system. 

Thanks so much, love this app, been using it for years :)
