### ISSUE TITLE
How tu change auth methood when using docker?

### ISSUE THREAD

**Issue by erikthegamer1242** [filebrowser/filebrowser#1553]
**Is your feature request related to a problem? Please describe.**

How can I change the auth method using docker run or docker-compose?

**Describe the solution you'd like**

N/A
**Describe alternatives you've considered**

N/A
**Additional context**

N/A

**Comment by o1egl** [comment]
Check out cli command [docs](https://filebrowser.org/cli/filebrowser)

**Comment by Tuphal** [comment]
I have the same issue.
I get a timeout in the docker image terminal.

Docker on Synology
Image: filebrowser/filebrowser:latest

Starting a terminal with "/bin/sh" and command `./filebrowser config set --auth.method=proxy --auth.header=X-WEBAUTH-USER `
![grafik](https://user-images.githubusercontent.com/42291781/133128624-da582a5f-1d1e-46b4-a167-1eaf50adc41d.png)

**Comment by Tuphal** [comment]
I tried with a test-VM to use the CLI and transfer the db-file to my docker. Without success.

I tried to change the db file directly with https://github.com/br0xen/boltbrowser with partial success:
![grafik](https://user-images.githubusercontent.com/42291781/133132305-0b9e7d07-81ce-47f1-9cc0-9317f284cdba.png)


It seems to be a semi-working step, because now I got a 403 error in filebrowser log:
![grafik](https://user-images.githubusercontent.com/42291781/133129881-a3fdfc27-7b9d-4eae-9ae1-d9373cd9131c.png)

If I hard code the user in the reverse proxy AND the user was previously created, it works:
![grafik](https://user-images.githubusercontent.com/42291781/133132092-f3b95acb-fb01-4937-90ab-6f0609702b54.png)

Seems like an issue on my Authelia passing the user name..
And the filebrowser docs did not mentioned, that the user had to be created before switching to auth-method=proxy


Edit:
I got it working.
SSO service is Authelia.
I have not yet tested why, but I guess FileBrowser is case sensitive with the user name.
If I do not use the username, but the name, it works:
![grafik](https://user-images.githubusercontent.com/42291781/133135197-42e3a7dc-5919-48f9-9d10-14f6382264f8.png)

**Comment by o1egl** [comment]
To make changes in the db you must stop filebrowser app because it locks access to the file

**Comment by erikthegamer1242** [comment]
> I tried with a test-VM to use the CLI and transfer the db-file to my docker. Without success.
> 
> I tried to change the db file directly with https://github.com/br0xen/boltbrowser with partial success:
> ![grafik](https://user-images.githubusercontent.com/42291781/133132305-0b9e7d07-81ce-47f1-9cc0-9317f284cdba.png)
> 
> It seems to be a semi-working step, because now I got a 403 error in filebrowser log:
> ![grafik](https://user-images.githubusercontent.com/42291781/133129881-a3fdfc27-7b9d-4eae-9ae1-d9373cd9131c.png)
> 
> If I hard code the user in the reverse proxy AND the user was previously created, it works:
> ![grafik](https://user-images.githubusercontent.com/42291781/133132092-f3b95acb-fb01-4937-90ab-6f0609702b54.png)
> 
> Seems like an issue on my Authelia passing the user name..
> And the filebrowser docs did not mentioned, that the user had to be created before switching to auth-method=proxy
> 
> Edit:
> I got it working.
> SSO service is Authelia.
> I have not yet tested why, but I guess FileBrowser is case sensitive with the user name.
> If I do not use the username, but the name, it works:
> ![grafik](https://user-images.githubusercontent.com/42291781/133135197-42e3a7dc-5919-48f9-9d10-14f6382264f8.png)

I actually ended up doing the same thing and it also worked for me

**Comment by erikthegamer1242** [comment]
> To make changes in the db you must stop filebrowser app because it locks access to the file

If I stop it then the whole container stops

**Comment by o1egl** [comment]
There are no ways to do it within a docker container. You should modify the db outside the docker container and then mount it back

**Comment by Tuphal** [comment]
Is it correct, that the users provided by the header , had to be created in FileBrowser before switching the auth.method?
Or will FileBrowser create the users which are provided by the header?

**Comment by erikthegamer1242** [comment]
> Is it correct, that the users provided by the header , had to be created in FileBrowser before switching the auth.method?
> Or will FileBrowser create the users which are provided by the header?

I had to create the user myself, set it as admin, log in using the header auth and remove the default admin user

**Comment by o1egl** [comment]
> Is it correct, that the users provided by the header , had to be created in FileBrowser before switching the auth.method?
> Or will FileBrowser create the users which are provided by the header?

That is correct. Users must be created in the app. You can assign an admin role you yourself to manage users creation

**Comment by firestrife23** [comment]
Eh, maybe as a feature request?  Adding new environment for authentication something like this?

```
AUTH_METHOD=proxy
AUTH_HEADER=X-Auth-Username
```

**Comment by Dulanic** [comment]
> Eh, maybe as a feature request? Adding new environment for authentication something like this?
> 
> ```
> AUTH_METHOD=proxy
> AUTH_HEADER=X-Auth-Username
> ```

Agre 100%, we can't create users in docker becuase if we stop the filebrowser command, it kills the container.
