### ISSUE TITLE
Using config file to set branding & users.

### ISSUE THREAD

**Issue by JMast3rs** [filebrowser/filebrowser#1649]
Hi,

I have been trying to uses the config file to set branding name, directory and theme. But with no luck.
I have tried the JSON file is a couple of different formats.

`{
  "port": 8080,
  "baseURL": "/filebrowser",
  "address": "0.0.0.0",
  "log": "stdout",
  "database": "/config/database.db",
  "root": "/data",
  "branding": { "name": "Company" }
}`

I can tell that it is seeing the config file, because I can change the port. 

Any help would be much help.

Kind regards 

James Masters

**Comment by dacagi** [comment]
I'm having the same issue. No matter how I tried setting the branding variables I can't get them to apply. All other variables work fine, both by using the config file, or passing as environment variables with the FB_ prefix. I thought maybe the dot was to be removed or swapped like FB_BRANDINGNAME or FB_BRANDING_NAME but no luck.

So I looked at the code, and it seems that branding is indeed an object and passing the config like you showed should do the trick, but I also noticed that certain settings are handled differently. If you check src/settings/settings.go, there's the Settings struct with the branding and other options, and the Server struct which enables all other variables we can use in the JSON.

So it seems that the Server options can be used via config file or env var, but the Settings can't. Those can be applied by either using the filebrowser cli, or like I ended up doing, just let it run the first time and then set those within the GUI settings.

If someone else has a better approach, or an explanation why those settings are not parsed from the config file, I'm quite interested since I'm not an expert in Go and it's difficult for me to really understand the code.

Best regards,
David

**Comment by yzernik** [comment]
@dacagi 
I was able to get the branding name and the initial user by calling a script to start the app:

```
#!/usr/bin/env sh

# Update configs
/filebrowser config init
/filebrowser config set --branding.name "My App Name"
/filebrowser users add ${USER_NAME} ${USER_PASSWORD}

exec /filebrowser

```
