### ISSUE TITLE
Question: How to correctly update filebrowser 

### ISSUE THREAD

**Issue by emma-makes** [filebrowser/filebrowser#1705]
I've gone over the documentation and closed issues, however, I found no clear instructions on how to update filebrowser itself.

I assume running the install script again, would install the latest version, however without any documentation I am worried that this would break something (I'm currently on version 2.9.0).

`curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash`

So the question would be:

What is the correct approach to update filebrowser and shouldn't there be documentation on the topic?

**Comment by niubility000** [comment]
My method is pretty simple: 
For example, I am using a linux amd64 server, I just download the latest version of linux-amd64-filebrowser.tar.gz from https://github.com/filebrowser/filebrowser/releases, 
then unzip it. 
then in my server: `killall filebrowser`, 
and replace the old file "filebrowser" with the new one, `cp -rf /a/filebrowser /b/filebrowser`
then `chmod 755 /b/filebrowser`
then run this filebrowser again, `systemctl start filebrowser.service`

**Comment by userdocs** [comment]
@emma-makes I will confirm rerunning the script simply downloads and reinstalls the binary so if you have used this method to install it then you probably should use this method to update it.

I would consider that the correct way for how it was deployed in your situation.

Since a lot of people don't use the script to deploy it, then the typically correct process is is:

-  establish the latest version from github
-  Compare versions
-  Download the latest release if newer
-  Extract over the old version
-  Restart the app

If you are lazy like me you can just do this whenever you feel like it, by taking advantage of the GitHub latest release redirection:

_Note: The output dir `~/usr/local` in this example will need to exist for this command to work. You can send it anywhere you like._

```
wget -q -O- "https://github.com/filebrowser/filebrowser/releases/latest/download/linux-amd64-filebrowser.tar.gz" | tar -xz -C ~/usr/local filebrowser
```

This method will work with any of the artifacts listed in a latest version release https://github.com/filebrowser/filebrowser/releases/latest 

Here are the Linux examples.

```
linux-386-filebrowser.tar.gz
linux-amd64-filebrowser.tar.gz
linux-arm64-filebrowser.tar.gz
linux-armv5-filebrowser.tar.gz
linux-armv6-filebrowser.tar.gz
```

**Comment by emma-makes** [comment]
Thank you for the feedback! Those approaches sound reasonable. I deployed filebrowser with the script, so I reckon that's the most sensible approach for me.
I'd love to see this description in the official FAQ :)
