### ISSUE TITLE
Uploading error

### ISSUE THREAD

**Issue by muzaffarab** [filebrowser/filebrowser#1708]
**Description**
When I upload any big-size file it gives an error within a few seconds.

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by ArmJo** [comment]
You give very little information to help you. So I assume you can upload small files? If yes, it is probably caused by a limit for upload file size of a reverse proxy (e.g. nginx), because filebrowser has no limit for the file size (see https://github.com/filebrowser/filebrowser/issues/1149#issuecomment-729555976). A suggestion for a nginx config is here: https://github.com/filebrowser/filebrowser/issues/706#issuecomment-569264112
