### ISSUE TITLE
Can we Access/merge multiple directory ?

### ISSUE THREAD

**Issue by maniCitizen** [filebrowser/filebrowser#1826]
Hi , I have two directories /home/ubuntu/Media and /home/ubuntu/Downloads from which i try to share the files, so my question is can we mount this two different directory's in single service file (filebrowser.service) . if yes kindly suggest little detailing.  thanks !.

**Comment by o1egl** [comment]
No, you can't. You can either set `/home/ubuntu` as a root path, or create a `/home/ubuntu/filebrowser` with symlinks to `/home/ubuntu/Media` and `/home/ubuntu/Downloads`

**Comment by ChaosBlades** [comment]
It would be nice to re-open this as a feature request. I would really like to mount multiple directories to use as source. FileBrowser had all the features I wanted and none that I didn't except for this. This is a show stopper for me.

I am using FileBrowser on my TrueNAS SCALE server and I wanted to mount multiple datasets as source files so that I could move files around, edit config files, and view images without having to SSH in all the time or use FileZilla. This was a nice light weight easy to use solution for that but without being able to mount multiple sources I can't do that.
