### ISSUE TITLE
When will ldap or AD domain login be supported? 

### ISSUE THREAD

**Issue by uranus829** [filebrowser/filebrowser#1851]
Hi,When will ldap or AD domain login be supported? If you can integrate ad domain login, it is a good choice to make a shared disk in the enterprise.

**Comment by ramiresviana** [comment]
There's a proposal for a authentication hook (#1554) that would allow to integrate Filebrowser with other systems, but that feature is not very demanded and probably wont be available soon.

**Comment by brlarini** [comment]
+1 would like to have LDAP/AD authentication for Filebrowser.
Maybe something very simple, such as getting the response from an external tool (ntlm_auth)?

**Comment by vbouchaud** [comment]
Hi there,
The organization I currently contract for is used to filebrowser but had issues with the fact there was no way to use a ldap authentication too.

I took the time to tweak the code to do it, https://github.com/vbouchaud/filebrowser/commit/dc346ebfb4dd1e3dd9b800086d103ccc937c03f4

Since there is the proposal for the authentication hook (that would be a much better idea IMO), I didn't make any effort to add tests and the [option property-memberof](https://github.com/vbouchaud/filebrowser/blob/dc346ebfb4dd1e3dd9b800086d103ccc937c03f4/cmd/config.go#L39 ) is unecessary - I thought I could easily add some kind of group based access control but I was mistaken.

Feel free to use the code as you see fit while waiting for the authentication hook MR to be merged.

**Comment by gaby** [comment]
I have a similar use-case as @vbouchaud would be really cool if filebrowser had some kind of support for LDAP.

**Comment by gaby** [comment]
I don't understand why #1554 doesnt get reviewed or merged. It's been 8 months....

**Comment by kaptinlin** [comment]
when ldap support?

**Comment by gaby** [comment]
@KaptinLin Nada... It's been months

**Comment by gaby** [comment]
This issue is now fixed via #1554

**Comment by UberMetroid** [comment]
I could really use LDAP.
