### ISSUE TITLE
Trash or Recycle Bin feature rather than immediate file deletion

### ISSUE THREAD

**Issue by robflate** [filebrowser/filebrowser#1854]
**Is your feature request related to a problem? Please describe.**
I would like File Browser to have a Trash/Recycle Bin feature so deleted files are not immediately deleted.

**Describe the solution you'd like**
Send deleted files to the Trash/Recycle Bin or a specified mapped Docker volume.

**Describe alternatives you've considered**
Maybe what I want is already possible using Command runner and Before Delete? I assume docker containers can't use trash-cli on the host but don't know. Alternatively, I see many Docker containers use a mapped volume and send deleted files there rather than immediately deleting them.

Thanks.

**Comment by ArgentumCation** [comment]
Seconding this, or a workaround if anyone has one. In my infinite wisdom I deleted a large folder off my NAS recently

**Comment by MatthiasBenaets** [comment]
> Maybe what I want is already possible using Command runner and Before Delete? 

Pretty much no need for this feature since it is possible with a Command Runner.
Add the command below under "Before Delete"
`/bin/sh -c 'if [[ "$FILE" != "/srv/Trash/"* ]]; then mv $FILE /srv/Trash; fi'`
Works great in my docker container on linux

Notes:
- You will have to create a Trash directory yourself. In this example I just create `Trash` directory in `/srv` (aka `/files/`)
- Deleting a dir or file will move it to `/srv/Trash`, if `$FILE` contains `/srv/Trash/` it will completely remove the item.
- Don't forget to add a trailing slash when comparing `$FILE ` to trashpath. Otherwise you will be able to completely remove the trash dir (I guess you can add an elif statement if you don't want to receive an error when trying to delete the trash dir)

**Comment by robflate** [comment]
Fantastic! This works great.

**Comment by JordyProvost** [comment]
"Pretty much no need for this feature"

Pretty much, but i see some limitations to the proposed workaround :

1. file path is not preserved in the recyclebin, so with hundreds of files, its hard to known where the file comes from.
2. consequence of 1, if i delete 2 files with the same name from 2 differents folders, the mv will fail and i cannot delete the second file without deleting the first from recyclebin
3. no convenient (or user friendly) way to restore from recyclebin
4. the recycle bin is the same for all users (with all the problems/consequences we could imagine)

I'm convinced that filebrowser need such a feature.

Can you please reopen this issue and tag is as enhancement request, even if you dont work to implement it soon ?

I have made a script that adress (very) partially the problems 1 et 2 (warning, i use bash, it may work in another shell, but i have not tested it).

Before delete :

`/bin/sh -c '/scripts/torecycle.sh "$FILE"'`

Script /scripts/torecycle.sh, executable, owner is the user who runs filebrowser, you need to edit FB_ROOTDIR ("root" value in your config init), and FB_RBIN (path to recycle bin).

```
#!/bin/bash

# Parameters
FB_ROOTDIR="/share"
FB_RBIN="$FB_ROOTDIR/.trash"

FILE="$1"

# We take the file path but we dont keep the rootdir part
FILE_PATH="$(dirname $FILE | sed "s,^${FB_ROOTDIR},,g")"
BASE_NAME="$(basename $FILE)"

# Return error when trying to delete the recyclebin itself
if [[ "$FILE" == "$RB_RBIN" ]];then exit 1 ;fi

# Create recycle bin if it does not exist
if [[ ! -d "$FB_RBIN" ]];then mkdir -p "$FB_RBIN" ;fi

# mv file to FB_RBIN if we dont delete from FB_RBIN
if [[ -z "$(echo $FILE | grep -E "^$FB_RBIN")" ]];then
        mkdir -p "$FB_RBIN$FILE_PATH"
        mv "$FILE" "$FB_RBIN/$FILE_PATH/$BASE_NAME"
fi
```
Obviously, the problem is we dont see the files in .trash, only the root of the aborescence we need to explore to see files... (and we maybe need to add a "find . -type d -empty -delete" in the trash after copies to avoid empty directories after "restorations".

But a real recycle bin must works against some sort of database to show "filename|path|delete_date".
With the database, it is possible to display multiples files with the same name directly in the root of the bin (the presented bin is just a view of the database, not the real files, also, we just display files deleted by the loggedin user).
The database must be associated with a script which mv the file in a hidden directory (in subfolders like timestamp.md5sum for example to avoid problems with 2 files with the same name).
When creating the database, recyclebin folder must be emptyed.
When deleting a user, database entries for this user, and associated files must be deleted.

Maybe another solution to not handle another db is to put some metadatas in the files moved to bin with "setfattr"
Filebrowser can then get this metadatas with "getfattr" to display bin content (with origin path etc...).
To handle multiples files with the same name, maybe add timestamp.[filename.ext], but it implies to parse the filenames to get rid of the timestamp part before displaying them to the user.
This solution may have poor performances compared to the database one, and add some dependencies too (package attr for alpine for example).


I have made a few scripts to show the PoC.
Here, we change the behaviour of the "rename" button, but only in the trash folder :

- Before delete : /bin/sh -c '/scripts/torecycle2.sh "$FILE"'
- Before rename :
  - /bin/sh -c '/scripts/protecttrash.sh "$FILE"'
  - /bin/sh -c '/scripts/torestore.sh "$FILE"'

/scripts/protecttrash.sh (to prevent user to rename trash) :

```

#!/bin/bash

# Parameters
FB_ROOTDIR="/share"
FB_RBIN="$FB_ROOTDIR/.trash"

FILE="$1"

# Return error when trying to handle the recyclebin itself
if [[ "$FILE" == "$FB_RBIN" ]];then exit 1 ;fi
```

/scripts/torecycle2.sh (almost the same as the previous /scripts/torecycle.sh, but add timestamp to the filename, put the origin path in metadata, and dont recreate filetree).
Note that thos script also contains the code of  protecttrash.sh (so it prevent deleting trash)

```
#!/bin/bash

# Parameters
FB_ROOTDIR="/share"
FB_RBIN="$FB_ROOTDIR/.trash"

FILE="$1"

echo "CMD : mv $FILE $FB_RBIN/$FILE_PATH/$BASE_NAME" >> /tmp/torecycle.log

# We take the file path but we dont keep the rootdir part
FILE_PATH="$(dirname $FILE | sed "s,^${FB_ROOTDIR},,g")"
BASE_NAME="$(basename $FILE)"

# Return error when trying to delete the recyclebin itself
if [[ "$FILE" == "$RB_RBIN" ]];then exit 1 ;fi

# Create recycle bin if it does not exist
if [[ ! -d "$FB_RBIN" ]];then mkdir -p "$FB_RBIN" ;fi

# mv file to FB_RBIN if we dont delete from FB_RBIN
if [[ -z "$(echo $FILE | grep -E "^$FB_RBIN")" ]];then
        mkdir -p "$FB_RBIN$FILE_PATH"
        mv "$FILE" "$FB_RBIN/$FILE_PATH/$BASE_NAME"
fi
```

/scripts/torestore.sh (restore file at the origin, based on the metadata we set earlier) :

```
#!/bin/bash

# Parameters
FB_ROOTDIR="/share"
FB_RBIN="$FB_ROOTDIR/.trash"

FILE="$1"

# If we handle a file in recycle bin, we do a restore
if [[ "$(echo $FILE | grep -E "^$FB_RBIN")" ]];then

        # if FILE is empty, we exit (because we will do a rm we need to be safe)
        if [[ -z "$FILE" ]];then echo "File is empty" && exit 1 ;fi

        # We check if the file have a timestamp in the name, if not, we exit
        # we only allow to restore at the root of the recycle bin, because only the files/folders here have path metadata
        BASE_NAME="$(basename $FILE)"
        FILE_TS=$(echo $BASE_NAME | awk -F'.' '{print $1}')
        if [[ ! "$FILE_TS" =~ ^[0-9]{10}$ ]];then echo "Filename does not begins by timestamp" && exit 1 ;fi

        # We take the name of the file itself, and remove the timestamp
        BASE_NAME_CLEANED="$(echo $BASE_NAME | sed 's/^[^\.]*\.//g' )"

        # We get the path to restore from metadatas, if path metadata dont exist, we exit
        ORIGIN=$(getfattr --only-values -n user.path $FILE)
        if [[ -z "$ORIGIN" ]];then echo "Origin is empty (metadata does not contain path value)" && exit 1 ;fi

        # Restore file
        mkdir -p "$FB_ROOTDIR$ORIGIN"
        mv -f "$FILE" "$FB_ROOTDIR$ORIGIN/$BASE_NAME_CLEANED"
fi
```

downsides :

- we have to set FB_ROOTDIR, FB_RBIN in all the scripts
- we have to copy all the script and chown/chmod them
- we need "attr" package
- we dont see arborescence like the previous script
- we see the timestamp when viewing the recycle bin
- the trash is the same for all users
- rename button will restore, but also give an error "404 not found" (because FB try to rename but the file is not in the recylce bin anymore), and you have to refresh to see the file has disapeared from trash

advantages:
- we dont have to explore the arborescence
- we can restore easily
- we can delete multiples files with exactly the same name without problem (because the timestamp is added to the filename), unless the files are deleted at the same second.


As i have said above, the only real solution is a database.
My point was just to demonstrate we cannot have a real recycle bin feature without implementing it in Filebrowser.

Thanks.

**Comment by ArgentumCation** [comment]
I seem to have found a more elegant solution, that almost does everything.
I added this to my `docker-compose.yml`:
```yml
    build:
      context: $DOCKERFILE_DIR/filebrowser
 ```
and then this to `$DOCKERFILE_DIR/filebrowser/Dockerfile`
```dockerfile
FROM filebrowser/filebrowser:latest
RUN apk add trash-cli
```

In the Command Runner settings, I added 
```sh
trash-put $FILE
```
under "Before Delete"

`trash-list`, `trash-empty` `trash-restore` and `trash-rm` would need to be run from a cli environment however

adding trash-cli to the upstream docker image seems trivial, but I'd imagine fleshing out the rest of the feature might take a bit more work

**Comment by JordyProvost** [comment]
@ajayk111
Thanks, it's indeed way more simple, but i dont think this is the good solution to implement as the trash will be the same for all users.
For instance, i stick on my solution as the possibility to restore from GUI fits my needs better, but it may help users who dont absolutely want this behavior. :)

**Comment by hameedacpa** [comment]
Hi, 
I'm using TrueNAS and I installed FileBrowser as an application and I applied 
`/bin/sh -c 'if [[ "$FILE" != "/srv/Trash/"* ]]; then mv $FILE /srv/Trash; fi'`
but it doesn't work
are there any simple and clear procedures for this because I think this features is necessary

**Comment by vjp23** [comment]
Hi all, I'm also having issues with this. I get a 500 error, and my docker logs show:

```
2024/10/12 06:29:16 [INFO] Blocking Command: " /bin/sh -c 'if [[ "/srv/not_trash_test.txt" != "/srv/Trash/"* ]]; then mv /srv/not_trash_test.txt /srv/Trash; fi'"
2024/10/12 06:29:16 /not_trash_test.txt: 500 [my WAN IP] exec: no command
```

Do I need to, like, enable some commands somewhere in the settings? I don't see anything in the docs about this but other issues suggest that maybe I do? I'm having a hard time understanding the help text in the settings under "Execute on shell".

Thanks!

**Comment by vjp23** [comment]
Looks like I was able to get this working by downgrading my Docker image to v2.23.0 as reported in https://github.com/filebrowser/filebrowser/issues/2993

**Comment by SawkeeReemo** [comment]
Just took time to set this up tonight to learn that there’s no recycle bin… And none is planned/the request was dismissed?? Really?? My single confused eyebrow may be permanently stuck in the upward position. …how can we deploy a GUI file manager and expect any user to not completely nuke their own files with no recourse all the time? This post is now almost four years old, and I’m actually shocked that one hasn’t been implemented. 

Until there is one, I guess this is only meant for sys admins who are extremely careful, eh?
