### ISSUE TITLE
Frontend has "Login" button with auth.method=proxy on public shares

### ISSUE THREAD

**Issue by nikarh** [filebrowser/filebrowser#1878]
**Description**

There is `Login` button in frontend on public shares with `auth.method=proxy`. This doesn't make much sense, since with this auth method login is performed outside of filebrowser.

**Expected behavior**

I would suggest that in that case there should either be no `Login`, or its behavior should be configurable (e.g. redirect to a user-defined link). Considering that `Logout` button is not configurable for `proxy` auth method, the first suggestion is more reasonable.

**How to reproduce?**

1. `filebrowser config set --auth.method=proxy  --auth.header=Remote-User`
2. Access filebrowser with `Remote-User` header (for that I use authelia)
3. Create a share for any file while logged in
4. Open the shared link in a private tab, without auth headers

**Comment by lalalabox** [comment]
I met **the same** problem.   
### Description
When I use `filebrowser config set --auth.method=proxy --auth.header=Remote-User` + `authelia`, I just wanna let the `/share*` can be accessed by anyone.
However, strange thing is:
> - when exclude `/share*, /static*, /api/public*` from protecting of `authelia`
> - Indeed, we can view or download shared files successfully
> - **BUT**, when we press the **Login** button, it cannot redirect to `authelia` **unless you refresh the webpage!**

### Expected behavior
Use `authelia` to protect `filebrowser`, and we can access shared link freely as well.
Meanwhile, the `Login` button should direct to `https://xxxxx.com`, rather than redirct to login page internally!

**Comment by raisinbear** [comment]
I think it's clear that this happens and shouldn't, but I'll chime in either way.

### Description

- I'm basically using the same configuration as @lalalabox. I also manually determined the mentioned locations to exclude from authelia (and it would be kinda nice to get some confirmation I'm not enabling all sorts of attack vectors by doing so).
- Login button takes me to FileBrowser Login, but not to authelia landing page, which it should. Except if I manually reload the page.
- The same login form is displayed if a (non-authelia-verified) user visits w.g. [url]/share, which as stated above must be excluded from auth-backend.
- Login via that form is not possible for me, no matter if the credentials are correct or not. At least ostensibly, this is a good thing. Still doesn't feel good that anyone can get to that form, however, because I couldn't find a way to log failed login attempts on the integrated authentication backend.

### Expected behavior

All stated already.

**Comment by masterwishx** [comment]
is the problem Fixed?

**Comment by nikarh** [comment]
No, still the same.

**Comment by masterwishx** [comment]
> No, still the same.

So am i
