### ISSUE TITLE
When previewing a video, space quickly starts running out

### ISSUE THREAD

**Issue by DUOLabs333** [filebrowser/filebrowser#1902]
**Description**
When I preview a video, space starts running out (I assume that it's trying to cache it)

**Expected behaviour**
The video is streamed, only caching a bit at a time.

**What is happening instead?**

**Additional context**

**How to reproduce?**
Try to view a large video, any format should do (but I tested mp4 and mkv files)

**Files**

**Comment by ramiresviana** [comment]
Filebrowser has no caching for video files on the server side, it will not write anything to the disk when previewing a video.

**Comment by DUOLabs333** [comment]
But I'm definitely seeing space fill up, and when I close the tab, the space gets freed back up.

**Comment by ramiresviana** [comment]
Can you point out the path of the file that is supposedly created by Filebrowser and consumes your disk space?

**Comment by DUOLabs333** [comment]
It's an mp4 file: `file:///home/system/Project.mp4`

**Comment by ramiresviana** [comment]
Operational systems and applications writes temporary files to very specific directories, you provided a arbitrary path that does not help solving your issue.  Is possible that Filebrowser is consuming system memory when reading files (https://github.com/filebrowser/filebrowser/issues/1671), but that is not confirmed because the lack of information and inability to reproduce the issue.

We need you to confirm what is consuming your disk space, it can be the operational system or applications other than Filebrowser. You are probably using a browser to access it, keep in mind that browsers also have cache.

**Comment by DUOLabs333** [comment]
> You are probably using a browser to access it, keep in mind that browsers also have cache.

This is probably it, I guess I have to find a way for Firefox to stop caching for this site. Thanks.
