### ISSUE TITLE
Use external programs to generate thumbnails 

### ISSUE THREAD

**Issue by chosgor** [filebrowser/filebrowser#1916]
**Is your feature request related to a problem? Please describe.**
filebrowser doesn't know how to generate thumbnails for all file types and it's not feasible to do so. This is a common problem in all file managers. Typically, they delegate thumbnail generation to external programs. [This spec](https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html) is used for identifying which programs to use for what type of files and how to actually run them. End user can install additional thumbnailers and all the programs that follow this spec can leverage them.

**Describe the solution you'd like**
We can implement the above spec so that filebrowser can detect the thumbnailers installed on the system (such as [this](https://packages.debian.org/stretch/ffmpegthumbnailer) or [that](http://manpages.ubuntu.com/manpages/trusty/man1/evince-thumbnailer.1.html)) and run them for thumbnail generation.

**Describe alternatives you've considered**
Maybe this can also be done via filebrowser configuration, giving the user to define their own binaries for generating custom thumbnails.

**Comment by CyAScott** [comment]
I am interested in this as well. I have an example of manually generated thumbnails for videos working with filebrowser in my fork. The thumbnails are not automatically generated, but it is a step in the right direction. My fork would need several modifications to work as you describe. I'd be willing to make the modification to store the thumbnails in the directory located at the $XDG_CACHE_HOME environment variable using the md5 hash of the absolute canonical URI.

**Comment by chosgor** [comment]
Although I'm not sure about the implications of accessing files under $XDG_CACHE_PATH (especially when running in a container), I think you got off to a good start.

As to the automatic generation, one has to simply parse the .thumbnailer file and build the command line as per https://github.com/GNOME/gnome-desktop/blob/master/libgnome-desktop/gnome-desktop-thumbnail.c#L207

**Comment by CyAScott** [comment]
After giving this some thought, there are a few issues with this solution for thumbnails.

## Canonical file path's will likely be different in the container vs the host machine

The spec defines that the thumbnail file names should be the md5 hash of the original file's canonical path (i.e. `file:///home/jens/photos/me.png` would be `c6ee772d9e49320e97ec29a7eb5b1697.png`). If the path to the original file inside the container is not the same path as the host machine, then filebrowser will attempt to look for the wrong file name in the `$XDG_CACHE_PATH` directory. It is possible to ensure that the paths are the same with [this config setting](https://github.com/filebrowser/filebrowser/blob/v2.21.1/docker/root/defaults/settings.json#L7), but that would be confusing to explain in the product documentation for that config setting.

## Filebrowser generating thumbnails based on thumbnailer files

In addition to filebrowser possibly configured in such a way that it is making the wrong file names for the thumbnails, filebrowser would need to parse the thumbnailer files that likely have paths for commands that aren't accessible from inside the container. It is possible to map all the volumes needed to make those paths accessible, but that requires the person who setup the container to know all the paths referenced in the thumbnailer files when setting up the container. In addition, there could be some downstream effects after executing the thumbnailer command since it might access a resource outside of the container like `ffmpeg` (which would fail unless that volume is also mapped).

## Conclusion

This spec is not container friendly. It would require the user setting up the container to research and find all the volumes that need to be mapped to make it work. However, I think the spec does have a good solution to the problem. Making it container friendly might be outside of the scope of the filebrowser product. It might be possible to create a base image that has the directory structure, environment variable configuration, and tooling for managing thumbnailers (i.e. installing/updating thumbnailers inside the container). If such a base image existed, then it would be simple for filebrowser to integrate with that base image and use it's tooling.

**Comment by RyannDaGreat** [comment]
Could we just steal thumbnails from the host OS? If you're using Ubuntu for example, Nautilus seems to already have found a way to generate thumbnails for even .blend files for example. Perhaps we could just hijack it?

**Comment by o1egl** [comment]
Filebrowser is supposed to run in a server environment with no desktop UI. In addition, Filebrowser is a cross-platform application, and we cannot be tied to specific OS implementations.
