### ISSUE TITLE
Timeout Error - Sharing same database with multiple docker container instance.

### ISSUE THREAD

**Issue by michaelsatish** [filebrowser/filebrowser#1929]
**Description**
Unable to share a single database file with multiple application instances. Is this working as designed? 

**How to reproduce?**
```sh
mkdir ~/test
cd ~/test

touch filebrowser.db

# Run the first instance.
docker run \
    -v ~/test:/srv \
    -v ~/test/filebrowser.db:/database.db \
    -u $(id -u):$(id -g) \
    -p 8080:80 \
    filebrowser/filebrowser

2022/04/27 19:08:48 Using config file: /.filebrowser.json
2022/04/27 19:08:48 Listening on [::]:80

# I can access the application at http://localhost:8080

# Run the second instance, sharing the same db, but on a different host port.

docker run \                                                                      
    -v ~/test:/srv \
    -v ~/test/filebrowser.db:/database.db \
    -u $(id -u):$(id -g) \
    -p 3000:80 \
    filebrowser/filebrowser

2022/04/27 19:11:12 timeout

```
Any help will be much appreciated.

**Comment by tyzbit** [comment]
Filebrowser does not support running multiple instances at once because when it starts it grabs an exclusive lock on the database file. Filebrowser uses https://github.com/asdine/storm which itself uses https://github.com/etcd-io/bbolt/ which ultimately tries to lock the file here:

https://github.com/etcd-io/bbolt/blob/a0458a2b35708eef59eb5f620ceb3cd1c01a824d/bolt_unix.go#L26-L27

It makes sense to grab an exclusive lock because if we had more than one process modifying the database, the state might change out from under us unexpectedly, causing all manner of issues.

If we wanted to allow multiple filebrowser instances, we would have to rewrite it to use a database for storing settings.

**Comment by michaelsatish** [comment]
Thank you for the explanation @tyzbit 

It'd be nice though to loadbalance the traffic going to the application.

**Comment by o1egl** [comment]
At this stage, Filebrowser is not designed to work in distributed high-load environments

**Comment by semmet95** [comment]
Hey everyone, since Filebrowser has been marked as "finished" I'm wondering if this feature is even on the roadmap? Would be great if it is, and I'd love to contribute :)

**Comment by hacdias** [comment]
No, not planned, there's no roadmap. Please read the README for the project status: https://github.com/filebrowser/filebrowser#project-status

**Comment by lukesoftware** [comment]
I'm having the same timeout issue when I programmatically add users, even
though I only have one instance running (on a dedicated VPS server). What's
the correct way to do this, via API? I'm currently doing it via CLI, but I
have to stop and start the service, which isn't ideal. Thanks for the reply.

Il giorno mar 3 mar 2026 alle ore 08:10 Henrique Dias <
***@***.***> ha scritto:

**Comment by tyzbit** [comment]
Although the project says it will consider PRs, I am not hopeful that it would consider adding multiple instances because of the complexity of the change. There are surely many places in the code where being the only instance performing some action is implicitly or explicitly relied upon. It would also be a large change, with lots of code changed and updated.

@lukesoftware I think the API is not intended for external usage. If you're doing serious user management continually, you may be nearing the edge of the scope of the project. You may be able to cobble together an external authentication mechanism like OAuth or LDAP and have Filebrowser apply permissions using hook authentication https://filebrowser.org/authentication.html#hook-authentication.

**Comment by lukesoftware** [comment]
Thanks for your replay @tyzbit, I've already tried to implements the
header/proxy auth, whitout success, but I will try again, if It Is the only
way.

Il Mar 3 Mar 2026, 14:17 Tyler Hawkins ***@***.***> ha
scritto:
