### ISSUE TITLE
User changable faveicon & custom textin place of "Filebrowser version"

### ISSUE THREAD

**Issue by Tusharkumar0012** [filebrowser/filebrowser#1975]
**Is your feature request related to a problem? Please describe.**

The problem is When custom branding is set (logo.svg) and one creates a shortcut of the website to home screen of Android,it automatically sets the default logo as the icon of the web-app/shortcut.

**Describe the solution you'd like**

There should be a similar approach to solving it as implemented for the logo.svg.

**Describe alternatives you've considered**

**Additional context**

**Comment by EDIflyer** [comment]
You can add custom favicons in `/[yourcustombrandingdir]/img/icons`:
![2022-07-15-22-05-39](https://user-images.githubusercontent.com/13610277/179315915-cb868f24-ff17-4aac-a7bc-f0561cd5fa51.png)
You need to add the PNGs and not just the ICO file otherwise the browsers seem to pick up the higher res files.
I think you might also need to add some of the other files (see example names) to get the right image for a shortcut on Android:
https://github.com/filebrowser/filebrowser/tree/master/frontend/public/img/icons
If there was a way to generate them all automatically from the SVG file that would be amazing, but not sure how do-able that would be!

**Comment by EDIflyer** [comment]
PS @Tusharkumar0012 I found that https://realfavicongenerator.net/ is an easy way to generate the full required list.

**Comment by Tusharkumar0012** [comment]
Appreciation & Thanks .
Will try to do it when get time .

Also need to figure out a way to write something else or disable this... ![disable_this.png](https://user-images.githubusercontent.com/50898840/179357211-49ac604a-b7be-4fdc-be18-c42d7e719557.png)

**Comment by EDIflyer** [comment]
I think for that bit you'd need to change the actual code itself as I see its specifically excluded from customisation in the docs - afraid that bit is beyond my knowledge 😂

**Comment by ramiresviana** [comment]
The `disableExternal` option can be used to hide the version and url from the Filebrowser text on the sidebar, it will also remove the report button from error notifications. There's no option to control the displayed text.
