### ISSUE TITLE
Support for network drive

### ISSUE THREAD

**Issue by Mr-KayJayDee** [filebrowser/filebrowser#1977]
**Describe the solution you'd like**
I and maybe many people here would like to be able to connect to their filebrowser server as a network drive on their computer.

**Describe alternatives you've considered**
I can use an external software that will map an sftp folder as a drive but i don't think that is the best way to do it.

**Comment by ramiresviana** [comment]
Filebrowser works by making calls to the filesystem, it does not handle drives.

**Comment by Tusharkumar0012** [comment]
You can host an smb server then mount that into ubuntu(or unraid whatever you are using) , then in docker-compose you can map tat as a volume to file-browser . this way you can mount/map the drive as a native smb share on any machine and also access from web browser .

more of a workaround solution but works great . because you get full 1gbps bandwidth when transferring files locally via smb share & you can access the drive remotly via filebrowser.
