### ISSUE TITLE
Fail2ban working example

### ISSUE THREAD

**Issue by okuzlu** [filebrowser/filebrowser#2103]
Couldnt find some example here. Maybe its useful for other who want to implement fail2ban.

**mount filebrowser log file to host docker compose:**

volumes:
  - ./filebrowser.log:/config/filebrowser.log
 
**/etc/fail2ban/filter.d/fail2ban.conf**

[INCLUDES]
before = common.conf

[Definition]
datepattern = `^%%Y\/%%m\/%%d %%H:%%M:%%S`
failregex = `\/[a-z]*\/[a-z]*: \d{3} <HOST> *`
ignoreregex =

**/etc/fail2ban/jail.d/filebrowser.conf**

[filebrowser]
enabled = true
port = 443
filter = filebrowser
action = iptables-allports[name=filebrowser, chain=FORWARD]
logpath = `<path to log file>`
maxretry = 3
bantime = 14400
findtime = 14400

**Comment by gmolinsm** [comment]
Hi there. I was struggling to make this work because even though Fail2Ban bans the ip, it takes no effect for some reason. For anyone undergoing this issue, the solution I found was to specify all ports in the ban actions:

[filebrowser]
enabled = true
port = 443
filter = filebrowser
logpath = `<path to log file>`
maxretry = 10
bantime = 10m
findtime = 10m
banaction = iptables-allports
banaction_allports = iptables-allports
