### ISSUE TITLE
Sharing account

### ISSUE THREAD

**Issue by QuocTrung76** [filebrowser/filebrowser#2118]
Can I share user accounts between Filebrowser and another framework account (e.g: Django framework)? So I can use the Filebrowser account to log in to Django.

**Comment by ramiresviana** [comment]
File Browser uses bbolt, but you may have some difficulties reusing it on other applications since the passwords are hashed and the database file is locked during the use. You should be able to integration Filebrowser utilizing the authentication hook, a new feature that will be available on the next File Browser version, check https://github.com/filebrowser/filebrowser/pull/1554.
