### ISSUE TITLE
I have not found a solid statement about support for PUT or POST uploads api.

### ISSUE THREAD

**Issue by elico** [filebrowser/filebrowser#217]
Is the software have any support for an upload or deletion of file using the POST\PUT\DELETE methods?
If so can it be documented?
Maybe an example using curl would help.

**Comment by hacdias** [comment]
Hello @elico!

Yes, I haven't documented that because I thought it wouldn't be needed. But File Manager supports those methods:

**Authentication**:
- **Path**: `/api/auth/get`
- **Method**: `POST`
- **Payload**: `{ "username": "username", "password": "password" }`
- It answers with a JWT token.

**REST**:
- Required HTTP Header: `Authorization: Bearer {token}`
- `GET/api/resource{path}` - Get file or path listing
- `DELETE /api/resource{path}` - Delete file or directory
- `POST /api/resource{path}` - Create file (content is the request body) or directory
- `PUT /api/resource{path}` - Update file (content is the request body)
- `PATCH /api/resource{path}` - Move/copy file. 
    - `Destination` header with the new path.
    - `Action` header with either "copy" or "move".

If you need more info, tell me 😄 
I may put a better version of this in the docs in the future!

**Comment by elico** [comment]
@hacdias thanks!
I will need to see how I am managing with this but it seems like a pretty straight forward and simple API.

Thanks!

**Comment by hacdias** [comment]
I'll close this then 😃 Anything else, just file another issue or reopen this one.

**Comment by 91wangmeng** [comment]
how can i upload a video ? can you provide detailed parameter specification

**Comment by weirdbricks** [comment]
in case someone comes across this thread, here's how I got a token with curl and use that token to upload a file:

```
# get the token - in this example I'm using the default username "admin" and password "admin"
# and the token is stored in the "TOKEN" variable
TOKEN=$(curl -X POST http://127.0.0.1:3000/api/auth/get -d '{ "username": "admin", "password": "admin" }')
# upload a file and present the token we got earlier
curl --header "Authorization: Bearer $TOKEN" --progress-bar --upload-file test.log.gz http://127.0.0.1:3000/api/resource/
```

hope it helps!

**Comment by guyskk** [comment]
https://github.com/guyskk/filebrowser-upload solve the problem!

**Comment by ntaapp** [comment]
I have tried to get Token using /api/auth/get however, I got 404 Not Found from server. 

Anyone have any update for new version?

**Comment by ntaapp** [comment]
> https://github.com/guyskk/filebrowser-upload solve the problem!

This does not work either

**Comment by ntaapp** [comment]
I finally, know how to get the Token and using it to upload the file
Writing here for anyone needs.
- To login: using api: POST  http://localhost:port/api/login and json in body with username and password => You will get the Token in response body. Copy it and using in other endpoints.
- To upload file using api:  POST http://localhost:port/api/resources/yourfilename.txt    and in the header you need to include: X-Auth with Token got from login endpoint. send it with file.
- To create folder using api: POST http://localhost:port/api/resources/yourfolder/    and in the header you need to include: X-Auth with Token got from login endpoint.
