### ISSUE TITLE
Archive Extraction Feature

### ISSUE THREAD

**Issue by ferronrsmith** [filebrowser/filebrowser#222]
It would be nice to be able to extract archives

**Comment by hacdias** [comment]
That's a good idea! 😄

**Comment by MarvBob** [comment]
I am very interested in this feature. Any idea about a possible release ?

**Comment by hacdias** [comment]
I'd like to implement this, but I've been a bit busy. Would you like to try to start this @MarvBob @ferronrsmith? 😄

**Comment by deanet** [comment]
any update of this issue ?

**Comment by DeyV** [comment]
I did this, but I'm not sure, that it is best method to do that. 

https://github.com/DeyV/filebrowser-dockercompose

1. added p7zip to docker
2. simple bash to unpack archives in directory and remove them
3. this bash as additional command  "commands": ["unpack"]

**Comment by eine** [comment]
@DeyV, installing additional dependencies in the host (be it the 'real' host or the docker image/container) is an option, which can be used right now as in your example. However, I think that this issue is focused on integrating this feature in the code base, so that filebrowser can be still used as a standalone single binary app. E.g., https://github.com/mholt/archiver can be used to provide such functionality.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by JojiiOfficial** [comment]
Hey
This repository doesn't seem to be archived and I can't find any information on the Readme.
Given that Filebrowser doesn't seem to be discontinued or archived, can we reopen this issue? It seems like a good feature for such an application
