### ISSUE TITLE
Bulk Download Control

### ISSUE THREAD

**Issue by ados8** [filebrowser/filebrowser#2347]
**Is your feature request related to a problem? Please describe.**
Currently giving users download access also allows them bulk download and compression.
This means users accidentally bulk download since it's a dedicated button which also puts the server under load compressing.

**Describe the solution you'd like**
Separate the download access from bulk download and compression.
Example access levels could be:
- Download
- Download Bulk
- Compression

**Describe alternatives you've considered**
The download button could be moved in line with the folder/file making it more clear to the user which item they would download.

**Additional context**

**Comment by giozucca** [comment]
I would like to bump this. I opened an issue for the same feature request. It would be much more efficient to be able to download, say, 20 files as septate downloads rather than compressing them. Even providing a list of share links (one for every file in a folder) and then have a program (such as jdownloader or IDM) handle downloading the list of share links.
