### ISSUE TITLE
Unable to Play WAV Files

### ISSUE THREAD

**Issue by cmurrayis** [filebrowser/filebrowser#2482]
Running V2.23.0 and unable to play wave files in the browser. I am able to download and play the files however does not appear to allow them to play from the browser.

I suspect a possible permission issue however cannot see where FileBrowser logs web errors?

**Comment by ray-yuruisoft** [comment]
it not the filebrower`s business

**Comment by cmurrayis** [comment]
Are you able to say why?

The files play fine via the original source interface?

**Comment by ray-yuruisoft** [comment]
absolutely！you can google the reason



---Original---
From: ***@***.***&gt;
Date: Wed, May 31, 2023 05:10 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [filebrowser/filebrowser] Unable to Play WAV Files (Issue #2482)




 
Are you able to say why?
 
The files play fine via the original source interface?

**Comment by cmurrayis** [comment]
Sorry @ray-yuruisoft I don't follow - I have googled already which lead to meany possible reasons such as the browser not supporting the codec however the same browser can play the files on the PBX interface to which the calls are being sync'd to File browser on another server - Both use the same Chrome media player.

The files are PCM - 16bit 8khz which is supported by Chrome for playback.

I was not able to find a definitive reason which is why I posted here.

PBX:

![image](https://github.com/filebrowser/filebrowser/assets/89428026/aae7dcb4-2d62-4bce-90e8-df568a4fa49d)

File Browser with the same file copied:

![image](https://github.com/filebrowser/filebrowser/assets/89428026/96913e2f-05ec-4af1-b21c-1eb50030fcbb)

**Comment by ray-yuruisoft** [comment]
sorry,i was wrong!maybe filebrower doesn`t has this function
you can use this chrome plug to solve your problem
https://chrome.google.com/webstore/detail/avi-wmv-mov-video-play-pr/nacdgolbkcofkjfekpnfodnbhadjagbe?hl=zh_Hans_CN
https://nsspot.herokuapp.com/videoplayer/




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月31日(星期三) 上午7:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [filebrowser/filebrowser] Unable to Play WAV Files (Issue #2482)





 
Sorry @ray-yuruisoft I don't follow - I have googled already which lead to meany possible reasons such as the browser not supporting the codec however the same browser can play the files on the PBX interface to which the calls are being sync'd to File browser on another server - Both use the same Chrome media player.
 
The files are PCM - 16bit 8khz which is supported by Chrome for playback.
 
I was not able to find a definitive reason which is why I posted here.
 
PBX:
 

 
File Browser with the same file copied:
