### ISSUE TITLE
unWanted behaviour

### ISSUE THREAD

**Issue by Tusharkumar0012** [filebrowser/filebrowser#2520]
**Description**
the files are available at the download url even after logout. 
so if you are viewing the file yourdomain.com/files/testfile.pdf , after logout it can be viewed/downloaded at yourdomain/api/raw/filename.pdf?auth=********blablabla********xyz
It is also available after clearing browser cache or even opening with a different device on a different network.

also there are files under-
yourdomain/api/preview/thumb/filename.pdf?auth=**********blablabla***********xyz

Expected Behaviour-
the auth token should be invalid after the user has been logged out.

This means files are vulnerable. Please fix it.

**Comment by Hariama** [comment]
Note: this has been fixed after another user disclosed the same vulnerability weeks later specifying how this could lead to RCE a couple of days ago (ref., https://github.com/filebrowser/filebrowser/issues/2570). The issue can be closed.

**Comment by Tusharkumar0012** [comment]
then how to update filebrowser without reconfiguring it ? I am using it as a docker container.

**Comment by Hariama** [comment]
You can either force this by spinning down your filebrowser-container, and running `sudo docker pull filebrowser/filebrowser:latest`, or utilizing a tool like watchtower to automatically watch for image-updates (ref., the xss-vuln has been removed in v.2.24.0, which has also been released as a docker-image on Docker Hub since yesterday)

**Comment by Tusharkumar0012** [comment]
Oh. Thanks. That seems easy enough.
