### ISSUE TITLE
More specific rules for users on specific directories

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#2526]
Is there a way to, or maybe add this feature?

On the storage drive are some directories in which I would like a user to be able to read the files, but not be able to delete, rename, or move the files. And there are some other directories where I would like the user to have full control of the files. In the User Settings tab of a user, I can add a rule, but this rule just hides the entire directory from a user. Is there a way to have more specific rules?

**Comment by ndm13** [comment]
I'm having this exact issue: I want users to be able to upload to their own user folders, but to only be able to download from other folders.  As it stands, I can either give users full control of their own folders or no control over a global folder.  This is very frustrating in what is otherwise a very nice app.

**Comment by ndm13** [comment]
Unstale: still an issue

**Comment by ndm13** [comment]
Unstale: still an issue
