### ISSUE TITLE
Session Timeout

### ISSUE THREAD

**Issue by Tarsman013** [filebrowser/filebrowser#2553]
**Description**
when uploading multiple, large files, I notice that after about an hour, the client logs out and all transfers fail

**Expected behavior**
the client wont log out without clicking "log out"

**What is happening instead?**
the client is automatically logged out after a period of "inactivity" (not clicking) even if an upload is in the process

**Additional context**
I am attempting to move a repository of large videos (for a youtube channel), when my client logs out, the uploads fail. 

**How to reproduce?**
do a long upload on slower internet, anything over an hour seems to be enough, but i do not personally have an exact number

**Possible way to resolve**
add the ability to change the timeout of a user

**Comment by brianfromm** [comment]
@Tarsman013, this has been fixed in PR #5546, which is included in release v2.48.0 and later.

**The solution:** You can now configure the session timeout using the `tokenExpirationTime` setting. The default is 2 hours.

**To increase the timeout for existing installations:**

```sh
filebrowser config set --tokenExpirationTime 6h
```

Then restart File Browser.

**For new installations**, you can set this in your configuration file before first run:

```json
{
  "tokenExpirationTime": "6h"
}
```

Or via environment variable: `FB_TOKEN_EXPIRATION_TIME=6h`

Valid duration formats include `"2h"`, `"30m"`, `"24h"`, or combinations like `"2h30m"`. You can change `6h` to whatever value you need for your situation.

See the [troubleshooting documentation](https://filebrowser.org/troubleshooting#session-timeout) for more details.
