### ISSUE TITLE
Customizing admin credentials via config/flags

### ISSUE THREAD

**Issue by jzaefferer** [filebrowser/filebrowser#257]
I'm interested in using this project in a managed hosting context, where customers could use filemanager to access files. For that the default admin/admin credentials are a problem. Is it reasonable to add config/flags to set the default values for those?

It looks like it  could be a simple code change (plus a bit more effort for tests + documentation): https://github.com/hacdias/filemanager/blob/26e1e44d602b9bca5b1e20771095579f4a1c2b43/filemanager.go#L193-L196 - instead of using the string "admin" here, read a value from the config (not sure yet how to do that).

**Comment by MikeMichel** [comment]
config via env vars would be also nice https://github.com/kelseyhightower/envconfig

**Comment by jzaefferer** [comment]
@hacdias since you added the label, does that mean you approve the idea?

Could you point me in the right direction for reading the username and password from the config?

**Comment by hacdias** [comment]
Hey @jzaefferer!

Yes, I like the idea and would like to implement it. Unfortunately, I haven't had much time for this. If you'd like to give a hand, you could check this files:

- [Flags](https://github.com/hacdias/filemanager/blob/master/cmd/filemanager/main.go)
- [Where the default pass is set](https://github.com/hacdias/filemanager/blob/master/filemanager.go#L192)

If you need anything, just ping me and I'll try to answer ASAP.

**Comment by jzaefferer** [comment]
Thanks for the pointers. I'll give that a try (or ask a colleague).

**Comment by jzaefferer** [comment]
Its possible that the only required change is this: https://github.com/var2dan/filemanager/commit/351dd8ee1244e231eb77b6efec57cb95dc2ab07b

Not sure if that still merges into current master; probably also needs updates to tests and docs.

**Comment by eine** [comment]
portainer/portainer is a partially open source web app where the backend is written in golang (although the frontend is based on Angular, instead of Vue.js). Having a look at their codebase might be interesting for anyone trying to implement this. See http://portainer.readthedocs.io/en/stable/configuration.html#admin-password

**Comment by ncresswell** [comment]
Funny enough, im actually looking to use this project within Portainer as a way to provide users with a way to download files from existing containers persistent volumes.

**Comment by eine** [comment]
@ncresswell, indeed, I got to know this project when you mentioned it in portainer/portainer#1380 in november. Do you think if the know-how you have in portainer about this issue can be somehow ported here?

**Comment by ncresswell** [comment]
We have actually already added filebrowser as a template in Portainer, but we want to get even closer integration.

Where is the username/password actually stored? Is it embedded in a db or encrypted file somewhere?

Rgds,

Neil Cresswell

On 15/06/2018, at 4:09 PM, 1138-4EB <notifications@github.com<mailto:notifications@github.com>> wrote:


@ncresswell<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ncresswell&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=0fx0h4vB56iTLpw2McH1ZD6TqG_QGpbggVOB-PfMJpM&m=vF_MO7_bc6o-dwelDVAmy1PTrv5eH-Dy1q3IIw2C0FU&s=vuyWnkvmBHkesp59BSc5NmwkuUxo1uk7idCVv4HcpuM&e=>, indeed, I got to know this project when you mentioned it in portainer/portainer#1380<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_portainer_portainer_issues_1380&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=0fx0h4vB56iTLpw2McH1ZD6TqG_QGpbggVOB-PfMJpM&m=vF_MO7_bc6o-dwelDVAmy1PTrv5eH-Dy1q3IIw2C0FU&s=Z45T5bcdKsf51tP1ccVPKlVYQfy4zFbRHSd-UmEl6IE&e=> in november. Do you think that the know-how you have in portainer about this issue can be somehow ported here?

**Comment by eine** [comment]
@ncresswell it is saved in the database, but the default values are hardcoded. See comments https://github.com/filebrowser/filebrowser/issues/257#issuecomment-353321710 and https://github.com/filebrowser/filebrowser/issues/257#issuecomment-396936650 above.

Source at https://github.com/filebrowser/filebrowser/blob/master/filebrowser.go#L193-L196

In order to add a flag: https://github.com/filebrowser/filebrowser/blob/master/cmd/filebrowser/main.go#L27-L117

This implementation, referred by @jzaefferer, uses environment variables: https://github.com/var2dan/filemanager/commit/351dd8ee1244e231eb77b6efec57cb95dc2ab07b

**Comment by hacdias** [comment]
Hello! Will be available on v2.0! I'm closing this to remove the clutter in the meanwhile. For more info, check #574 and #575!
