### ISSUE TITLE
Option to use PNG instead of SVG for branding logo

### ISSUE THREAD

**Issue by BCalupas** [filebrowser/filebrowser#2597]
**Is your feature request related to a problem? Please describe.**

Right now filebrowser only accepts .svg as the branding logo 

**Describe the solution you'd like**

I would like an option to use a PNG file for the logo branding (currently only SVG). Hope there is an option in the settings to upload the logo there.

**Describe alternatives you've considered**

Hardcoding, css, etc.

**Additional context**

**Comment by notsatan** [comment]
Hi, I'm facing some friction because of this issue as well — is there any way I can contribute to get this rectified?

From a cursory glance, seems like this is being caused by the filename being hard-coded in `constants.js`

https://github.com/filebrowser/filebrowser/blob/01f7842a18beb6efdadd7bce522991c1534cdb12/frontend/src/utils/constants.js#L10

Can we leave the filename to the user? Maybe allow the user to supply filename and the extension as an environment variable, with the current value as a default for a fall-back (just bouncing ideas at this point)

**Comment by notsatan** [comment]
@o1egl @hacdias @Equim-chan (wasn't sure you guys would get a notif for a closed issue)

**Comment by Platway** [comment]
You can embed an PNG into the SVG, like this:

`<svg width="192" height="192" xmlns="http://www.w3.org/2000/svg">
  <image width="192" height="192" href="data:image/png;base64,......" />
</svg>`
