### ISSUE TITLE
Command Runner 'After Upload' not executed after a file is uploaded

### ISSUE THREAD

**Issue by saulchristie** [filebrowser/filebrowser#2626]
**Description**
'After upload' Command Runner is not executed following a file upload.

**Expected behaviour**
'After upload' Command Runner to be executed following a file upload.

**What is happening instead?**
By way of user experience, nothing is happening. File uploads fine, but no command is executed.

**Additional context**
The error occurs in v2.24.2, running bare metal on Ubuntu. Defined 'after upload' command has not been modified since the functionality worked, and syntactically identical commands defined in other Command Runner areas are still executed as expected.

**How to reproduce?**
Define a command to be executed after a file upload within FileBrowser's 'Command Runner' config.
Upload a file.
Observe the defined command is not executed.

**Files**
N/A

**Comment by kafeinnet** [comment]
I was just going to open an issue about that. I confirm this issue, I have the exact same problem with filebrowser in a docker environment. Reverting to 2.24.1 fix the problem.

With 2.24.1 I can see this log (here I uploaded a `lemmings.mp4` file):
```
2023/08/29 17:37:21 Using config file: /.filebrowser.json
2023/08/29 17:37:21 Listening on [::]:80
2023/08/29 17:38:22 [INFO] Blocking Command: "/opt/ffmpeg/convert.sh /srv/lemmings.mp4"
```

With 2.24.2 the last line never appears.

**Comment by ghost** [comment]
Can confirm, I had to revert to 2.23.0 to get it to work again

**Comment by ruihaut** [comment]
Issue still here on 2.27.0

**Comment by AndresJ551** [comment]
Same, trying to curl "after upload" doesn't work, the same with "before upload".
Have no error message on logs.
Using the same command after delete or after copy works perfectly.

I'm using the latest tag from https://hub.docker.com/r/filebrowser/filebrowser

**Comment by mi-bauer** [comment]
I looked into the codebase and for me it looks like this (please correct me if I'm wrong):
The cause of this issue is the integration of [this](https://github.com/filebrowser/filebrowser/pull/2145) feature. With the feature of chunked uploads new routes for '/api/tus' were introduced. The newly introduced [corresponding handlers](https://github.com/filebrowser/filebrowser/blob/master/http/tus_handlers.go) are missing the call of the RunHook method which is present in [other handlers](https://github.com/filebrowser/filebrowser/blob/master/http/resource.go). I currently don't know where we should include the RunHook method in the new handlers. It looks like the backend never knows when a file is done uploading. @TobiasGoerke do you have an idea on how we could fix this?

**Comment by TobiasGoerke** [comment]
You're right, the backend can't know for sure whether the upload is completed.
The [frontend knows](https://github.com/TobiasGoerke/filebrowser/blob/master/frontend/src/api/tus.js#L42) though and could send a finalizing request to the server.
@o1egl WDYT?

**Comment by jrukavina** [comment]
I have been trying to fix this issue for a few days now since I noticed it has been present for a while (since v2.24.0).
I am inexperienced with web development and found it complicated to solve as tus didn't communicate to backend that the file finished uploading. Fortunately, I came across this fix #2767  which I tested locally, and it seems to work as expected.
@TobiasGoerke could this fix be considered for the next release?

**Comment by jrukavina** [comment]
I should have tagged @o1egl instead probably

**Comment by gingerbeardman** [comment]
Still an issue with 2.30.0 (May 2024) and was introduced in 2.24.0 (July 2023)

I am also still running 2.23.0 (November 2022!) because I rely on running these commands.

**Comment by Mubelotix** [comment]
The stale bot is driving me crazy. There are hundreds of ongoing issues that are closed

**Comment by gingerbeardman** [comment]
It's a plague infecting many projects. I've seen people, presumably neat freaks with some sort of OCD, go around adding them to repos to "clean them up". They seem to like looking at blank issues sections, and full closed section. Like sweeping things under the carpet and pretending they don't exist. A high percentage of issues are open because they haven't been dealt with!

PR #3422 Remove stale bot

**Comment by BestTrolley** [comment]
Problem still persists, and to make matters worse, with plesk for example, it is not possible to go all the way back to 2.23! 
This really is a deal breaker, since the users don't get notified about new uploads.

**Comment by Trackhe** [comment]
It is not working.

**Comment by hankthetank27** [comment]
I'm also experiencing this issue and am now rolled back to v2.23..
