### ISSUE TITLE
How to mount external device to filebrowser

### ISSUE THREAD

**Issue by justnotiyann** [filebrowser/filebrowser#2827]
I installed the file browser on the Armbian OS,
Everything went smoothly until I wanted to connect the external HDD and automount it using the following link instructions:

[Auto Mount Drive Armbian](https://unix.stackexchange.com/questions/681379/usb-flash-drives-automatically-mounted-headless-computer)

The script successfully read external data into the media folder.
The problem is when I checked with the terminal, the device managed to read all the data but when I opened it in a filebrowser it couldn't

**Comment by glowinthedark** [comment]
[automounting](https://superuser.com/questions/1265412/automounting-usb-drives-on-a-headless-systemd-linux-box) is probably not the issue here (`apt install usbmount` is probably all you need); if your mount points are within the fb's root folder then it's likely a permissions issues, especially if the drive is ext2/3/4
