### ISSUE TITLE
File requests - public uploads via shared link

### ISSUE THREAD

**Issue by baldemar-wuda** [filebrowser/filebrowser#2836]
**Is your feature request related to a problem? Please describe.**
I would love to have the ability to collect files from people by simply sending them a link to a folder (where they can upload files without a need to log in). 

**Describe the solution you'd like**
Shared link with option to allow uploading to a folder (by non-logged users).

**Comment by swatoner** [comment]
My 2cents, this is not practical and security risky.
Since a URL can be easily found and abused.
Even onedrive verified by e-mail or a onetime password.
Such actions, will required a redesign of the application in total and its simplicity.
So this project/solution might not be what you need for.

**Comment by hgouveia** [comment]
I also would like to have this feature

**Comment by jclendenan** [comment]
This would be a great feature.  No access to any files that are uploaded should be provided.  It's a blind drop box type thing.
Do not allow upload of a file if it already exists in the folder.
Do not allow overwriting of any file/folder.

**Comment by Zouizoui78** [comment]
This feature would be very useful and is the only thing I miss from my previous setup with nextcloud. I had quite a few folders that I shared with friends where they could upload stuff.

**Comment by max-tet** [comment]
I'd also vote for this feature. I see no particular security risk if the URL is unguessable just like shares.

Also, it would be useful to be able to set a size limit and expiry time for each upload link.

**Comment by Mitho27** [comment]
I also would vorte for it. Also users might chose to additionally put the files in encrypted containers.

**Comment by d-Rickyy-b** [comment]
I think this is a great suggestion. Upload shares are really great for collecting files from multiple people at the same time. To name one use case: You married your SO and had a great party with lots of family and friends. After the party you want to collect the pictures from all your guests in order to share them with everyone afterwards. Of course you can add accounts for each guest but that's increasingly complicated the more guests there are.

Another example: Assume you're using filebrowser in business context. You're working with a client who needs to send you some files. Your proxy server prevents you from accessing random cloud storage for security reasons. In order to receive the files, you send an upload link to the customer.

One upload link/share should allow an unauthenticated user in possession of the link to upload files to a single directory. Similar to download links you could have an optional password.

Btw. this is not a security risk. Many file hosting platforms have such a feature (Dracoon, Nextcloud, OwnCloud, etc.). You could generate longer links that are harder to brute force. And you can limit the share duration the same way as with download shares.

**Comment by Cjkeenan** [comment]
I also would love this feature. Sure it "could" be used in an abusive way, but a simple banner or big suggestion to limit the duration with a checkbox that you acknowledge the risk and want a permanent duration would be fine too. File Browser is self-hosted after all, so anyone hosting this needs to take security into their own hands.

**Comment by tulku** [comment]
A way to allow people to upload files using share links would be a great addition. This also has been requested several times.

I found other issues with the similar requests:
https://github.com/filebrowser/filebrowser/issues/1435
https://github.com/filebrowser/filebrowser/issues/2411
https://github.com/filebrowser/filebrowser/issues/2652

**Comment by Glideh** [comment]
A public drop zone would be a great addition, and even if FileBrowser is far from a NextCloud (Thank God), wouldn't it have a good place in FileBrowser's logic ?
After all it remains a shareable directory link.
Obviously I'm not talking about the time required to dev that though, I guess it's a quite big thing.

**Comment by Rage997** [comment]
I believe this issue should be re-opened as this feature is not been added
