### ISSUE TITLE
unable to deploy docker container, it gets into some internal error,

### ISSUE THREAD

**Issue by P-Y-R-O-B-O-T** [filebrowser/filebrowser#2936]
**Description**

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by P-Y-R-O-B-O-T** [comment]
sometimes it says /database/filebrowser.db is a directory
sometimes it says permission denied
sometimes it gives something like this :
[custom-init] No custom files found, skipping...
[ls.io-init] done.
panic: While parsing config: invalid character 'p' looking for beginning of object key string

goroutine 1 [running]:
github.com/filebrowser/filebrowser/v2/cmd.initConfig()
	/home/runner/work/filebrowser/filebrowser/cmd/root.go:420 +0x32a
github.com/spf13/cobra.(*Command).preRun(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:946
github.com/spf13/cobra.(*Command).execute(0x126e040, {0xc0000340b0, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:876 +0x59e
github.com/spf13/cobra.(*Command).ExecuteC(0x126e040)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/filebrowser/filebrowser/v2/cmd.Execute()
	/home/runner/work/filebrowser/filebrowser/cmd/cmd.go:9 +0x1a
main.main()
	/home/runner/work/filebrowser/filebrowser/main.go:8 +0xf

**Comment by rluetzner** [comment]
I've seen a few of these myself.

## /database/filebrowser.db is a directory

There's a comment in the installation instructions that's easy to miss. If the database does not yet exists, you'll have to create an empty file manually. Otherwise Docker will create the path as a directory, which is not what you want.

So on your Docker host you'll need to

```bash
rm -rf /path/to/filebrowser.db
touch /path/to/filebrowser.db
```

.

## Permission denied

I ran into this, because I initally ran the container as root (without adding a `user` or `PUID` in the compose file). That generated a few files, including the faulty `filebrowser.db` directory that the container could not access. You can

```bash
# Check the current permissions
ls -la /path/to/filebrowser-data
# Set the correct permissions you want
sudo chown -R <uid>:<gid> /path/to/filebrowser-data
```

. I'm 95% sure that this issue will just go away if you do the first thing I mentioned. 🙂 

----

As for the last thing, I really have no idea. Have you checked that the config file is a valid JSON document? Other than that I could imagine that it's an issue with file endings. Are you running this on Windows by any chance?

**Comment by P-Y-R-O-B-O-T** [comment]
thanks bud, good work on this file manager

Maybe we can collab on something, i have a good enough repo too

try to see some of my work
