### ISSUE TITLE
LDAP & Active Directory (AD) Sync

### ISSUE THREAD

**Issue by berserkwarwolf** [filebrowser/filebrowser#301]
First of all, this is an awesome App.

I'm writing to ask if there are any plans to implement AD sync. File Manager makes sense for small businesses, and some of us have AD, it would be cool if we could sync our users.

Thank you.

**Comment by maweck** [comment]
I would also be quite interested in having the LDAP for Authorization to combine it with #471 

So in my case the username would be provided through a header, but the filebrowser instance would need to check all other properties (Full name, email, general access rights) from an LDAP. 

We also have some snippets for an LDAP connection in GO available, but I think this ticket is more than just adding it and I guess it also includes some changes in the UI.

@1138-4EB once you have some time to think about this, could you maybe provide some thoughts about the following points:
- Should there be some kind of parameter that allows you to specify if the internal DB or an LDAP should be used as the user base?
- What are the places where this switch has to happen?
- From my point of view filebrowser should show the user management at all when LDAP is configured - Do you agree? (So adding and removing users would be disabled in that case -> It has to be done in the LDAP itself).

**Comment by eine** [comment]
Hi @maweck! IMHO user management and interactions with the database require a rework. See #489. The flows need to be clarified, in order to allow further extensions.

It would be rather straightforward to rely on an LDAP for authentication, as you did with the proxy. However, I don't think that the database can be replaced, because it contains more info than just usernames and passwords. Disabling the addition of new users might be an option; but parameters for existing users should still be editable. Therefore, a mechanism would be required to decide what to do when:

- A user exists in the DB but not in LDAP.
- A user exists in LDAP but not in the DB. I.e. automatic addition of users should be optional (not default).
- A user exists in both the DB and LDAP, and some parameters need to be updated in the DB.
- (Potentially) Some users are set up in the config file and are also found in LDAP.

Furthermore, I think that it should be possible for LDAP and non-LDAP users to coexists in the DB. So LDAP would be an (optional) authentication option and password would be another (optional) authentication method. Indeed, this could be extended to the proxy 'authentication'. So, there would be a precedence order:
- `If` noauth is enabled; go in.
- `Else if` the proxy header is present:
  - `If` the user has proxy access enabled; go in.
  - `else` error or jump to next option (if available).
- `Else if` LDAP authentication is enabled for the user:
  - `If` it exists in the LDAP service
    - `If` it is properly logged in; go in.
    - `else` error (not allowed) and/or jump to next option (if available).
  - `else` error or jump to next option (if available).
- `Else if` password access is enabled for the user:
  - `If` password is correct; go in.
  - `else` error.
- `Else` access not allowed.

As you can foresee, this is a not so easy task, because it requires diving into the codebase. I have not done it myself (yet), so I cannot help pointing the places where changes should be made. @hacdias, who is the creator, might provide a clearer view.

**Comment by maweck** [comment]
Hello @1138-4EB ,

thank you once again for taking so much time for us :+1:  

> I don't think that the database can be replaced, because it contains more info than just usernames and passwords. 

Yes, but I think when an LDAP is used, the Database should not manage users at all. I think LDAP should always be the single point of user management in your company.

> Disabling the addition of new users might be an option; but parameters for existing users should still be editable.

Yeah, that is also true - But that is something which the one decides who configures the LDAP -> Does he provide a read only account for the LDAP connection or can this account also write? In tools like Jira, Jira tries to write into the LDAP and returns an Error like "LDAP is read-only" if it is the configured LDAP user is not allowed to write.

>Furthermore, I think that it should be possible for LDAP and non-LDAP users to coexists in the DB. So LDAP would be an (optional) authentication option and password would be another (optional) authentication method. Indeed, this could be extended to the proxy 'authentication'.

This is exactly how a lot of tools do it, but I could expect that it is quite complex to implement. But in general: Would love to see that too.

> As you can foresee, this is a not so easy task, because it requires diving into the codebase. 

Yip, sad, but true :(

**Comment by Equim-chan** [comment]
I think now that there are so many ways to do the authorization, maybe we can make an interface for this:

```go
type Auther interface {
    Auth(http.Header) (authorizedUser *User, err error)
}
```

So others can write plugins very easily as well.

**Comment by maweck** [comment]
I guess authentication plugins are a way a lot of tools go for (e.g. Nexus3, Jira, ..). So providing this endpoint and a plugin mechanism in general is something that will for sure be useful.

**Comment by omaidb** [comment]
AD和LDAP的建议真是太赞了。早日完成该方案

**Comment by omaidb** [comment]
The AD and LDAP recommendations are really great. Complete the program as soon as possible

**Comment by ttimpe** [comment]
This project seems perfect for those use cases where you don't need all the NextCloud/owncloud features. But it needs AD/LDAP functionality to be useful for me. And then the files should be owned by the actual LDAP user, not some kind of www-data user.

**Comment by nambrosch** [comment]
@ttimpe you're making the assumption that the ldap user exists on the host that's running filebrowser.  My use case is authenticating active directory users so they can upload files to a website.  Those users (intentionally) do not have local unix accounts.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
