### ISSUE TITLE
RAM Usage

### ISSUE THREAD

**Issue by k33n8nc** [filebrowser/filebrowser#3010]
**Bug**
When uploading files, the RAM get filled up but never cleaned after (tested for 10 days) up to 256 GB RAM. I expect the RAM to fill up for some time and once done clean up. However the RAM never cleans up. The more you upload / download the more it's get filled once filled, it stays 99.9%

**Env**
Issue present with: Proxmox VME -> Ubuntu Server -> Docker Container

**Reproduce:**
Run Proxmox VM, docker-compose the filebrowser, set db permissions, start upload/download few gigs, see RAM fill up and never clear.

**Comment by andor-pierdelacabeza** [comment]
That could maybe be filesystem cache or other thing. To have a bit more information of the origin of that RAM usage could you run from the container or the Docker host...

To get the top 10 memory using processes:
`ps -eo pmem,pcpu,rss,vsize,args | sort -k 1 -n -r |head -n 10`

A bit more detailed memory report:
`cat /proc/meminfo`

**Comment by k33n8nc** [comment]
Thank you for helping out! Indeed the cache and inactive files. I started up a new container and made some screenshots right after. Then i did some uploading to filebrowser and made screenshots again. You can see the difference.

**Memlog inital**
<img width="280" alt="memlog initial" src="https://github.com/filebrowser/filebrowser/assets/38896281/b841a955-ba32-4771-9544-9de221a24d62">

**Memlog fludded**
<img width="257" alt="memlog fludded" src="https://github.com/filebrowser/filebrowser/assets/38896281/8c666834-6217-4d2f-b0e6-01e424eed270">

**Top 10 inital**
<img width="1091" alt="top10 initial" src="https://github.com/filebrowser/filebrowser/assets/38896281/98ac47ca-127f-4b06-8b96-86e7e48ce261">

**Top 10 fludded**
<img width="1645" alt="top10 fludded" src="https://github.com/filebrowser/filebrowser/assets/38896281/6a18c8c5-ff5b-495f-a453-eaf6b30f8372">

**Comment by niubility000** [comment]
Maybe just reboot your system daily automatically. It will clean up the RAM.

**Comment by andor-pierdelacabeza** [comment]
Shouldn't be necessary to reboot, as almost all is cache and it's available for other software as needed. Although "Mem Free" reports very little memory, we can see that "Mem Available" is almost 64GB of RAM, and all that memory we'll be freed if needed by other software. Yeah i Know, it's confusing. Even kernel developers feel [it's confusing](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773).

@k33n8nc , although it's not necessary for the correct function of your OS, if for some reason you want to force clearing that cache, you can run this from the root user:

`sync && echo 3 | sudo tee /proc/sys/vm/drop_caches`

That will signal the OS to commit to disk all the pending writes, and then clear the disk cache.

That behavior is very well explained in this site that I visited again and again, because it keeps happening and you never remember exactly why :) : 

https://www.linuxatemyram.com/

**Comment by k33n8nc** [comment]
Thanks, indeed @andor-pierdelacabeza it's available. I stumbled upon https://www.linuxatemyram.com/ and wanted to share this here, only to find it was already here! Thanks all for helping me out, after all it's seem like a misunderstanding on how things work from my side.

`free -m`

Gives a nice overview where available in linux terms means "used, but can be made available". It's a performance benefit that's a little confusing when you just look at the numbers / graphs / free space.
