### ISSUE TITLE
Healthcheck fails in Docker with default .filebrowser.json: curl: (3) URL rejected: Bad hostname

### ISSUE THREAD

**Issue by CorySanin** [filebrowser/filebrowser#3085]
**Description**

This is a regression caused by #2938. Healthcheck fails due to [.filebrowser.json](https://github.com/filebrowser/filebrowser/blob/master/docker_config.json) having an empty address property. The healthcheck script used to default to localhost, now it defaults to empty string.

**Expected behaviour**

healthcheck script calls /health endpoint

**What is happening instead?**

curl fails, script exits with code 1

**Additional context**

I _think_ this can be fixed by setting `address` to "localhost" in [docker_config.json](https://github.com/filebrowser/filebrowser/blob/master/docker_config.json)

**How to reproduce?**

```
docker run --rm -p 8080:80 filebrowser/filebrowser:v2.28.0
```
and wait for healthcheck

**Comment by smgsmagus** [comment]
same here:
![fileb](https://github.com/filebrowser/filebrowser/assets/161730255/adacf7a7-027e-4a31-a86a-8c7a2e039a62)

**Comment by Zulux91** [comment]
So I've run into the same issue. After some debugging when trying the healthcheck.sh inside the container (with some echo to see whats going on) this is what worked for me. The default v2.28.0 healthcheck.sh file looks like this:
```
#!/bin/sh
PORT=${FB_PORT:-$(jq .port /.filebrowser.json)}
ADDRESS=${FB_ADDRESS:-$(jq .address /.filebrowser.json)}
ADDRESS=${ADDRESS:-localhost}
#BEGIN DEBUG ECHOS
echo "PORT=$PORT"
echo "ADDRESS=$ADDRESS"
echo $ADDRESS:$PORT
#END DEBUG ECHOS
curl -f http://$ADDRESS:$PORT/health || exit 1
```

When trying to run that you get:
```
/ # sh healthcheck.sh
PORT=8080
ADDRESS=""
:8080
curl: (3) URL rejected: Malformed input to a URL function
```

I don't have my address section populated on the filebrowser.json file since it wasn't necesary for v2.27.0 and the script should default to localhost in any case. I'm very unfamiliar with Bash but for me it seems like for some reason the command `ADDRESS=${ADDRESS:-localhost}` is not running because of the empty double quotes when it should return empty (again, bash is very new to me so feel free to correct my thinking). I asked deepseeker coder AI model the following after presenting it with the script for some context: 

> How can I do to not get double quotes here: ADDRESS=${FB_ADDRESS:-$(jq .address /.filebrowser.json)}

And its answer was that i should use the `-r` or `--raw-output` option in `jq`. So I added said option and the result after running the script was:
```
/ # sh healthcheck.sh
PORT=8080
ADDRESS=
:8080
curl: (3) URL rejected: Malformed input to a URL function
```
So now `ADDRESS` is empty but we're still not defaulting to `localhost` as it should so my next idea was that the `ADDRESS=${ADDRESS:-localhost}` command is not being executed in time, or something along those lines makes sense to me. I'd like to hear a technical explanation from someone who knows better, to learn a bit more. Acting on that I added `&&` at the end of every PORT and ADDRESS. Final script to me looks like this:
```
#!/bin/sh
PORT=${FB_PORT:-$(jq .port /.filebrowser.json)}&&
ADDRESS=${FB_ADDRESS:-$(jq -r .address /.filebrowser.json)}&&
ADDRESS=${ADDRESS:-localhost}&&
#BEGIN DEBUG ECHOS
echo "PORT=$PORT"
echo "ADDRESS=$ADDRESS"
echo $ADDRESS:$PORT
#END DEBUG ECHOS
curl -f http://$ADDRESS:$PORT/health || exit 1
```
And its output:
```
/ # sh healthcheck.sh
: not found.sh: line 2:
: not found.sh: line 3:
: not found.sh: line 4:
PORT=8080
ADDRESS=localhost
localhost:8080
{"status":"OK"}/ #
```
So the script is working fine now... kinda since there are some minor errors. Of course this is not by far the most elegant solution but maybe can help resolve the issue or work as a temp solution for someone.

**Comment by CorySanin** [comment]
Ah, you're correct. The double quotes _are_ introduced by executing jq without the -r (--raw-output) flag. I didn't realize there was already logic in `healthcheck.sh` intended to fallback to "localhost".

Not sure why yours wasn't falling back to localhost though. Adding the -r flag is all I needed.

**Comment by Zulux91** [comment]
> Ah, you're correct. The double quotes _are_ introduced by executing jq without the -r (--raw-output) flag. I didn't realize there was already logic in `healthcheck.sh` intended to fallback to "localhost".
> 
> Not sure why yours wasn't falling back to localhost though. Adding the -r flag is all I needed.

Oh yes, you're right. Only -r is needed. Just tested on a fresh container and it works fine.

**Comment by Tuumke** [comment]
I don't understand what the fix is here. I have a default filebrowser installation and keeps giving me this healtcheck error too:

``` curl: (3) URL rejected: Bad hostname  ```

**Comment by Zulux91** [comment]
> I don't understand what the fix is here. I have a default filebrowser installation and keeps giving me this healtcheck error too:
> 
> `curl: (3) URL rejected: Bad hostname `

Were you able to inspect the pull request? That might make it clear. There's a healthcheck.sh script inside the container that needs to be changed to incorporate the mentioned -r parameter.

**Comment by Guiorgy** [comment]
> I don't understand what the fix is here. I have a default filebrowser installation and keeps giving me this healtcheck error too:
> 
> `curl: (3) URL rejected: Bad hostname `

1. Execute an interactive shell inside the container
    ```shell
    docker exec -it -u root [CONTAINER_NAME] ash
    ```
2. Install nano (or another editor of your choice):
    ```shell
    apk add --no-cache nano
    ```
3. Edit `healthcheck.sh`:
    ```shell
    nano healthcheck.sh
    ```
4. Add the `-r` or `--raw-output` flag to the jq command:
    Change `ADDRESS=${FB_ADDRESS:-$(jq .address /.filebrowser.json)}` to `ADDRESS=${FB_ADDRESS:-$(jq -r .address /.filebrowser.json)}`

**Comment by Tuumke** [comment]
> > I don't understand what the fix is here. I have a default filebrowser installation and keeps giving me this healtcheck error too:
> > `curl: (3) URL rejected: Bad hostname `
> 
>     1. Execute an interactive shell inside the container
>        ```shell
>        docker exec -it [CONTAINER_NAME] ash
>        ```
> 
>     2. Install nano (or another editor of your choice):
>        ```shell
>        apk add --no-cache nano
>        ```
> 
>     3. Edit `healthcheck.sh`:
>        ```shell
>        nano healthcheck.sh
>        ```
> 
>     4. Add the `-r` or `--raw-output` flag to the jq command:
>        Change `ADDRESS=${FB_ADDRESS:-$(jq .address /.filebrowser.json)}` to `ADDRESS=${FB_ADDRESS:-$(jq -r .address /.filebrowser.json)}`

Guess this wont work for me, as it repulls the image in portainer when i change my compose to run as root (otherwise i cant edit healtcheck). I need a new docker image build :-(

**Comment by Guiorgy** [comment]
@Tuumke You don't have to run the container as root. If you are using Portainer, you can execute a shell from the webui (select `/bin/ash`), and there you can specify the user, type `root` inside:

![image](https://github.com/filebrowser/filebrowser/assets/27736965/11be12a0-bb30-4d50-af96-818f8e95c6bd)
![image](https://github.com/filebrowser/filebrowser/assets/27736965/e5ee1c7d-cd56-4f77-afb9-68cf2f836fe0)

PS. Fixed my comment above

**Comment by Zulux91** [comment]
> Guess this wont work for me, as it repulls the image in portainer when i change my compose to run as root (otherwise i cant edit healtcheck). I need a new docker image build :-(

~~I fixed mine by doing a cat to the healthcheck (`docker exec -it filebrowser cat healthcheck.sh`) to get its content. Made a copy outside of the container since you have the /srv mounted to some place inside the machine, keeping the same name. Edited the script to add the -r flag and copied back the edited file, replacing the old one.~~

Here's a one line command as a temp fix:
```
docker exec -it [CONTAINER_NAME] sed -i 's/\(jq .address \/.filebrowser\.json\)/\1 -r/' healthcheck.sh
```

**Comment by mapxn** [comment]
Have the same issue.

<img width="649" alt="image" src="https://github.com/filebrowser/filebrowser/assets/16299874/64215af7-c368-4059-ba9b-28d31f0a1888">

**Comment by Guiorgy** [comment]
@mapxn and future readers, the problem has been identidied and fixed (see #3087), no need to spam report. Either wait for the next release, or use one of the optiones above to temporarily fix it yourself.

**Comment by seppeel** [comment]
> > Guess this wont work for me, as it repulls the image in portainer when i change my compose to run as root (otherwise i cant edit healtcheck). I need a new docker image build :-(
> 
> ~I fixed mine by doing a cat to the healthcheck (`docker exec -it filebrowser cat healthcheck.sh`) to get its content. Made a copy outside of the container since you have the /srv mounted to some place inside the machine, keeping the same name. Edited the script to add the -r flag and copied back the edited file, replacing the old one.~
> 
> Here's a one line command as a temp fix:
> 
> ```
> docker exec -it [CONTAINER_NAME] sed -i 's/\(jq .address \/.filebrowser\.json\)/\1 -r/' healthcheck.sh
> ```

Thanks for your workaround!

If your container does not run as root, just add "-u root".

```
docker exec -it -u root [CONTAINER_NAME] sed -i 's/\(jq .address \/.filebrowser\.json\)/\1 -r/' healthcheck.sh
```

**Comment by lustrant** [comment]
healthechk.sh shoudl be changed to:

`
#!/bin/sh
PORT=${FB_PORT:-$(jq -r .port /.filebrowser.json)}
ADDRESS=${FB_ADDRESS:-$(jq -r .address /.filebrowser.json)}
ADDRESS=${ADDRESS:-localhost}
curl -f http://$ADDRESS:$PORT/health || exit 1
`

-r needs to be added in order to give just the strings and not "strings", i.e. the address is
http://filebrowser:431/health
and not
http://"filebrowser":431/health

**Comment by Guiorgy** [comment]
@lustrant Already has been (see #3087)

**Comment by Tuumke** [comment]
But when can we see this fixed in the docker image? :O
Been a while now, surely this is pushed easy into a new image?

**Comment by CorySanin** [comment]
Needs to get merged first.

**Comment by jinks** [comment]
If fixing a typo that makes the default docker image unusable takes more than two weeks, that doesn't really instill confidence in the project.

**Comment by Guiorgy** [comment]
@jinks If you think you can do better, why don't you fork this project and maintain it better instead. Don't forget that this project is maintained by unpaid volunteers with their own lives, and no obligations to any of us.

**Comment by jinks** [comment]
@Guiorgy Because I don't care enough to maintain a project long-term.

The question remains, why pushing a 2-letter fix to Docker Hub remains such a chore. It's not even part of the core code. Unless there is something **seriously** wrong with the release process, I would imagine pushing the fix to Docker should be _less_ work than this thread has already consumed.

**Comment by Guiorgy** [comment]
@jinks As I said, they have their lives, maybe they have something more urgent going on. And it's not like the container is completely broken, or hard to manually workaround.

**Comment by ying001ch** [comment]
I'm running into this issue as well, and my workaround is to add an environment variable `FB_ADDRESS: 0.0.0.0` so that the command `jq .address /.filebrowser.json` doesn't work

**Comment by Guiorgy** [comment]
FYI, the fix has been merged (#3130), so just wait for the next release 😁

**Comment by pentago** [comment]
I just wonder, why is this internal healthcheck script needed at all?
Isn't that to be done optionally and controlled by the container runtime/orchestrator?

**Comment by Guiorgy** [comment]
@pentago AFAIK, if you aren't using any advanced orchestrator, such as Kubernetes, then this is the only way. Mine isn't a production server, moreover, it's just a RPI 3B+, an orchestrator is a total overkill. The same is probably true for most.
