### ISSUE TITLE
Multi Scope?

### ISSUE THREAD

**Issue by joebiwankenobi** [filebrowser/filebrowser#3097]
Hi..
How do I create "multi Scopes"?
I've se it so that when i add a new user.. it creates their Home Dir in /Users/
but i'd also like users to have access to another folder on the drive, this folder contains handy downloads.
I've fiddled with "scopes & Rules" but whrn i enable the folder in the "rules" this then allows users to see ALL user folders and i don't want that.
i just want them to be able to upload to their own home folder and have access to the "software" folder.

the only way i can see to make this work is to have a dedicated "software" login for users to get their downloads but that seems a bit daft to me.

##################################################
under global settings:
TICKED - Auto create user home dir while adidng new user
/Users/
##################################################
under User default settings
SCOPE
/Software/

when the above is applied - users can only access their Home folder and not /Software

Please Help

thank you in advance

Joe

**Comment by shivardev** [comment]
Need a solution for this please, I want to share multiple folders for a user

**Comment by opereztuta** [comment]
Sharing multiple directories with a user in FileBrowser requires consolidating those directories into a single accessible scope because FileBrowser doesn't natively support multiple scopes per user. Here's a general guideline on how to achieve this:

### **Method 1: Using Symbolic Links**

Symbolic links (symlinks) create references to directories located elsewhere on your file system within a single directory. This method allows users to access multiple directories through one root scope.

#### **Steps:**

1. **Create a Central Directory as User's Scope:**

   Choose or create a directory that will serve as the user's root scope in FileBrowser.

   ```bash
   mkdir /path/to/user_scope
   ```

2. **Create Symbolic Links to Each Target Directory:**

   For each directory you want the user to access, create a symbolic link inside the user's scope.

   ```bash
   ln -s /path/to/target_directory1 /path/to/user_scope/alias_name1
   ln -s /path/to/target_directory2 /path/to/user_scope/alias_name2
   # Repeat for additional directories
   ```

   - **`/path/to/target_directory`:** The actual path to the directory you want to share.
   - **`alias_name`:** The name you want to assign to the symlink as it appears to the user.

3. **Set Appropriate Permissions:**

   Ensure that the user running FileBrowser has the necessary permissions to access the target directories and the symbolic links.

   ```bash
   chown -R filebrowser_user:filebrowser_group /path/to/target_directory1
   chown -R filebrowser_user:filebrowser_group /path/to/target_directory2
   # Adjust permissions as needed
   ```

4. **Configure the User in FileBrowser:**

   - Log into the FileBrowser admin panel.
   - Navigate to **Users** and create or edit the user.
   - Set the **Scope** to `/path/to/user_scope`.
   - Adjust other settings (permissions, access rights) as required.

#### **Advantages:**

- **Flexibility:** Easily add or remove directories by modifying symlinks.
- **Simplicity:** No need for advanced configurations or system modifications.

#### **Considerations:**

- **Security:** Ensure symlinks don't expose unintended directories. Use absolute paths and manage permissions carefully.
- **Traversal:** Users might navigate to unintended areas if directory traversal isn't properly restricted.

---

### **Method 2: Using Bind Mounts**

Bind mounts map a directory to another location in the filesystem. This method is more secure than symlinks and prevents users from navigating outside the intended directories.

#### **Steps:**

1. **Create a Central Directory as User's Scope:**

   ```bash
   mkdir /path/to/user_scope
   ```

2. **Create Mount Points Inside the User Scope:**

   ```bash
   mkdir /path/to/user_scope/directory1
   mkdir /path/to/user_scope/directory2
   # Repeat for additional directories
   ```

3. **Mount the Target Directories Using Bind Mounts:**

   ```bash
   sudo mount --bind /path/to/target_directory1 /path/to/user_scope/directory1
   sudo mount --bind /path/to/target_directory2 /path/to/user_scope/directory2
   # Repeat for additional directories
   ```

   - To make these mounts persist after a reboot, add them to `/etc/fstab`:

     ```fstab
     /path/to/target_directory1 /path/to/user_scope/directory1 none bind 0 0
     /path/to/target_directory2 /path/to/user_scope/directory2 none bind 0 0
     ```

4. **Set Appropriate Permissions:**

   Ensure that the FileBrowser user has the necessary permissions for the bind-mounted directories.

   ```bash
   chown -R filebrowser_user:filebrowser_group /path/to/user_scope
   ```

5. **Configure the User in FileBrowser:**

   - In the FileBrowser admin panel, set the user's **Scope** to `/path/to/user_scope`.
   - Configure permissions as needed.

#### **Advantages:**

- **Security:** Users cannot navigate outside the bind-mounted directories.
- **Isolation:** Each bind mount is treated as a separate filesystem by FileBrowser.

#### **Considerations:**

- **Requires Root Access:** Setting up bind mounts requires administrative privileges.
- **System Configuration:** Modifying `/etc/fstab` should be done carefully to avoid boot issues.

---

### **Method 3: Adjusting Directory Structure**

If feasible, reorganize your directories so that all the directories you want to share are subdirectories of a common parent directory.

#### **Steps:**

1. **Create a Common Parent Directory:**

   ```bash
   mkdir /path/to/common_parent
   ```

2. **Move Target Directories Under the Common Parent:**

   ```bash
   mv /path/to/target_directory1 /path/to/common_parent/
   mv /path/to/target_directory2 /path/to/common_parent/
   # Adjust as necessary
   ```

3. **Set Appropriate Permissions:**

   ```bash
   chown -R filebrowser_user:filebrowser_group /path/to/common_parent
   ```

4. **Configure the User in FileBrowser:**

   - Set the user's **Scope** to `/path/to/common_parent`.
   - Adjust permissions and settings as needed.

#### **Advantages:**

- **Simplified Permissions:** Easier to manage permissions within a single directory hierarchy.
- **No Symlinks or Mounts Needed:** Reduces complexity.

#### **Considerations:**

- **Operational Impact:** Moving directories might affect applications or services relying on their original paths.
- **Feasibility:** Not always practical due to system constraints or organizational policies.

---

### **Important Security Measures**

- **Restrict User Navigation:**

  - Use FileBrowser's settings to prevent users from navigating above their root scope.
  - Enable the "No Parent" option to restrict access.

- **Permissions Management:**

  - Regularly audit permissions to ensure users have appropriate access.
  - Use Unix permissions and FileBrowser's user settings to enforce access controls.

- **Monitor Access:**

  - Enable logging in FileBrowser to monitor user activities.
  - Review logs periodically for any unauthorized access attempts.

---

### **Alternative Solutions**

- **Use Multiple User Accounts:**

  - If a single user cannot have multiple scopes, create separate accounts for each directory and share the login details (if appropriate).

- **Check for Updates or Plugins:**

  - Look for any FileBrowser updates or community plugins that may add multi-scope functionality.
  - Consider submitting a feature request to the developers.

---

### **Summary**

By consolidating the directories into a single scope using symbolic links or bind mounts, you can effectively share multiple directories with a user in FileBrowser. Each method has its advantages and considerations, so choose the one that best fits your environment and security requirements.

- **Symbolic Links:** Easiest to set up but requires careful permission management.
- **Bind Mounts:** More secure, prevents users from navigating outside intended directories.
- **Adjusting Directory Structure:** Simplifies permissions but may not be feasible in all cases.

---

### **References**

- **FileBrowser Documentation:** [filebrowser.org](https://filebrowser.org/features)
- **Symbolic Links Tutorial:** [Linux ln Command](https://www.gnu.org/software/coreutils/manual/html_node/ln-invocation.html)
- **Bind Mounts Guide:** [Mounting Subdirectories with Bind Mounts](https://www.kernel.org/doc/html/latest/filesystems/sharedsubtree.html)
