### ISSUE TITLE
Cant upload files when behind a nginx proxy

### ISSUE THREAD

**Issue by P-Y-R-O-B-O-T** [filebrowser/filebrowser#3136]
![image](https://github.com/filebrowser/filebrowser/assets/110553703/7055e168-c269-4fc4-b9b3-9240d91b4f42)

**Comment by gletiecq** [comment]
Have you looked at what the default limit on upload sizes are in your install of nginx?  By default it's only 1MB.  That's probably where the problem lies since a vanilla filebrowser install without an nginx proxy doesn't behave this way.  The limit is configured in /etc/nginx/nginx.conf using the configuration identifier "client_max_body_size" and if you set that to zero instead of the default 1m it will disable file upload size checking for you.

Filebrowser admins might want to consider adding some documentation about running filebrowser behind a reverse procy in apache and nginx and alerting users to potential issues like this, and others.  This is a fairly common situation.

**Comment by P-Y-R-O-B-O-T** [comment]
got the solution, changed the nginx limit of file buffer size, also I enabled the editing option for user, if the user do not have editing permission, user can't upload files

thanks
