### ISSUE TITLE
Extend Session Time for Large Uploads

### ISSUE THREAD

**Issue by usaboxer** [filebrowser/filebrowser#3150]
Filebrowser seems to timeout around two hours. When uploading a 20gib file over a slow connection it estimates 3-4 hours. It drops connection about halfway through. 

A simple input for this in the settings would be a great fix.

I cannot figure out how to make the adjustment manually. If there is an easy way that would be ok too!

![image](https://github.com/filebrowser/filebrowser/assets/167049426/3ef51369-d21c-44b4-b7bd-a0659b04b235)

**Comment by kloon15** [comment]
Its also quite annoying to have to log in every 2 hours.
While a changeable expiry date would indeed be a simple fix, the main issue with the current implementation is if the token gets leaked it can cause big problems if it has a long expiry.

**Comment by brianfromm** [comment]
This has been fixed in PR #5546, which is included in release v2.48.0 and later.

@usaboxer - You can now configure the session timeout. For existing installations:

```sh
filebrowser config set --tokenExpirationTime 6h
```

Then restart File Browser. For a 20GB upload over 3-4 hours, something like `6h` or `8h` should give you enough buffer.

@kloon15 - Good point about the security tradeoff. The default remains 2 hours for this reason. Users who need longer sessions for large uploads can increase it, but should be aware of the risk if tokens are leaked. There's no "remember me" or sliding expiration - it's a fixed duration from login.

See the [troubleshooting documentation](https://filebrowser.org/troubleshooting#session-timeout) for more details and configuration options.
