### ISSUE TITLE
baseURL can't contain double slash

### ISSUE THREAD

**Issue by tpimh** [filebrowser/filebrowser#3344]
**Description**
If `baseURL` is set to `https://example.com`, it's being transformed to `https:/example.com` which is causing problems. Changing `//` to `////` doesn't have any effect, any number of slashes is replaced with just a single slash.

**Expected behaviour**
`baseURL` should be set to the value exactly like it is in the config.

**What is happening instead?**
`baseURL` value is altered for some reason.

**Additional context**
When accessing the URL set as the baseURL with Firefox, the page never loads as static files are being requested from a wrong path. Other browsers untested.

**How to reproduce?**
I am using a Docker container with the `filebrowser/filebrowser` image and Caddy as reverse proxy with SSL. Just editing `.filebrowser.json` is enough to reproduce.

**Files**
`.filebrowser.json`: just change `baseURL` value.

**Comment by tpimh** [comment]
Can someone please take a look at this?

**Comment by WowSuchRicky** [comment]
@tpimh  baseurl is supposed to be a relative path, e.g. in your case, it would just be `"/"` (see https://github.com/filebrowser/filebrowser/blob/21783ed91a13ad52afdb411e43faf14fb6ef6e42/frontend/index.html#L93). However, I found your issue because _that_ doesn't seem to work either. Hopefully this still helps you though.
