### ISSUE TITLE
rsync truenas to omv nobody permissions

### ISSUE THREAD

**Issue by bobcaro** [filebrowser/filebrowser#3383]
Setup a rsync backup from truenas scale to open media vault works great. I did a sample sync to omv and i tried to delete the folder but i get a "require permission from OMV/nobody to delete files in this folder". How do I get permission?

**Comment by Silloky** [comment]
Hi, I'm pretty sure this issue is more related with OpenMediaVault setting permissions you don't want on synced folders.
Maybe try posting your problem there.

As I understand, this is just a temporary need, and not long term : you just need to delete that folder.
So what you can do, is use `sudo` : so `sudo rm -rf <pathtobackup>`.
I feel like I need to write this : *this command is irreversible and deletes everything in that path, so make sure the path you set is the one you want**.

> require permission from OMV/nobody to delete files in this folder

Means that the owner is `omv` and the group is `nobody`.
So your user is in the public permission ; OMV mustn't set write permissions for public.

For a long term solution, I would suggest looking into the `extra options` box in the rsync task settings in OMV.
This allows you to set up extra arguments for the rsync command : for example, as described [here](https://stackoverflow.com/a/11537337/18427893), you can define the destination permissions, such as read-write-execute for public, which is exactly what you want !
