### ISSUE TITLE
Voting: new name

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#343]
So, let's vote for a new name for File Manager, which must be also available as a GitHub organisation (ref.: #342). In the end of the month, the name with more thumbs up will be chosen.

Feel free to add more options. The template:

```
**Name:** [Insert Name]
**Slug:** [Insert Slug]
```

Don't forget the plugins for Caddy will keep their names: filemanager, hugo and jekyll.

**Comment by hacdias** [comment]
**Name:** File Browser
**Slug:** filebrowser

**Comment by hacdias** [comment]
_Placeholder_

**Comment by hacdias** [comment]
_Placeholder_

**Comment by hacdias** [comment]
_Placeholder_

**Comment by hacdias** [comment]
_Placeholder_

**Comment by hacdias** [comment]
_Placeholder_

**Comment by hacdias** [comment]
_Placeholder_

**Comment by hacdias** [comment]
_Placeholder_

**Comment by hacdias** [comment]
_Placeholder_

**Comment by malikpiara** [comment]
**Name:** Cloudify
**Slug:** cloudify

**Comment by malikpiara** [comment]
**Name:** Firefly
**Slug:** firefly

_Firefly, the decentralized file browser._

**Comment by arteta22000** [comment]
**Name:** filebrowser
**Slug:** filebrowser

**Comment by eine** [comment]
IMHO it'd be interesting to add "web" somewhere, since the main feature of the project is that it is a web-based file manager/browser: https://en.wikipedia.org/wiki/File_manager

**Name**: Web File Manager
**slug**: wfm

Related to #342, possible repos:

- wfm/front-vue
- wfm/front-angularjs
- wfm/back-go
- wfm/back-ipfs

[wfm](https://github.com/wfm) is not available ATM, but it seems to be a profile with very very little public activity. Shall you like the proposal, it might be worth mentioning him to politely ask if he would change his name to wfmurphy or any other, so that the organization can be created. If contacting him is not possible, GitHub staff can check it according to https://help.github.com/articles/name-squatting-policy/

Otherwise, I'd just propose **web-file-manager**.

**Comment by Equim-chan** [comment]
@malikpiara the name [firefly](https://github.com/firefly) and [cloudify](https://github.com/cloudify) are already occupied.

**Comment by Equim-chan** [comment]
@hacdias Let's move on?

**Comment by hacdias** [comment]
@Equim-chan yeah, it's 7am here and I'm going to catch a train, but I will start the process of moving today hopefully. Although I won't be in Portugal in the next couple of days so I'm not sure if I can finish this.

We also have to define how are we going to split everything because this is not *that* simple as just moving a repository. Yes, initially, and I can do that just now, we will be moving a repository. Although, the goal is to split the front-end from the back-end and even split it in some more packages 😄 

I'll get back to this later today 😄

**Comment by Equim-chan** [comment]
I see the changes are on going right now. Just a suggestion that can we change the title of https://github.com/filebrowser/vue? Maybe filebrowser/frontend or something.
