### ISSUE TITLE
User Management "Download file" rights suggestion

### ISSUE THREAD

**Issue by UnAfraid** [filebrowser/filebrowser#350]
Hello,

Can new permission flag be added to limit downloading of files, for scenarios that you want multiple users to be able to share same account just to upload files, but not download the files.

Thanks!

**Comment by eine** [comment]
@UnAfraid, if a user can upload a file, it means that there is write access. Therefore, the content can be browsed/seen. In this context, disabling the download button seems irrelevant, because you can always save the content you are able to see.

Please, provide some more info about the context:

- Are you suggesting to let a user upload files to a dir/scope but not be able to open the uploaded files afterwards?
- Should they be able to list the content but not to open it?
- How would possible conflicts be managed (i.e. uploading a file that already exists) if the content cannot be checked?

**Comment by UnAfraid** [comment]
@1138-4EB thanks for the reply.

I have this done with ftp, i have limited users to be able to upload files, not able to overwrite existing, not able to read even what they've uploaded.
Its a global upload directory that we use to receive files from clients that we must check, therefore we don't want other clients to be able to download content of this folder.

>Are you suggesting to let a user upload files to a dir/scope but not be able to open the uploaded files afterwards?
* Yes
>Should they be able to list the content but not to open it?
* Yes
>How would possible conflicts be managed (i.e. uploading a file that already exists) if the content cannot be checked?
* Either auto-rename or deny the upload

**Comment by hacdias** [comment]
Hello! Will be available on v2.0! I'm closing this to remove the clutter in the meanwhile. For more info, check #574 and #575!
