### ISSUE TITLE
File download via wget

### ISSUE THREAD

**Issue by aoceano** [filebrowser/filebrowser#362]
It is possible download a file via wget command passing user and password as argument?

For example, I want to download a file named "myfile.zip", placed in root. I would like to execute the following command to download the file via command line: 
wget --use=MYUSER --password=MYPASSWORD http://mydomain.com/api/myfile.zip.

Is this possible?

Best regards

AS

**Comment by Equim-chan** [comment]
filebrowser is using jwt instead of basicauth by default. If you intend to download and authorize with basicauth, try to set `noauth` in filebrowser and set corresponding basicauth middleware on the downstream.

Accepting jwt and basicauth at the same time may be tricky on the current implementation.

**Comment by la0wei** [comment]
@Equim-chan 
Seems related to 2 things.
1.authorization
2.path

**Comment by Equim-chan** [comment]
@la0wei Path is `/api/download/{related file path to scope}`. For example, with scope `/srv`, to download a file `/srv/test/100M.bin`, GET `/api/download/test/100M.bin`.

**Comment by hacdias** [comment]
Since we use JWT you cannot do that. You'd need to exchange your username and password with the server to obtain a JWT token and then use it to authenticate any other requests.

What you can do is use the share feature to obtain a permalink for a certain resource. Then you can just wget/curl it.

I'll close this issue as we already answered the question.

**Comment by cnlydia** [comment]
How can i get the api of generate jwt token? 

I can't  find it . :(

**Comment by tonglv** [comment]
> 

$ wget --user admin --password admin@1018 http://xx.xx.xx.xx:8018/api/raw/software/jdk-11.0.16.1_linux-x64_bin.tar.gz
--2022-11-02 09:28:31-- http://xx.xx.xx.xx:8018/api/raw/software/jdk-11.0.16.1_linux-x64_bin.tar.gz
Connecting to xx.xx.xx.xx:8018… connected.
HTTP request sent, awaiting response… 401 Unauthorized
Unknown authentication scheme.
Authorization failed.

failed!

**Comment by ramiresviana** [comment]
> > 
> 
> $ wget --user admin --password admin@1018 http://xx.xx.xx.xx:8018/api/raw/software/jdk-11.0.16.1_linux-x64_bin.tar.gz --2022-11-02 09:28:31-- http://xx.xx.xx.xx:8018/api/raw/software/jdk-11.0.16.1_linux-x64_bin.tar.gz Connecting to xx.xx.xx.xx:8018… connected. HTTP request sent, awaiting response… 401 Unauthorized Unknown authentication scheme. Authorization failed.
> 
> failed!

The user and password parameters from `wget` are used for the Basic authentication method, which is not supported by Filebrowser.

**Comment by dltkr77** [comment]
I also found this method while searching, so even though it's a closed issue, I'll leave a comment.

1. Get JWT token
```
export TOKEN=$(curl -s -X POST \
-H "Content-Type: application/json" \
-d '{
"username": "<id>",
"password": "<password>"
}' \
https://<host>/api/login)
```

2. Download file
```
curl -L \
-H "X-Auth: $TOKEN" \
"https://<host>/api/raw/<file_path>" -o <path_to_download>
```
