### ISSUE TITLE
Default directory perm 0666 problem

### ISSUE THREAD

**Issue by march1993** [filebrowser/filebrowser#387]
https://github.com/filebrowser/filebrowser/blob/281339337d007dc884c49e4f877e2f53e09dffd7/http/users.go#L216

Filebrowser panics with 0666 under non-root privilege. Won't it be 0755 or 0700?

**Comment by march1993** [comment]
Also in the file resource.go, there are two '0776' permissions for files.  Won't it be 0644 or 0600?

**Comment by hacdias** [comment]
Since I'm not an avid unix user, I'm unsure what the default permissions should be. This can be easily changed though. @1138-4EB thoughts?

**Comment by Equim-chan** [comment]
#300?

**Comment by eine** [comment]
@hacdias, unfortunately I am also unsure about what the default should be. Nonetheless, this issue seems to be outdated. The `0776` in `resource.go` that @march1993 mentioned are now set to `0775` (see #441).

We might want to close this issue and continue the discussion in #300, as both seem to be tightly related.

**Comment by hacdias** [comment]
@Equim-chan related issues, yes! We can update the code to use other file permissions. What do you think it's best?

**Comment by hacdias** [comment]
@1138-4EB yes, let's do that!
