### ISSUE TITLE
①是否可以加入传输列表？因为现在上传大文件时，如果刷新页面容易传输中断。

### ISSUE THREAD

**Issue by changdapu** [filebrowser/filebrowser#407]
你好，您开发的这个软件使用很流畅，体验效果很棒，我有几个小小的请求建议，望采纳；

①是否可以加入文件传输列表？因为现在上传大文件过程中，如果刷新页面会导致传输中断
②是否可以增加一个磁盘空间展示？
③是否可以增加自定义展示的目录设置，防止过多的展示系统文件夹，而导致系统文件误删改。
④是否可以提供单击鼠标，打开文件夹的操作选项？
⑤如果能提供在线解压zip等压缩文件，和在线浏览office文档，我认为就更完美了。
⑥自定义主题样式的功能应该很棒，可是我还不知道怎么用，我想应该有一些文字说明下。

感谢！

**Comment by hacdias** [comment]
Hello @changdapu,

I used the translator so I can understand what you said. I hope I an give you the right answers:

1. Didn't understand correctly. You can upload the files in one tab and work on another to avoid errors while uploading.
2. Do you want to display the available space in disk?
3. You can use rules to allow/disallow the access to certain directories. Or you can set a more restricted *scope*. I'd go for the last.
4. How so? Like the right click on Windows?
5. Could you try to explain it in another way?
6. We can add some more documentation about how to customize the theme.

**Comment by Equim-chan** [comment]
I can translate. @hacdias 

1. Can we add a list of transmissions? Because if the page is refresh, the progress of uploading of some large files will be interrupted.
1. Can we add a display of disk quota?
1. Can we make a filter applied for the files/folders to list? This is to prevent too many system files/folders to be shown and possible misoperation of delete/modify.
1. Can we add an option that allows open a folder with just one click?
1. If it supports unzip or view MS office files online, it can be more perfect.
1. Custom themes feature looks great, but I don't know how to use. I think there should be some instructions.

**Comment by eine** [comment]
1. Please open a separate issue.
2. Please open a separate issue.
3. Yes. See https://github.com/filebrowser/filebrowser/issues/472#issuecomment-408590576.
4. See #419.
5. Please open a separate issue.
6. See #208. Also, add a separate issue to suggest adding instructions.
