### ISSUE TITLE
Case Insensitive & Fuzzy Search 

### ISSUE THREAD

**Issue by collegeimprovements** [filebrowser/filebrowser#415]
Would it be possible to make search `case:insensitive` by default or via some config option ?
And would it be possible to have fuzzy search ?

**Comment by bkanuka** [comment]
I opened issue #336 which, if implemented, would allow this and other search customization. Unfortunately I gave it my best shot and couldn't get it.

**Comment by DeyV** [comment]
I suggest  change default behavior. Everyone use google and other search tools, and most of them is case insensitive. It is especially important in file search, when nobody think about letters size (excluding programmers)

**Comment by 1138-4EB** [comment]
Since case insensitive search is implemented already, I suggest we take one of these paths:

- Change the title of this issue to "Fuzzy Search" and use it to track that.
- Close this issue and open a new one for Fuzzy Search.
- Close this issue and add a comment about Fuzzy Search in #336.

@collegeimprovements, it is up to you.
