### ISSUE TITLE
Is SSL supported?

### ISSUE THREAD

**Issue by respi02** [filebrowser/filebrowser#431]
Is currently SSL eg. https supported in filebrowser? If not, can you do it? :D I do not see this option in config and when i try to view with valid https certificate on my VPS server, got this

Website (my domain) returned an invalid response.
ERR_SSL_PROTOCOL_ERROR

**Comment by hacdias** [comment]
To use SSL with File Browser, it would be better to proxy to it via a web server like Caddy or Nginx. That way it is simpler.

I would advise you to use Caddy since it gives you automatically generated and free SSL certificates (through Let's Encrypt) and has an [extension just for File Browser](https://caddyserver.com/docs/http.filemanager).

**Comment by gahmasec** [comment]
In case someone still needs it to use filebrowser with SSL just create a SSL certificate and through the following commands configure correctly:

`sudo filebrowser config set -k home/user/ssl/server.key (PATH of TLS Key file)`
`sudo filebrowser config set --cert home/user/ssl/example.com.crt (PATH of TLS Cert file)`

**Comment by tilusnet** [comment]
My docker image gets `0 curl: (22) The requested URL returned error: 400` with 

```
    filebrowser/filebrowser \
    --cert cert.crt \
    --key cert.key 
```

Not sure why, any hints guys?
