### ISSUE TITLE
Admin password

### ISSUE THREAD

**Issue by ncresswell** [filebrowser/filebrowser#435]
Hi there, is there any way to set the admin password when starting filebrowser under Docker?

You already support "--other-flag other-value" but can that be used as "--adminpassword Letmein" for example?

You only list  --port 80, --database /database.db, --scope /srv as flags in the documentation, but is there a complete list of all supported flags?

**Comment by juan11perez** [comment]
same question. basically we're looking for a persistent password. Is there a way to do it via the config.json file?

**Comment by eine** [comment]
Might this be closed in favour of #257?

**Comment by juan11perez** [comment]
@1138-4EB thank you. any methodology that allows a persistent password. 
a password file would be good.

**Comment by eine** [comment]
@juan11perez, I think that the main issue here is not to save the password raw. Although it is not relevant for "home users", it seems that some users are expecting to use filebrowser as part of a (probably paid) service for third parties. Therefore, we should be careful about how we implement it so that we don't introduce a false feeling of security. Alternatively, a naive implementation is possible, but we should clearly state that it is not save for production.

Personally, I think that we should set `--no-auth` by default until we can ensure a save approach. Doing so would require a testsuite to evaluate it.

**Comment by juan11perez** [comment]
@1138-4EB thank you. apologies if I oversimplified. Just commenting from a user perspective as frankly cant add much in the way of process. 

As it stands, it's open. So some (initial) solution is progress.

I tried blocking it with nginx password feature, but strangely enough it only works on Safari browsers. Meaning, when the dialog box pops up on chrome, firefox, etc and I type the user and password it effectively ignores it and keeps asking for it. Not the case with Safari. Works as intended.

**Comment by eine** [comment]
@juan11perez, there is no need to apologise at all. Your proposal is reasonable. I just wanted to point out the difference between doing something "less unsecure" or doing it "really secure".

Unfortunately, @hacdias must be busy with his uni exams. Let's wait until he can sit down and think about this.

Meanwhile, it'd be useful if you could partially document your approach in the referred issue. I think that offloading credential management to an external layer (reverse proxy) is a valid workaround and it can help to keep filebrowser simple. But I am not sure about the implications that such a solution would have in granularity.

Anyway, if you want a solution, even though it might be not ideal, you can check https://github.com/filebrowser/filebrowser/issues/257#issuecomment-397765726 There is an existing proposal that uses environment variables.

**Comment by hacdias** [comment]
Hello! Will be available on v2.0! I'm closing this to remove the clutter in the meanwhile. For more info, check #574 and #575!
