### ISSUE TITLE
Compile a mipsel version

### ISSUE THREAD

**Issue by ifengchao** [filebrowser/filebrowser#447]
How to compile a mipsel verison for openwrt routers ?
Anyone tried this?
Appreciated.

**Comment by hacdias** [comment]
Hey @ifengchao! I haven't added mips and misple versions to automatic releases because I've had some compiling issues in the past in the most recent versions. You can take a look at [Go's docs](https://github.com/golang/go/wiki/WindowsCrossCompiling) to see how to cross compile. Basically you just have to set the env variable for the platform and architecture and then compile as you'd normally do.

**Comment by ifengchao** [comment]
@hacdias Thanks you for your advice.

**Comment by eine** [comment]
@ifengchao any feedback about this? Should we keep the issue open?
