### ISSUE TITLE
Different (optional) (Hugo) website root for each user account

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#448]
### 3. What are you trying to do?

Per user website root for Hugo. Optionally setting the users scope as the website root -
per user account rather than (only) globally. Basically having the option to allow multiple
users each edit their own Hugo sites, or in the case of multi-sites (e.g. i18n) having
multiple users work on different instances of the same site. E.g. example.co.uk, example.cn,
example.jp

### 4. What did you expect to see?

Either an option to set a specific website root per user account - or an option to call the
users scope as the website root. 

### 5. What did you see instead (give full error messages and/or log)?

Nothing unexpected. Just doesn't work unless the global website root points to a working
Hugo directory - meaning all users can only work on the same Hugo site. 
Unless I missed something despite checking the documentation and the issues / questions list.

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

By trying the same as above.

**Comment by ghost** [comment]
Addition 1:

And the option to manually set the preview path e.g.

https://filemanagerhomeurl.com/username/preview/

Addition 2:

The option to turn off Preview on a per-user basis

**Comment by ghost** [comment]
I do understand that running separate instances also solves this problem, but it would be nice to just have to run and monitor one instance.

I did find a bug however:

running instance for example.com

instance is started at hugo website root.

create extra user with scope ./content

if user does hugo new - the file gets created, but file browser automatically tries
to navigate to /content/newfile.md - which isn't possible for the new user as content
is their scope. 

I reckon a 'if scope includes ./content then directly open the file'  or go to sub directory within ./content and open file - should be added.

**Comment by gocpp** [comment]
Closing issue as it is clearly not being read or being taken seriously. Toodlepip File Browser.

**Comment by eine** [comment]
Hi @gocpp , I'm glad to see that you reconsidered it and decided to reopen this issue. I'm replying to let you know that it is being read and that it is being taken as seriously as many other open issues in the project. However, as you may know, this project was started some years ago by a quite young student who started uni recently. No one is being paid to develop it and no one has enough free time to reply in three (weekend) days. Then, we need to be considerate with each other.

On my part, I'm trying my best to reorganize the content after the migration to a GitHub organization, in order to make it easier for new users to contribute (see filebrowser/community#1, #399 and #450). Hope it helps get some (wo)manpower involved in it!

Regretfully, both my expertise and my main interest (#302) in this project are quite far from this specific issue. I use Hugo intensively for offline site generation, but not as a server itself; and I don't have a clear picture of how it should be handled in the context of File Browser (#310).

So, could please help me and any possible contributor to better understand your use case by providing reproducible steps to reach the limitations you found? E.g. by providing either the configuration files or the arguments you use to run filebrowser.

About your second issue/bug, if I don't get it wrong you expect scopes to be recursive but they are not. Is it? If so, could you please open a new issue just asking that? I think that it might be easier to tackle it.

**Comment by ghost** [comment]
Hi @1138-4EB, - thank you for your reply, much appreciated.

I will look into contributing although it will require me to pick up Go as a language (until now I have done most of my developing in C and C++), but I agree this project deserves more manpower.

As for the first issue - I did not mean using Hugo as the server, but using File Browser as a service for multiple users to work on multiple Hugo sites. At the moment one instance of File Browser can only define one Hugo website root - meaning all users can only work on the same site. My request was if a configuration option could be added where an administrator can specify a website root for each user individually - that can't be much of a problem I'm sure. So there aren't any configuration files, errors etc to supply in this case as its default behaviour of File Browser as it stands at the moment, not an error.

The second issue is about how File Browser handles opening a new document after it is created by Hugo; for example:

Administrator adds a 2nd user - with scope ./content within the website root.
When the 2nd user then clicks "Hugo New" (make a new entry / post) the default behaviour of File Browser is then to automatically open the file - which it does by opening /websiteroot/content/newfile.
As the 2nd user however is limited to content in the first place, from his / her session it would be 
/content/newfile. Thus the file doesn't open and results in an error. The user can then of course navigate back to their home directory and open the file anyway, but said error would create confusion and / frustration for users limited to the content section. In other words, limiting the scope of secondary users to the content section (so they can't accidentally edit / delete other files crucial to the Hugo project) means that creating new documents will always lead to an error first before they can manually navigate to the file and open it for editing. 
Thus I suggested that an "if content is included in the scope of users session then remove website root from the file path prior to opening the file".

Perhaps I should indeed open a new issue for the second point.

**Comment by eine** [comment]
> (until now I have done most of my developing in C and C++)

Then, I'm sure you'll pick the syntax very easily. It is so close to C. Not so much to C++. You can have a look at this preliminary version of the docs I wrote this weekend to welcome new contributors: https://github.com/1138-4EB/filebrowser-community/blob/patch-1/contributing.md If you want to go fast, just glance over https://tour.golang.org/ and then find your own way at https://github.com/golang/go/wiki/Learn This might also be interesting to you: http://crypto.stanford.edu/~blynn/c2go/

Of course, let us know about the issues you might find while getting contact with either golang or Vue.js, as that will help us improve the docs.

> Perhaps I should indeed open a new issue for the second point.

Yes, please. Just cut it from here and paste it in a new thread. I always use filebrowser in `--no-auth` mode with a single user. But I'll definitely give it a try.

**Comment by ghost** [comment]
Hi @1138-4EB - Thanks for all the information, I'll look into Go for sure, perhaps it will come in handy for some other projects as well as contributing to this one. As for Vue.js - I'm a total noob when it comes to working with JavaScript frameworks (only do some minimal vanilla javascript from time to time), so that will probably take me more time to pick up.

Pasted the 2nd problem into a new issue.
