### ISSUE TITLE
Wildcards in command arguments are not handled/expanded properly

### ISSUE THREAD

**Issue by chinglinwen** [filebrowser/filebrowser#466]
1. download from release page
2. no caddy

### 3. What are you trying to do?
gofmt after save

### 4. What did you expect to see?
success format the file

### 5. What did you see instead (give full error messages and/or log)?
internal server error

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

config global setting, add command ```gofmt -w *.go```, and try edit a go file and click save.

version: filebrowser version 1.9.0
os: CentOS Linux release 7.3.1611 (Core)

**Comment by eine** [comment]
If I don't get it wrong, you are trying to:

1. Execute filebrowser from a release binary.
2. Access filebrowser frontend in a browser.
3. Open a file in filebrowser.
4. Edit the file and save it.
5. Execute `gofmt -w *.go` in the 'Search box' of filebrowser, in order to have the edited file formatted.

If so, you should:

- Enable command `gofmt` in the config, not `gofmt -w *.go`.
- Then, write `$gofmt -w *.go` in the search box in order to execute it after you edited the file.

Please, let us know if this solves your issue. Should I misunderstood it, please reword the issue.

@hacdias, I think that commands composed of multiple words are not supported, so this might be the underlying issue that produces the 'internal server error'. Can you confirm it? If so, do we want to add support for it? I.e., do we want to allow enabling the usage of a subset of the options available for a executable?

**Comment by hacdias** [comment]
On Settings you should just add a one word command. But it is also unclear if @chinglinwen is using hooks (after save hook) or typing the command after saving.

**Comment by chinglinwen** [comment]
@1138-4EB I tried by typing command on the searchbox, it doesn't work, though this also not my expectation way of format the go file. ( expect just click, and it automatic format it )

```
$gofmt -w /home/wen/tt/wen/svc-check/*.go
stat wen/svc-check/*.go: no such file or directory

$gofmt -w /home/wen/tt/wen/svc-check/*.go
stat /home/wen/tt/wen/svc-check/*.go: no such file or directory
```

@hacdias I just click save, with after save setting to `gofmt -w *.go`, you said it should be one word in the setting of after save, I tried quote it, it's not working ( internal server error )

I also encounter some strange problem, why the two go file behaviors different, one can edit, and another can not ( just show download picture )

```
[wen@pcmaster t]$ stat ../exec/timer.go
  File: ‘../exec/timer.go’
  Size: 1296      	Blocks: 8          IO Block: 4096   regular file
Device: fd02h/64770d	Inode: 15213753    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/     wen)   Gid: ( 1000/     wen)
Access: 2018-07-27 15:33:55.068443590 +0800
Modify: 2018-05-09 18:35:15.259821755 +0800
Change: 2018-05-09 18:35:15.299821975 +0800
 Birth: -
[wen@pcmaster wen]$ stat hello/main.go
  File: ‘hello/main.go’
  Size: 74        	Blocks: 8          IO Block: 4096   regular file
Device: fd02h/64770d	Inode: 16483834    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/     wen)   Gid: ( 1000/     wen)
Access: 2018-07-27 15:36:15.631005375 +0800
Modify: 2018-07-27 15:36:12.611993311 +0800
Change: 2018-07-27 15:36:12.611993311 +0800
 Birth: -
[wen@pcmaster wen]
```
> main.go is newly created by vim on the system.

**Comment by eine** [comment]
I can reproduce it. `$gofmt -w *.go` in the search box fails because `*.go` is not handled properly. Indeed, the internal server error is related to this:

```
2018/07/29 19:46:37 [INFO] Blocking Command:"gofmt -w *.txt"
stat *.txt: no such file or directory
2018/07/29 19:46:37 /main.txt: 500 Internal Server Error
2018/07/29 19:46:37 exit status 2
```

@hacdias, should [`fielpath.Glob(pattern string)`](https://golang.org/pkg/path/filepath/#Glob) be used?

I can also reproduce the limitation to edit the content of a `.go` file. This is a know issue. See filebrowser/filebrowser#358.

**Comment by hacdias** [comment]
@1138-4EB instead of using filepath.Glob, we could do something like this:

```
exec.Command("/bin/sh", "-c", "mv ./source_dir/* ./dest_dir")
```

That way, we're invoking the shell and then it will take care of globs and everything else. Although, we need to know in which platform we are to do so. We can check if there is an `sh` path or `bash` and on Windows PowerShell or just keep it running directly.

**Comment by hacdias** [comment]
Since you can now choose to use a shell for your commands, I'm closing this. Change that option on:

Settings -> Global Settings -> Execute on Shell

It will allow the commands to be run on your preferred shell, which should handle the expansion.
