### ISSUE TITLE
Custom upload view/template - query

### ISSUE THREAD

**Issue by danryu** [filebrowser/filebrowser#469]
I'm integrating filemanager with my web service and it's working beautifully.

However, I want to add a custom function, ie to have a custom upload form which I can open in a modal on my website portal. Basically I want to have the "upload button" with the filemanager at a specific directory in the filesystem, to upload to a pre-determined location each time - and that's it, with none of the rest of the usual interface.
I wanted to dive in and hack a template or two, and then I discovered that it's all Go/Rice/Hugo/VueJS funkiness - and I don't have a clue where to start as I'm not familiar with any of the above stack....

Can anybody give me any tips as to where to start?

**Comment by hacdias** [comment]
Right now it's not possible to add custom functions. If you want to create a form to upload to File Browser, you should exchange your auth data  with `/api/login` to retrieve a JWT token and then use it to POST to `/api/files/Your/path` with the files on the request body.

I'd suggest you to use File Browser directly.

I'm also closing this since it didn't get feedback in the last months.
