### ISSUE TITLE
Support SSO through HTTP Headers

### ISSUE THREAD

**Issue by maweck** [filebrowser/filebrowser#471]
Hello together and thank you for providing this great project.

we are planning to use "filebrowser" internally, but sadly miss some features. The first one is SSO. All our tools are running behind a proxy which handles the authentication and authorization. If the user is allowed to access the tool, the proxy sets the "X-Forwarded-User" header (and some additional ones). The tools are looking for this header and fully trust its value if found - Meaning that if the header is provided, the user will automatically be logged in.

I already did a quick and dirty POC with "filebrowser" and from my current point of view it could be implemented quite easily. My first questions would be: 
- Is this feature also interesting for the filebrowser project?
- Are there things we would need to take care of right now when we would implement this?

Thank you and best regards

**Comment by eine** [comment]
If I don't get it wrong, what you are suggesting would be potentially dangerous as it should only be used through a properly configured proxy. If not, any user providing any `X-Forwarded-User` will have access. Am I wrong?

Nevertheless, I think that this is an interesting feature. Should you be willing to contribute a PR to implement this, I suggest to please:

- Be explicit about the risk in the codebase.
- Make it default to be disabled.
- Add a message/log when filebrowser starts in this mode.
- Consider adding an example configuration for a proxy such as NGINX or Traefik (or the one you are actually using).

Should it be possible to use any mechanism that allows filebrowser to check whether it is being executed behind a (known) proxy, that'd be great. But I don't think this is compulsory.

**Comment by maweck** [comment]
Hay @1138-4EB , 

> If I don't get it wrong, what you are suggesting would be potentially dangerous [..] If not, any user providing any X-Forwarded-User will have access

Yes, if e.g. the proxy is not correctly configured or if the proxy can be bypassed. So I am more than fine with adding a warning about that feature.

> Should you be willing to contribute a PR to implement this

That would be the plan :) My question here would be: How do you want the options to look like? Should I create a new option "proxy-auth" in parallel to "no-auth" or should there be something like "auth" that can be set to:
- no-auth
- proxy-auth
- ... maybe more to come?

> Be explicit about the risk in the codebase.
Make it default to be disabled.
Add a message/log when filebrowser starts in this mode.

Fine with those :)

> Consider adding an example configuration for a proxy such as NGINX or Traefik (or the one you are actually using).

Hm, the setup is often not possible or quite complex with common proxy projects out of the box (see e.g. https://serverfault.com/questions/537425/ldap-auth-proxy-adding-headers-according-to-ldap-groups ). I would say that it is not the best idea to simply provide snippets that can be copy & pasted by people who do not know what they are doing. Would it be fine for you to simply describe the idea/concept behind this feature and do a PR for: https://github.com/filebrowser/filebrowser.github.io after the feature is available ? 

Thanks and best regards

**Comment by eine** [comment]
> That would be the plan :) My question here would be: How do you want the options to look like? Should I create a new option "proxy-auth" in parallel to "no-auth" or should there be something like "auth...

Are these options mutually exclusive? `no-auth` is exclusive for sure, so I think we should keep it as a separate flag. Then, `auth` (which enables multi-user support) should have two possible values: `default` (current implementation) or `proxy`.

However, should `default` and `proxy` be compatible (i.e. requests coming from a known proxy are accepted but any other requires a password), then `auth` should not exists and `proxy` should be added only. In this case, if `no-auth` and `proxy` are enabled at the same time, `proxy` would act as frontend to provide access to a single common instance to multiple users.

Anyway, let's hear what @hacdias and @Equim-chan think about this.

> I would say that it is not the best idea to simply provide snippets that can be copy & pasted by people who do not know what they are doing.

Sure. I agree. I think that the best solution is to provide enough info so that a user that has already set up a proxy with access to a LDAP database (or any other source of credentials) finds just the additional references and snippets required to extend it to use filebrowser. This is why I mentioned a couple of common proxies. A new user with less experience will have to read the basic and intermediate references we would provide. I.e., it is perfectly ok to link to the NGINX manual and a few Stack Exchange Q&As.

> Would it be fine for you to simply describe the idea/concept behind this feature and do a PR for: filebrowser/filebrowser.github.io after the feature is available ?

It is perfectly ok. Indeed, this issue and the comment in the PR are enough to explain the idea/concept. Then, adding a slightly longer and more specific explanation can be done either in [filebrowser.github.io](https://filebrowser.github.io) or in [filebrowser/community](https://github.com/filebrowser/community). I.e., the modifications in the options/flags should be changed in [filebrowser.github.io](https://filebrowser.github.io). But references and comments about the risks and suggestions for users implementing it can be provided in the community repo (see https://github.com/filebrowser/community/pull/1/files). In the end, the sources of both repos are markdown, so it is easy to reorganize the content once it is written.

> Thanks and best regards

Thanks to you! Please, let us know if you need any further information about how to build/test the app.

**Comment by hacdias** [comment]
@maweck I'm making some changes to the internals and have got a question for you: is it possible for SSO to login via a proxy and then let the 'Authorization' header pass around with the jwt token?

I'm creating an interface for authenticators, they receive an http.Request and return an user and an error. The internals of each authenticator don't care for the request itself: it can be via a proxy, or via json, or just bypassing (with authorization none). And then, after the user is authenticated, I plan to keep the jwt token so the app knows the user is still logged in. Is it possible on your system?
