### ISSUE TITLE
Check for updates and automatically download/replace

### ISSUE THREAD

**Issue by yurividal** [filebrowser/filebrowser#475]
It would be nice to have a button to check for update releases of file filebrowser.  Perhaps a message saying a new version is available, or even a button to automatically download and replace the previous version.

**Comment by hugomassing** [comment]
I'm currently searching a way to update only filebrowser with caddy? Is there a way to update without installing caddy again?

**Comment by eine** [comment]
@hugomassing, caddy includes all the plugins at build time (see https://github.com/filebrowser/filebrowser/pull/399#issuecomment-407251536). I.e. the codebase of the plugins is embedded in caddy, because all of them are built together. Therefore, AFAIK the is no way to update only filebrowser, you need to rebuilt caddy. However, I think that each release is pushed to GitHub releases and Caddy builder at the same time, so if you update Caddy regurlarly you should get the latest version. Might we know a little more about the context? 

@yurividal [mviereck/x11docker/blob/master/#L1018-L1147](https://github.com/mviereck/x11docker/blob/master/x11docker#L1018-L1147) does this with a bash script. We can take it as a reference. Let's write a list of desired features:

- [ ] In the frontend, check either GitHub releases or Docker Hub periodically and show a message if a new version is found. When automatic update is supported, add a button to the message.
  - Make it optional and let the user configure the frequency.
- [ ] Make filebrowser aware of the context: standalone, in a container or as a caddy plugin.
- [ ] Function and handler (API) to:
  - Retrieve a specific version or the latest from GitHub.
  - Stop filebrowser, remove it and start the retrieved version with the same config file and options.
  - If a docker image is being used, and if the requested version is available as a docker image, remove the container, retrieve the new one and start it with the same options.
  - If filebrowser is being used as a caddy plugin, either:
    - Disable this feature.
    - Suggest updating caddy.
- [ ] Add a button to the frontend (probably in the settings) to send a request. This should contain the desired target version.
  - Currently, if `no-auth` is used, settings are not available. This should be changed, in order to support the automatic update.

The first task should be quite straightforward. Automatically updating filebrowser standalone might require a bit of work. The docker option seems tricky.

**Comment by VLEFF** [comment]
I have installed it with https://filebrowser.github.io/get.sh, how can I update filebrowser for the moment?

**Comment by eine** [comment]
@VLEFF running the script again should overwrite it with the latest version from https://github.com/filebrowser/filebrowser/releases/latest.

Alternatively, the binary should be located in `/usr/local/bin`. So you can just replace it manually. Download the tarball for your arch from the link above, extract it and copy/move the file named `filebrowser`.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
