### ISSUE TITLE
Setup 'After upload' command

### ISSUE THREAD

**Issue by hugomassing** [filebrowser/filebrowser#483]
**Description**
I have a server error everytime I upload something even with a command like "git status"

**Expected behaviour**
No error

**What is happening instead?**
Error 500 (notification in the right bottom)

**Additional context**
I want to update a file after it's uploaded

**Files**
every file is affected

**Comment by eine** [comment]
@hugomassing, can you please let us know which version of filebrowser are you using (is it a release or you built your own), and provide the config file and the execution command. That will help us reproduce the issue.

**Comment by hugomassing** [comment]
I tried with with one I build myself today, but it was not working with version 1.8 too. I'm quite a beginner with Caddy, but everything is working great so maybe the mistake is on my side

**Comment by eine** [comment]
It's ok. Let's try to find the breaking point. Can you try with the [latest release](https://github.com/filebrowser/filebrowser/releases/tag/v1.9.0) standalone? Just download the binary for your platform, execute it (use the default credentials admin/admin), set the 'After upload' command and try to upload a file. Let us know what output you get, both in the terminal and in the browser console.

**Comment by eine** [comment]
I just tried the following in a play-with-docker node:

``` bash
git clone https://github.com/filebrowser/filebrowser
cd filebrowser
curl -L https://github.com/filebrowser/filebrowser/releases/download/v1.9.0/linux-386-filebrowser.tar.gz | tar xvz
docker run --rm -itv $(pwd):/src -w /src -p 8000:8000 alpine sh -c "apk add -U git && ./filebrowser -p 8000"
```

And it works as expected. However, I had to ensure that:

- `git` is installed in the box where filebrowser is being executed.
- `git` is an allowed command in filebrowser.
- `git status` is executed in a git repo, i.e. the file is uploaded to a git repo.

Moreover, the test produces no output when the file is uploaded. I then executed `$git status` in the search box in order to check it.

@hugomassing can you please check if your setup fulfills those requirements?

**Comment by hugomassing** [comment]
I tried this as well and got it working. I guess the issue is that it produced a 500 when the command resulted in a crash. Also I tried to make the $FILE environnement variable working after an Upload, with no success. I would love to treat every file uploaded with a script. Can you help me with this one?

**Comment by eine** [comment]
Please, provide an example script where you try to setup the FILE environment. Also, let us know what command are you actually putting in the 'After upload' field. Last, please copy any output you get in the terminal. If it crashes, the backend will tell why it crashed.

**Comment by hugomassing** [comment]
I just did `echo $FILE` on After Upload and the terminal output was just $FILE.

**Comment by eine** [comment]
Then, try something like `bash -c "echo $FILE"`.

**Comment by hugomassing** [comment]
Okay and if I want to execute a command like `lltag --yes --mp3v2 --no-tagging --rename "%a - %t" $FILE`?

**Comment by eine** [comment]
It's the same. The point here is that commands are executed in filebrowser/golang by calling the system directly. If you need them to be executed in a shell environment/context (because you are using shell features such as envvars), you need to tell it explicitly.

One option is to use `bash -c "your_commands"` or `sh -c "your_commands"` as commented above. For the specific command you ask about, you will need to either escape the double quotes inside the command, or combine single and double quotes.

Another option is to write a script:

```
#!/bin/sh
your_commands
```

Then, ensure that it is executable with `chmod +x script.sh`. Last, call it directly (`./script.sh`) or add it to the PATH. In order to add it the PATH, you can move the script to a folder that is already in the list (such as `/usr/bin` or `/usr/local/bin`) or you can edit the PATH to add the location of the script (`PATH=$PATH:<location>` or `PATH=$PATH:$(pwd)`).

HINT: you can try `$bash -c "your_commands"` or `$script` in the search box of filebrowser, instead of editing the settings and uploading a file every time. It will make testing the script easier.

I'm closing this issue because the original problem/question is solved. But feel free to continue the conversation.
