### ISSUE TITLE
How to configure apache as a reverse proxy (upgrade connection to websockets)

### ISSUE THREAD

**Issue by anothergituser** [filebrowser/filebrowser#486]
**Description**
Use the search feature.

**Expected behaviour**
Find files

**What is happening instead?**
websocket: not a websocket handshake: 'upgrade' token not found in 'Connection' header
in logs

**Additional context**
The application runs with apache as a reverse proxy

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by francislavoie** [comment]
This doesn't sound like an issue with this project. You'll just need to configure your apache to forward the `Connection` and `Upgrade` headers so that websocket connection can properly upgrade.

**Comment by eine** [comment]
As @francislavoie commented, this seems to be a configuration issue with Apache. See, e.g.:

- https://stackoverflow.com/questions/29792372/apache2-websockets-reverse-proxy-on-same-url
- https://stackoverflow.com/questions/27526281/websockets-and-apache-proxy-how-to-configure-mod-proxy-wstunnel
- https://forum.mattermost.org/t/solved-apache2-reverseproxy-with-websocket-https/437/3

@anothergituser I'm closing this because it seems not to be an issue with filebrowser itself. However, feel free to continue the conversation and let us know if you could solve it.

**Comment by themegabyte** [comment]
For Nginx, this will be like this:

```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
proxy_http_version 1.1;
```

Or in nginx proxy manager or equivalent:

![Image](https://github.com/user-attachments/assets/e63bc269-5d23-452a-8dee-f0c1fca680fa)
