### ISSUE TITLE
Symbolic Link not working in Docker Image

### ISSUE THREAD

**Issue by gdomod** [filebrowser/filebrowser#487]
**Description**
symbolic links are not working in docker image
i mounted my volume to /srv
in my volume i create some ln -s links to some folders

all folders showing as empty, permission are correctly

**Comment by eine** [comment]
Please, can you provide some more info about the context so that we can reproduce it?

- Which image and version are you using?
- Which is the base OS?
- With 'volume' you mean a 'docker volume' or a host directory?
- Are links created from folders in the volume to folders in the volume or is any of them pointing outside?

**Comment by gdomod** [comment]
thanks for fast reply.

in mount -v /var/www in docker image to /srv 

and at host i mount ln -s /tmp to /var/www 

in filemanager i see tmp but i got an error. is that maybe a docker protection ?

base os is ubuntu 18.04

**Comment by eine** [comment]
Well, that's how docker works. It has nothing to do with filebrowser or the filebrowser image specifically.

Docker cannot follow symlinks outside of the volumes that are actually mounted/bind in the container. You created a symlink from `/var/www/tmp` in the host to `/tmp`. But, when the container reads `/srv/tmp -> /tmp`, it tries to follow the link to `/tmp` inside the container, which is empty. In order to achieve what you want, you should also mount/bind `/tmp` in the host to `/tmp` inside the container. See this example:

``` bash
$ mkdir test-dir
$ cd test-dir
$ mkdir test
$ mkdir srv
$ echo "Hello" > test/hello.md
$ echo "World" > srv/world.md
$ cd test
$ ln -s ../srv srv_mnt
$ docker run --rm -itv $(pwd):/test alpine sh -c "ls -la /test && ls -la /test/srv_mnt/"
total 12
drwxrwxr-x    2 1000     1000          4096 Aug  2 12:54 .
drwxr-xr-x    1 root     root          4096 Aug  2 12:54 ..
-rw-rw-r--    1 1000     1000             6 Aug  2 12:54 hello.md
lrwxrwxrwx    1 1000     1000             6 Aug  2 12:54 srv_mnt -> ../srv
total 8
drwxr-xr-x    2 root     root          4096 Jul  5 14:47 .
drwxr-xr-x    1 root     root          4096 Aug  2 12:54 ..
$ docker run --rm -itv $(pwd):/test -v $(pwd)/../srv:/srv alpine sh -c "ls -la /test && ls -la /test/srv_mnt/"
total 12
drwxrwxr-x    2 1000     1000          4096 Aug  2 12:54 .
drwxr-xr-x    1 root     root          4096 Aug  2 12:55 ..
-rw-rw-r--    1 1000     1000             6 Aug  2 12:54 hello.md
lrwxrwxrwx    1 1000     1000             6 Aug  2 12:54 srv_mnt -> ../srv
total 12
drwxrwxr-x    2 1000     1000          4096 Aug  2 12:54 .
drwxr-xr-x    1 root     root          4096 Aug  2 12:55 ..
-rw-rw-r--    1 1000     1000             6 Aug  2 12:54 world.md
$ cd ../..
$ rm -rf test-dir
```
