### ISSUE TITLE
Use Waffle Board for management

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#495]
Maybe it would be useful to use [Waffle.io](https://waffle.io/filebrowser/filebrowser) to help us manage this project. What do you think @filebrowser/maintainers?

**Comment by eine** [comment]
I didn't know about it. It seems very useful. Especially because it allows us to have a common entrypoint to manage all the repositories in the project. Let's use it.

However, I am still missing some messaging/chat service. Does waffle.io provide any or does it rely on slack? I have used both slack and gitter previously, and I think that the latter provides a better integration with GitHub. However, the difference might be negligible depending on how does waffle integrate with slack. Anyway, I'd be also ok with some IRC room.

**Comment by hacdias** [comment]
No, it doesn't have chat/messaging. Why don't we just use IRC, Slack or gitter.im? I'm just not sure which. I'm on IRC and Slack. I used gitter.im previously, but not anymore.

**Comment by hacdias** [comment]
Just created a channel on freenode: https://www.irccloud.com/irc/freenode/channel/filebrowser

**Comment by eine** [comment]
While I was organizing the content in waffle.io, I realized that it is quite similar to GitHub projects. @hacdias, did you try this? What advantages does waffle offer?

Although I cannot see the 'Projects' tab here (yet), I think you can enable it by creating one in https://github.com/filebrowser/filebrowser/projects.

**Comment by ghost** [comment]
wafle existed before github added the projects functionality.
github projects is much better and easier and integrates of course with github issues.
