### ISSUE TITLE
Where is the docker image?

### ISSUE THREAD

**Issue by yaskor** [filebrowser/filebrowser#503]
https://hub.docker.com/r/hacdias/filebrowser/
https://hub.docker.com/r/hacdias/filemanager/

both give 404

**Comment by eine** [comment]
Hi @yaskor! We changed it yesterday and we have not updated all the docs and references yet. It is now available in [hub.docker.com/r/filebrowser/filebrowser](https://hub.docker.com/r/filebrowser/filebrowser/). However, note that it is a "rolling" image, until we push the first release with the new CI scheme.

See #450 and #492.

BTW, we would be so glad if you told us where you found (now) invalid references, so that we can fix them.

**Comment by samil-kale** [comment]
Thx for the quick answer.

If found the reference on the offical [github](https://github.com/filebrowser/filebrowser) readme.md

> Moreover, the previously unique repo was split into multiple pieces: frontend, logo, caddy... At the same time, the official docker image was changed to **hacdias/filebrowser**. Users are encouraged to check their sources and update them accordingly.

**Comment by hacdias** [comment]
Updated the README! Thanks @yaskor

**Comment by emeryao** [comment]
looking forward for the new docker image

**Comment by eine** [comment]
@Emeryao, as commented above, it is already available at https://hub.docker.com/r/filebrowser/filebrowser/tags/. What do you mean?

**Comment by emeryao** [comment]
can we push a *versioned* tag to docker hub besides of the `latest` ?

**Comment by eine** [comment]
Yes. We are about to do it (see https://github.com/filebrowser/filebrowser/pull/497#issuecomment-411584661). But travis is not detecting our pushes right now, so we need to wait (see https://github.com/filebrowser/filebrowser/pull/505#issuecomment-411622451 and https://www.traviscistatus.com/).

**Comment by eine** [comment]
@Emeryao tag `v1.10.0` is available now. See https://hub.docker.com/r/filebrowser/filebrowser/tags/
