### ISSUE TITLE
Hi, I was wondering if it was possible to run or use this with Ubuntu for Windows Subsystem Layer?

### ISSUE THREAD

**Issue by jcklpe** [filebrowser/filebrowser#513]
Hi, I'm a designer learning to code. So first I just want to say this project is BEAUTIFUL! It just looks really great. I love it. 

I was looking for an alternative file browser for Windows when I came across this. I don't think it's really what I need for Windows but I'm intrigued about using it with my WSL installation. 

Sometimes I'd really like to have a GUI interface to mess with files but you can't do that with File Explorer in Windows. BUT I was thinking maybe I could use this to do that?

I ran the script for linux, and  said stuff installed. When I ran filebrowser it gave me this output

```
└─➤ filebrowser
Listening on [::]:13512
panic: invalid page type: 1: 4

goroutine 1 [running]:
github.com/filebrowser/filebrowser/vendor/github.com/coreos/bbolt.(*Cursor).search(0xc420153808, 0xc4201538c0, 0x6, 0x20, 0x5)
        /go/src/github.com/filebrowser/filebrowser/vendor/github.com/coreos/bbolt/cursor.go:256 +0x388
github.com/filebrowser/filebrowser/vendor/github.com/coreos/bbolt.(*Cursor).seek(0xc420153808, 0xc4201538c0, 0x6, 0x20, 0x0, 0x0, 0x0, 0x14aa760, 0x14aa760, 0x7f69aa9306c8, ...)
        /go/src/github.com/filebrowser/filebrowser/vendor/github.com/coreos/bbolt/cursor.go:159 +0xa5
github.com/filebrowser/filebrowser/vendor/github.com/coreos/bbolt.(*Bucket).Bucket(0xc4202381d8, 0xc4201538c0, 0x6, 0x20, 0xc4201538c0)
        /go/src/github.com/filebrowser/filebrowser/vendor/github.com/coreos/bbolt/bucket.go:112 +0xde
github.com/filebrowser/filebrowser/vendor/github.com/coreos/bbolt.(*Tx).Bucket(0xc4202381c0, 0xc4201538c0, 0x6, 0x20, 0x6)
        /go/src/github.com/filebrowser/filebrowser/vendor/github.com/coreos/bbolt/tx.go:101 +0x4f
github.com/filebrowser/filebrowser/vendor/github.com/asdine/storm.(*node).GetBucket(0xc4201f69c0, 0xc4202381c0, 0xc420153960, 0x1, 0x1, 0x46debe)
        /go/src/github.com/filebrowser/filebrowser/vendor/github.com/asdine/storm/bucket.go:40 +0x1dc
github.com/filebrowser/filebrowser/vendor/github.com/asdine/storm.(*node).getBytes(0xc4201f69c0, 0xc4202381c0, 0xa70381, 0x6, 0xc4202323e8, 0x3, 0x8, 0x985e80, 0x985eb0, 0x1, ...)
        /go/src/github.com/filebrowser/filebrowser/vendor/github.com/asdine/storm/kv.go:45 +0x71
github.com/filebrowser/filebrowser/vendor/github.com/asdine/storm.(*node).Get.func1(0xc4202381c0, 0x0, 0xc420153a38)
        /go/src/github.com/filebrowser/filebrowser/vendor/github.com/asdine/storm/kv.go:103 +0x82
github.com/filebrowser/filebrowser/vendor/github.com/asdine/storm.(*node).readTx.func1(0xc4202381c0, 0x11417d0, 0xc4202381c0)
        /go/src/github.com/filebrowser/filebrowser/vendor/github.com/asdine/storm/node.go:124 +0x2f
github.com/filebrowser/filebrowser/vendor/github.com/coreos/bbolt.(*DB).View(0xc4201661e0, 0xc420153aa0, 0x0, 0x0)
        /go/src/github.com/filebrowser/filebrowser/vendor/github.com/coreos/bbolt/db.go:626 +0x90
github.com/filebrowser/filebrowser/vendor/github.com/asdine/storm.(*node).readTx(0xc4201f69c0, 0xc420153b08, 0x1195fa0, 0xc4200aa420)
        /go/src/github.com/filebrowser/filebrowser/vendor/github.com/asdine/storm/node.go:123 +0x8b
github.com/filebrowser/filebrowser/vendor/github.com/asdine/storm.(*node).Get(0xc4201f69c0, 0xa70381, 0x6, 0x985e80, 0xc4201f5210, 0x9659e0, 0xc4201ec0c8, 0xc420153bd8, 0x404fa6)
        /go/src/github.com/filebrowser/filebrowser/vendor/github.com/asdine/storm/kv.go:102 +0x19d
github.com/filebrowser/filebrowser/bolt.ConfigStore.Get(0xc420129420, 0xa6e5c0, 0x3, 0x9659e0, 0xc4201ec0c8, 0xc4201eb9b0, 0x30)
        /go/src/github.com/filebrowser/filebrowser/bolt/config.go:15 +0xcb
github.com/filebrowser/filebrowser.(*FileBrowser).Setup(0xc4201ec0c0, 0xc4201eb9b0, 0x1199d00)
        /go/src/github.com/filebrowser/filebrowser/filebrowser.go:127 +0x197
main.handler(0xc420153f58, 0x2)
        /go/src/github.com/filebrowser/filebrowser/cmd/filebrowser/main.go:228 +0x6d3
main.main()
        /go/src/github.com/filebrowser/filebrowser/cmd/filebrowser/main.go:182 +0x35d

```

I'm afraid maybe I'm just too ignorant still of code to know what exactly I'm looking for here, but the quickstart guide says there should be an address and I don't see anything. I tried putting in localhost:13512 thinking that might be it? But that did not work. So.... I'm not really sure what to do. Maybe it didn't install properly? Maybe it's just not meant to be run in WSL?

I mean it seems like it should run on WSL if it is really just a server that you access through the browser, since I can run my Wordpress website in a linux virtual machine no problem and access it's UI etc in the browser. So... not really sure what to do but I'd love to know if there's a way!

**Comment by eine** [comment]
Hi @thedonquixotic, is there any reason to run filebrowser in WSL and not in Windows directly?

**Comment by jcklpe** [comment]
@1138-4EB Well the reason for wanting to run it in WSL is two fold.: 
1. I tried installing on windows and it gave me some weird errors. 
but more importantly 
2. I don't actually have a GUI solution for messing around with files in WSL right now so this would fill a niche for me that I really need! I can use MidnightCommander to transverse the CLI and copy files etc in a more visual way but this looks much nicer and like it would be a big help for when I want to look at a file that is in WSL. Files that are in WSL, as in actually considered a part of [WSL etc, can't be manipulated by the Windows OS interface because it will mess up and corrupt the files.](https://superuser.com/questions/1110974/how-to-access-linux-ubuntu-files-from-windows-10-wsl) 

When I looked over the features for FileBrowser a little more, I really don't think it serves as a full replacement for what File Explorer, at least not yet, espc consider all the right click context menu integration I have built into File Explorer at this point, BUT it would be good for doing stuff with WSL I think! I just need to figure out what I'm doing wrong 😕

**Comment by eine** [comment]
@thedonquixotic I could make some test in a Windows box. Conclusions:

- In order to use filebrowser in MSYS/MinGW, you should download the windows-amd64 build: https://github.com/filebrowser/filebrowser/releases/download/v1.10.0/windows-amd64-filebrowser.zip It works ok.
- In order to use filebrowser in WSL, you should download the linux-amd64 build: https://github.com/filebrowser/filebrowser/releases/download/v1.10.0/linux-amd64-filebrowser.tar.gz

When you run it in WSL, the program is properly started (as you can see in your logs, `Listening on [::]:13512`), but it then fails because of how the VM underneath handles memory allocation. I could reproduce it in both WSL Debian and WSL Ubuntu. However, if you terminate it (`Ctrl+C`) and start it again, it works ok on the second or third try. From there on, every time you start it no error is produced. Please, let me know if this behaviour is the same in your box. Unfortunately, I cannot further investigate the underlying issue, because it does not fail anymore.

Moreover, in WSL the hard drives are mounted in (`/mnt/c`, `/mnt/d`, etc.). So, you can optionally work in those dirs, and/or use symlinks. I.e., run filebrowser from MSYS/MinGW/PowerShell and set the scope to `D:/workdir`. Then, symlink `~/workdir` to `/mnt/d/workdir` in WSL. Note that this approach would let you use the Windows File Explorer too. However, I have not tried any of these.

**Comment by jcklpe** [comment]
@1138-4EB Excellent. Worked liked a charm!

It launched me into the Windows home folder and not the WSL home folder. Which makes sense as that is what the terminal does also. I'll have to test to see if using symlinks is a viable way to get to that home folder. Though I think I might ultimately be better off just symlinking anything I need to edit etc out into the windows folders. That's what I do with my WP installations anyway so I don't think it makes a huge difference.

**Comment by eine** [comment]
Great! Since you already got it working, I'm closing this issue. Anyway, feel free to continue the conversation and add any further test results that you'd like to share.

**Comment by hugows** [comment]
I wanted to contribute to the project and working on WSL is always more interesting, since you can easily configure node there too. I'm also evaluating WSL at this point so this is interesting for me.

I've put some printfs on the code (could not get Go debugger to work on WSL) and the culprit seems to be BoltDB, which never  returns a **save** call that starts in **bolt.do/NewStorage** function.
