### ISSUE TITLE
Show upload speed and progress during upload

### ISSUE THREAD

**Issue by 1405040117** [filebrowser/filebrowser#519]
Hope achieve upload file display percentage progress and upload speed, similar to BaiduYun.

**Comment by eine** [comment]
Related to #367 and #446.

**Comment by helloray** [comment]
Is it possible to use this simple progress bar with text below it? https://dzwillia.github.io/vue-simple-progress/examples/

**Comment by helloray** [comment]
I have made a demo but it looks ugly. 
![default](https://user-images.githubusercontent.com/5954203/46126393-a1fa0980-c25f-11e8-8e38-0bc8c83f686c.png)

**Comment by eine** [comment]
@helloray , in order to discuss the implementation and (hopefully) get help from other contributors, please open a PR in the corresponding repo. If only frontend sources are modified, the repo is [filebrowser/frontend](https://github.com/filebrowser/frontend). If it requires some other modification in the backend, open another issue in this repo, and link both of them.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
