### ISSUE TITLE
"no buildable Go source files" when building caddy-hugo

### ISSUE THREAD

**Issue by ludovicc** [filebrowser/filebrowser#52]
Hello,

I'm trying to build a Docker container with Caddy and Caddy-hugo. I'm getting this error and I know no much about Go. Can you help?

```
no buildable Go source files in /home/go/src/github.com/hacdias/caddy-hugo/assets
```

Here is my Dockerfile, save it in a directory then run 'docker build .' to reproduce the problem.

```
FROM abiosoft/caddy

RUN apk add go mercurial && mkdir /home/go
ENV GOPATH /home/go
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/go/bin/
RUN /usr/bin/go get -u github.com/jteeuwen/go-bindata/...
RUN /usr/bin/go get github.com/caddyserver/caddydev
RUN /usr/bin/go get github.com/hacdias/caddy-hugo
RUN cd /home/go/src/github.com/hacdias/caddy-hugo && /usr/bin/go generate
```

**Comment by hacdias** [comment]
Hello!

That "error" is normal. That's why you have to execute `go generate` then. It can be skipped, or is it preventing you to continue?

**Explanation**

That error happens because there's no `.go` file in `assets` when you clone the repository. When you execute `go generate` the following commands are executed:

``` bash
go get github.com/jteeuwen/go-bindata
go install github.com/jteeuwen/go-bindata/go-bindata
go-bindata -pkg assets -o assets/assets.go templates/ assets/css/ assets/js/ assets/fonts/
```

The last one will build an `assets.go` file in `assets`. After that, you should not receive that error anymore.

**A question**

Why are you using "FROM abiosoft/caddy" if "mholt/caddy" is the actual repository and "abiosoft/caddy" is just a fork?

**Comment by ludovicc** [comment]
I can deal with that, it's less scary than it looks. I will publish the
Docker file later.

Thanks

**Comment by hacdias** [comment]
Thank you too! I'll close this issue for now. When you publish the Docker file, let we know! :)

Have a nice day!

**Comment by faddat** [comment]
That explains it!

And about the Docker-- @abiosoft  has been doing incredible things with caddy and docker, so I imagine that is the reason....

**Comment by ludovicc** [comment]
I have published my Dockerfile here: https://github.com/ludovicc/caddy-hugo. It should appear also in hub.docker.com as ludovicc/caddy-hugo.
