### ISSUE TITLE
Build Caddy from source

### ISSUE THREAD

**Issue by hugomassing** [filebrowser/filebrowser#520]
Before the recent changes, I was able to build my own caddy version with filebrowser and update my version of filebrowser by hand. 

Now when I build my caddy executable, when running it, I have this error : 
```
panic: EmbeddedBox with name `../frontend/dist` exists already

goroutine 1 [running]:
github.com/GeertJohan/go.rice/embedded.RegisterEmbeddedBox(0x104cac4, 0x10, 0xc42021f0c0)
       .go/src/github.com/GeertJohan/go.rice/embedded/embedded.go:77 +0x18d
github.com/filebrowser/caddy/assets.init.0()
        .go/src/github.com/filebrowser/caddy/assets/rice-box.go:221 +0x224b
```

I may be missing something, but what's the proper way to build Caddy with filebrowser without downloading it from the website? I've looked in the various build script, but didn't found something. 

Building my `filebrowser` executable with `build_all.sh` is working.

**Comment by eine** [comment]
> Building my `filebrowser` executable with `build_all.sh` is working.

I think that this is the point. Bear with me:

`filebrowser` is a repository, `frontend` is a subrepo/subdir, and `caddy` is an 'external' repo.

Prior to #399 and #506, the procedure was:

- Build `filebrowser/frontend` from `filebrowser/frontend`, which left the artifacts in `filebrowser/frontend/dist`.
- Pack the content of `filebrowser/frontend/dist` to `filebrowser/rice-box.go`, by executing `rice embed-go` in `filebrowser` (the root of the repo).
- Build `caddy`, which imported `github.com/filebrowser/filebrowser`, and consequently `filebrowser/rice-box.go`.

Therefore, it was required that a maintainer built the frontend and pushed the rice-box to the filebrowser repo. This was not desirable, because the rice-box contains the artifacts from the frontend, so it is not a 'real' source file. Also, we wanted to have it completely automated.

So:

- In #399, `rice-box.go` was removed from `filebrowser`. The frontend is now built in the CI environment, and it is used directly. When a tagged commit is pushed (a release), the `rice-box.go` is automatically pushed to `caddy/assets` (note that the first line is rewritten from `package filebrowser` to `package assets`). See (long) discussion about this starting from [#399-issuecomment-401897721](https://github.com/filebrowser/filebrowser/pull/399#issuecomment-401897721).
- In #506, we refactored the sources of `filebrowser` to subdirs `lib` and `cli`. So now, `rice embed-go` is executed in `filebrowser/lib` (see [build_assets.sh#L22-L23](https://github.com/filebrowser/filebrowser/blob/master/build/build_assets.sh#L22-L23)) and the file is generated as `filebrowser/lib/rice-box.go` (see [build_all.sh#L45](https://github.com/filebrowser/filebrowser/blob/master/build/build_all.sh#L45)). Note that, as a result, when `rice-box.go` is pushed to `caddy` the first line is rewritten from `package lib` to `package assets`, also the name of the box changed from `./frontend/dist` to `../frontend/dist`.

---

As a result, if you execute `build_all.sh` and you then try to build `caddy/filemanager`, you have two copies of `rice-box.go`. One of them is located at `filebrowser/lib/rice-box.go` (ignored through `.gitignore`) and the other one is `caddy/assets/rice-box.go`. You cannot add two boxes with the same name. No matter if the content of the boxes is exactly the same (which is probably true), because they belong to different packages. That's the source of your error.

---

The most simple solution is to remove `filebrowser/lib/rice-box.go`. However, this is only an option if you don't mind/want the latest frontend, as the existing rice box in `caddy/assets/rice-box.go` will be used.

---

The second option, and the best solution in this context, is to execute this from `caddy` (assuming that `caddy` is a sibling of `filebrowser`):

``` bash
mv ../filebrowser/lib/rice-box.go ./assets/
sed -i 's/package lib/package assets/g' assets/rice-box.go
```

You will have a single rice-box, built from the 'latest' frontend sources. This is equivalent to what is executed in the CI flow (see [push_ricebox.sh#L15](https://github.com/filebrowser/filebrowser/blob/master/build/push_ricebox.sh#L15)).

---

As a last approach, you can just remove [parser.go#L22](https://github.com/filebrowser/caddy/blob/master/parser/parser.go#L22). It will ignore `caddy/assets/rice-box.go`, so that `filebrowser/lib/rice-box.go` is used. Note that you cannot remove `caddy/assets/rice-box.go` without editing `parser.go`, because it would be importing an empty dir/package. 

This might be desirable if you want to make multiple consecutive builds of the frontend and test the results with caddy. You avoid executing `mv` and `sed` each time, but you need to remember resetting the changes to `parser.go` before you commit/leave.

---

I hope that this explanation, although long, helps you grasp the details of the flow. I thought that it would be useful for you, as you are starting to dive into the project.

Also, I am sorry for the inconveniences that recent changes might have produced. Hopefully, these are for good.

Please, let us know if these solutions work for you.

**Comment by hugomassing** [comment]
Okay, I got this working with method 2. Thank you so much for your help with this. Learned a lot using your code!
