### ISSUE TITLE
Make it easier to get started with Docker

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#525]
**Is your feature request related to a problem? Please describe.**
Getting started with Docker is not as simple as it could be. https://filebrowser.github.io/installation/#docker In order to map database.db, you need to have a database.db file but as a new user where do you get this file from?

**Describe the solution you'd like**
Most of the time when creating a docker container, as a user you only need to specify a directory (not a file) for config i.e.
instead of the current
```
-v /path/to/config.json:/config.json \
-v /path/to/database.db:/database.db \
```
it would be
`-v /path/to/filebrowser:/config`
The application then stores whatever config it needs in the config folder e.g. database.db, config.json etc. The application has logic, if database.db is present then use it, if nothing present -> then create a database.db for the new user
Mapping to a folder is much nicer than files

**Describe alternatives you've considered**
None

**Additional context**
The instructions could be clearer as well
https://filebrowser.github.io/installation/#docker
In one place the path is `/etc/config.json` and the other `/config.json` and `/etc/database.db` vs `/database.db`

**Comment by brandonkal** [comment]
Why? The DB file does not need to exist on the host, it is created by the mount. Bind mounting a file is not any harder than a folder... Or just use docker volumes and keep it simple. Also it seems you are confusing docker daemon logic with application logic.

**Comment by ghost** [comment]
What's the advantage of specifying multiple files over a single folder?
If I keep it simple and just use docker volumes, how do I retain my settings on a different host?

**Comment by eine** [comment]
> In order to map database.db, you need to have a database.db file but as a new user where do you get this file from?

It can be an empty file: `touch database.db`.

> The application then stores whatever config it needs in the config folder e.g. database.db, config.json etc.

Filebrowser, by default, looks for a config file named `.filebrowser.[ext]` in either `.`, `/etc/filebrowser/` or `$HOME`. So, if the default config file is moved to `/config`, it won't be found unless the path is explicitly given through flags or envvars.

Then, changing https://github.com/filebrowser/filebrowser/blob/master/Dockerfile#L10 to `COPY Docker.json /etc/filebrowser/.filebrowser.json` is an option, should you want to propose a PR. If so, the `database` field in the default config should probably need to be changed too.

> The application has logic, if database.db is present then use it, if nothing present -> then create a database.db for the new user

This is already the case. The underlying issue is that docker creates a `database.db` folder in the host if it does not exist as a file. Thus the need to `touch` it.

> Mapping to a folder is much nicer than files

You can do it already: `docker run -d -p 8888:80 -v /path/to/config:/config filebrowser/filebrowser -c /config/config.json`. Given that you set `database: "/config/database.db"` in you config file.

> The instructions could be clearer as well
filebrowser.github.io/installation/#docker
In one place the path is /etc/config.json and the other /config.json and /etc/database.db vs /database.db

We'd be glad to accept a PR in https://github.com/filebrowser/filebrowser.github.io, should you be willing to make it more coherent.

> What's the advantage of specifying multiple files over a single folder?

Making it explicit that two, and only two, files are used. Also, allowing the user to bind only one of them. For example, I normally bind the config file but I ignore the database, because I don't want it to be persistent.

Anyway, specifying multiple files would still be possible if put in the same folder. So, it is possible to support both use cases.

> If I keep it simple and just use docker volumes, how do I retain my settings on a different host?

You just export the volume and import it in the different host: https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes

**Comment by ghost** [comment]
@1138-4EB wow, thank you for such a helpful response
I'll have a play and then create PR for the docs

**Comment by ghost** [comment]
Thanks 
@flightlevel
this fixed my issue

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
