### ISSUE TITLE
more information on docker hub

### ISSUE THREAD

**Issue by bdito** [filebrowser/filebrowser#528]
**Is your feature request related to a problem? Please describe.**
The image on docker hub ( https://hub.docker.com/r/filebrowser/filebrowser/ ) has no readme and no description. 

**Describe the solution you'd like**
- add a short description in docker hub
- add readme with quickstart or link back to github and/or to the official documentation
- add icon for the user filebrowser on docker hub

**Comment by dtwilliams10** [comment]
I can work this issue, just need permission to the repo in Docker Hub.

**Comment by hacdias** [comment]
@dtwilliams10 you can work on that here or on a PR. The descriptions for Docker Hub you write them here and we can update them 😄

**Comment by dtwilliams10** [comment]
@hacdias Ok I'll get started, did you want to assign this issue to me? I'll open a PR when I'm done.

**Comment by eine** [comment]
I took the proposal by @dtwilliams10 as a reference, and I updated the descriptions of the two repos:

- https://hub.docker.com/r/filebrowser/filebrowser/
- https://hub.docker.com/r/filebrowser/dev/

However, I could not add the icon/logo, because it seems that the only option is to do it through gravatar. @hacdias, can you please register filebrowserbot there with its email account?

@dtwilliams10, @bdito, feel free to propose any additional refinement to the current descriptions.
