### ISSUE TITLE
Build broken on Go <= 1.11

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#530]
See https://github.com/pierrec/lz4/issues/33.

@1138-4EB could you update the Go version around, please?

**Comment by eine** [comment]
It is fixed now. For some arbitrary reason related to curl, the last execution of https://travis-ci.com/filebrowser/docker-dev had failed. It was not started again because it is scheduled weekly. I triggered manually and now filebrowser/dev is based on go1.11.

Now, there is a problem with yarn: https://travis-ci.com/filebrowser/filebrowser/builds/82754910. I don't know why it cannot connect to the yarn/npm registry. I can reproduce it locally, so it is not a travis issue.
