### ISSUE TITLE
POLL: do you use staticgen?

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#577]
As we are renovating and rewriting for the next version, do you think we should keep Static Gen? Do you use it or not?

React with 👍 if you use it, or 👎 otherwise.

If we removed it, would you be satisfied with:
- Using the command hooks (before/after save,rename, etc)
- Or even custom buttons you could add commands to.

Ping @1138-4EB @Equim-chan @Bitti09 @torch2424 @sinni800 @saveshodhan @chinglinwen @hugomassing @maweck @DeyV @VLEFF @mozzbozz @tokvv @mdlawson @igargi @oopsmonk @dvrkps @pandarong @genofire @maxux @rigon @kairen @coco-perso @ericvolp12 @thomasyxy @llitfkitfk @EduardoRT @princemaple @matm @ptman @thgh @Timmmm @abiosoft @bronzehedwick

**Comment by ptman** [comment]
I'm sorry, I don't know enough to make an informed decision. Would you kindly tell us some pros and cons?

**Comment by sinni800** [comment]
I'm not sure if I remember this right, but wasnt the hugo caddy plugin basically filebrowser with... some differences or something? 

Honestly I've actually never used staticgen, but all it is is just running static site generator programs as far as I could see

**Comment by hacdias** [comment]
@ptman hey! Not having the direct integration, you would lost the preview feature and would have to run the hugo/jekyll command by yourself (or via a custom button if we built that feature). Honestly, it doesn't seem worth it for me, but if many users use it, I'll keep the feature.

After the rewriting/revamping I could release a beta version so people could test and see if they need some feature back.

---

@sinni800 yes, basically it's just a wrapper to let you run some commands directly via the interface and it also works without the Caddy integration (via some CLI flags). My suggestion is just to remove this and add custom buttons (#91).

**Comment by torch2424** [comment]
Super rad you are reaching out to the community to make this decision! 😄 

I don't know what static gen is, so I guess not? haha!

**Comment by sinni800** [comment]
I think most users don't even know about the source here, which is a problem... I have no actual opinion on this, but I think the preview is something people probably don't want to lose!

**Comment by eine** [comment]
I think that it should be either split, as you suggest, or fully integrated (so that no external binary is required). Now, it is both a build dependency and the binary is required. So removing the former sounds good.

**Comment by hacdias** [comment]
@sinni800 not file preview, but website preview. A static website generator is something like [Hugo](http://gohugo.io) which takes your files and then generates a website from them. Right now we support previewing instead of publishing. Although it doesn't work well, so I don't believe many people use it.

File previews will be kept!

@torch2424 👏 

@1138-4EB I think the sensible option is to split: we can leave a guide explaining how to configure the hooks and custom buttons for a better experience.

**Comment by mozzbozz** [comment]
Well, I think this thing is called "filebrowser", not "static site generator". So... I didn't even know filebrowser can do that - and as far as I read the comments in this ticket, the feature also seems a bit hacky, so I guess it's best to just drop it.

**Comment by vitaliy-kuzmich** [comment]
> I think most users don't even know about the source here, which is a problem... I have no actual opinion on this, but I think the preview is something people probably don't want to lose!

hey, I tried, and image preview did not work, what kind of preview are you talking about ? 

UPD: got it, you are talking about view, because preview, is something that has cut version of original file, or not full file view.

**Comment by vitaliy-kuzmich** [comment]
> Well, I think this thing is called "filebrowser", not "static site generator". So... I didn't even know filebrowser can do that - and as far as I read the comments in this ticket, the feature also seems a bit hacky, so I guess it's best to just drop it.

oh thats the problem, I also noticed that, there is no focus on which way  filebrowser are going, it looks like a cloud tool, but at the same time it is not. And if considering it as a non cloud, there is no need to have image previews generator, nor user's database, no database at all... And in case cloud, there should be users, also roles, and it should work like a cloud, otherwise it loses point. Look, I did fork( https://github.com/vitaliy-kuzmich/filebrowser), and I am going to modify the source, in order to be cloud analog like nextcloud/owncloud. In all other cases, I use ssh, ftp. There are clients on android as well in order to send/receive files.

**Comment by hacdias** [comment]
We're removing the integration with Hugo and Jekyll on the next version. 

@vitaliy-kuzmich, this is not about image preview. And File Browser is meant to be used as a replacement for nextcloud.

Also, File Browser is not a static website generator and it never was.

**Comment by hacdias** [comment]
Will close this! We will remove this feature on 2.0

**Comment by skyfaller** [comment]
I used the Caddy Hugo plugin on my personal websites, as well as a website for a paying client, and I had no idea until I went to update Caddy just now that this feature had gone away! I don't have a replacement GUI for my client to edit his Hugo pages, I am entirely reliant on caddy hugo. Is there any chance that Hugo integration could be brought back, or split out into its own project somehow?

**Comment by eine** [comment]
@skyfaller, you can still use Hugo with Filebrowser. Just install it in the environment where filebrowser is executed (either a docker container or the host), and use commands/hooks to run either `hugo` or `hugo serve` with the desired parameters. Which feature are you missing?

**Comment by skyfaller** [comment]
Unfortunately I'm a noob who doesn't understand what you just said. I don't see any documentation on the website for replicating the old Caddy Hugo behavior. I don't know what features I'm missing because I barely understand what Caddy Hugo did, how Hugo integration worked or what is lost now that it is gone. I haven't really run Hugo from the command line at all.

What commands would I need to run to do the same things that Caddy Hugo did, and how do I set them up in the new File Browser?

**Comment by eine** [comment]
> Unfortunately I'm a noob who doesn't understand what you just said.

Please, be more specific. Which terms did you not understand?

> I don't see any documentation on the website for replicating the old Caddy Hugo behavior.

As explained above, integration with static site generators was just a side feature. Since it has been removed, there is no explicit documentation, because it is not actively supported anymore.

However, if you want to use File Browser to edit some Markdown sources which are then to be processed with hugo to generate a web site, that's something you can still do. Also, if you want to edit sources with File Browser and use `hugo server` to serve the site, you can do that too.

> I don't know what features I'm missing because I barely understand what Caddy Hugo did, how Hugo integration worked or what is lost now that it is gone. I haven't really run Hugo from the command line at all.

You might not know how did Caddy Hugo did what it did, and how did it integrate with hugo. However, no other but you can explain what did you use it for. You said you were using it on your personal websites, as well as a website for paying client. How do you call the service you are charging for? That might help us define what do you need. Also, how were you serving all those different sites? Were all of them served in the same url?

> What commands would I need to run to do the same things that Caddy Hugo did, and how do I set them up in the new File Browser?

I did never use Caddy Hugo, because File Browser and Hugo as separate tools fit my needs. So I do not know the details about what Caddy Hugo did, and which of the features did you use.

This is the main site of project Hugo: https://gohugo.io/. There are a [Quick Start](https://gohugo.io/getting-started/quick-start/) and some other [guides](https://gohugo.io/getting-started/). The documentation can be found at https://gohugo.io/documentation/. The repo is https://github.com/gohugoio/hugo.
