### ISSUE TITLE
User groups

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#614]
With the new version (2.0) we introduce new ways of user management through the command line which will make it a lot easier to add bunch of new users or to change the password of that person that forgot it.

Although, and as per some requests, such as what's contained on #401, I'm opening this issue about **user groups**. A feature maybe similar to Linux user groups or the following:

1. A user group is created with some defaults
2. When creating a user, we can choose which user group to use for defaults

This is not actually a user group, but just different templates for user settings so it could also be in a different way:

1. A user group X sets the options Q, W and E
2. A user is created and its part of user X. Hence, options Q, W and E will **always** come from the group X and won't be available for change in the user X.

This needs some thought and won't be for 2.0.

**Comment by eine** [comment]
I think we can extend it for a user to be able to be in multiple groups. For each resource, we evaluate the permissions of each of the groups and the ones of the user, resulting in the most permissive.

So, each user struct has a new field which is a list of groups. But I am not sure about how to implement groups. Would those be users without login? Or should be declare a new type? I think a new type would be better, because it would allow future extensions such as setting owners of the groups.

**Comment by hacdias** [comment]
Yes, a different struct. But let's wait for 2.0 to be released and polished. This would be an excellent feature, but let's focus on the current work now.

This would need a completely restructure of how we see users. All users would need to have groups, but one of the groups could be special in the way that it doesn't define anything so the user is defined by itself. That would simplify code (in my head).

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
