### ISSUE TITLE
Watch config

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#617]
_(idea imported from #489)_

Viper allows us to watch for changes in the config and update our program according to those changes. It might be interesting for those experimenting with config files.

See more: https://github.com/spf13/viper#watching-and-re-reading-config-files

**Comment by eine** [comment]
If I recall correctly, viper already does this with environment variables. I.e., each time `viper.GetString` is called, the corresponding envvar is evaluated. However, from our point of view is quite useless ATM, because we read the parameters just once (when starting the server). Even if viper changed the values (either because envvars are reset or because a config file change), the server would not be aware about it. Are you thinking about restarting the server when changes are detected?

**Comment by hacdias** [comment]
Yes, that was what I was thinking but I'm not sure if it's worth it

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
