### ISSUE TITLE
Calculate proper folder size

### ISSUE THREAD

**Issue by fazo96** [filebrowser/filebrowser#633]
Folders show up as being 4kb in size regardless of their content

**Comment by hacdias** [comment]
Hello @fazo96! Which platform and File Browser version are you using?

**Comment by fazo96** [comment]
hey @hacdias I am running the linux amd64 build on Arch Linux using this PKGBUILD https://aur.archlinux.org/packages/filebrowser-bin/

I am still on Filebrowser 1.10 and I just noticed there is a new update, so I'll try that today

**Comment by fazo96** [comment]
The problem persists on Filebrowser 1.11

I thought maybe it was happening because the files are on an NTFS filesystem but it happens with ext4 too

**Comment by hacdias** [comment]
Oh, please check v2.0 and see if the issue persists.
https://docs.filebrowser.xyz/upgrade-from-1.x

**Comment by helloray** [comment]
In Linux, command "ls" also show 4096 as folder size. This is normal not a bug.

**Comment by hacdias** [comment]
Yes, what @helloray said is true. Also, we shouldn't be showing directories size:

![image](https://user-images.githubusercontent.com/5447088/51122878-c7ad1d80-1812-11e9-9873-abfec6feccc5.png)

Is it in the informations modal? If so, it might have been a mistake because we aren't suppose to be showing directories size.

**Comment by hacdias** [comment]
I'm closing this since it is not really an issue. Although I have hidden the size field when only one folder is selected.
