### ISSUE TITLE
Cannot build from scratch

### ISSUE THREAD

**Issue by sibprogrammer** [filebrowser/filebrowser#663]
**Description**
Attempt to build from scratch has failed due to problems with dependencies.

**Expected behaviour**
Successful generation of the binary.

**What is happening instead?**
Bunch of errors:

```
 ❯ go build                                                                                                                                                               [12:17:54]
# github.com/mholt/archiver
../../go/pkg/mod/github.com/mholt/archiver@v3.1.0+incompatible/lz4.go:18:7: undefined: lz4.NewWriter
../../go/pkg/mod/github.com/mholt/archiver@v3.1.0+incompatible/tarlz4.go:84:12: undefined: lz4.Writer
../../go/pkg/mod/github.com/mholt/archiver@v3.1.0+incompatible/tarlz4.go:86:10: undefined: lz4.NewWriter
# golang.org/x/sys/unix
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20181205085412-a5c9d58dba9a/unix/fcntl.go:26:42: undefined: Flock_t
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20181205085412-a5c9d58dba9a/unix/ioctl.go:14:47: undefined: Winsize
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20181205085412-a5c9d58dba9a/unix/ioctl.go:25:47: undefined: Termios
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20181205085412-a5c9d58dba9a/unix/sockcmsg_unix.go:37:18: undefined: Cmsghdr
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20181205085412-a5c9d58dba9a/unix/sockcmsg_unix.go:43:9: undefined: Cmsghdr
```

**How to reproduce?**
* checkout master branch (checked on 4a2573830ea76246c13d16fda1ad75fcd133996c)
* prepare all dependencies (`go mod download`, frontend preparation)
* run `go build`

**Comment by eine** [comment]
Did you try executing `./wizard.sh -b` from the root of this repo? Optionally, `USE_DOCKER="true" ./wizard.sh -b` will execute everything in a docker container.

- https://github.com/filebrowser/filebrowser/blob/master/wizard.sh#L176-L212
- https://github.com/filebrowser/filebrowser/blob/master/wizard.sh#L79-L93
- https://github.com/filebrowser/filebrowser/blob/master/wizard.sh#L103-L110

**Comment by sibprogrammer** [comment]
> Did you try executing ./wizard.sh -b from the root of this repo?

Yes, the same problem.

> Optionally, USE_DOCKER="true" ./wizard.sh -b will execute everything in a docker container.

It works (there is another problem: it produces Linux binary, but I'm on Mac)

Here is some additional information:
```
 ❯ go version
go version go1.11.5 darwin/amd64
```

**Comment by eine** [comment]
> > Did you try executing ./wizard.sh -b from the root of this repo?
> 
> Yes, the same problem.

It seems that it can properly get the dependencies when they are missing (that's why it works inside the container). However, neither `go mod download` nor `go get ./...` seem to be able to checkout the proper version if you already have a different one.

I am not sure. Maybe this is how `go mod` is expected to work. Can you run `go mod vendor` and build with it instead of the other locations in your host?

> It works (there is another problem: it produces Linux binary, but I'm on Mac)

Sure. Just add `GOOS` and `GOARCH` flags to line [wizard.sh#L108](https://github.com/filebrowser/filebrowser/blob/master/wizard.sh#L108). We use a separate procedure (goreleaser) to generate all the artifacts for the different platforms.

**Comment by sibprogrammer** [comment]
> Can you run `go mod vendor`

Didn't help. Seems like it just copies the content of $GOPATH/pkg/mod

I decided to remove the whole $GOPATH/pkg directory and repeat `go mod download`
It helped (after two attempts). Seems like the problem is more about the stability of `go mod` and there is no reason in proposed patch (34b62f1)

Thank you for your help :)

**Comment by eine** [comment]
> > Can you run `go mod vendor`
> 
> Didn't help. Seems like it just copies the content of $GOPATH/pkg/mod

Note that `go mod vendor` will only create and fill the subdir. Apparently, you need to run `go build -mod vendor` (line [wizard.sh#L108](https://github.com/filebrowser/filebrowser/blob/master/wizard.sh#L108)) in order to use it. See https://www.reddit.com/r/golang/comments/9ai79z/correct_usage_of_go_modules_vendor_still_connects/.
 
> Thank you for your help :)

You are welcome. I'm glad it worked in the end ;).
