### ISSUE TITLE
Unable to use filebrowser by docker

### ISSUE THREAD

**Issue by truc0** [filebrowser/filebrowser#667]
**Description**
I'm trying to use filebrowser by docker. I followed the docs but got an error.

__Basic info__:
My system info:
-   Ubuntu 18.04.1 LTS (bionic)
What i did is:
![info](https://user-images.githubusercontent.com/22969604/52173001-f93d4880-272f-11e9-9a8d-e721681590f1.png)
After running the command in screenshot above, the directory tree of `/srv/test/filebrowser` is:
```
/srv/test/filebrowser/
├── filebrowser.db
└── .filebrowser.json

2 directories, 0 files
```
__Note__: `.filebrowser.json` is a directory now!

**Expected behaviour**
Set up successfully by docker...

**What is happening instead?**
An error occurred.  Can be found in screenshot above. The error text is here:
```
Status: Downloaded newer image for filebrowser/filebrowser:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/srv/test/filebrowser/.filebrowser.json\\\" to rootfs \\\"/var/lib/docker/overlay2/c4e9cb1e5d5800aebff23df12464d0adafa851cda51989aa5315dca9c71b7654/merged\\\" at \\\"/var/lib/docker/overlay2/c4e9cb1e5d5800aebff23df12464d0adafa851cda51989aa5315dca9c71b7654/merged/.filebrowser.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```
And the docker container status is :
![info](https://user-images.githubusercontent.com/22969604/52173066-13c3f180-2731-11e9-8b46-5ba42b4597b6.png)

**Additional context**
I removed the directory `.filebrowser.json` and replace it by following config:
```json
{
    "log": "debug",
    "root": "/share",
    "database": "/srv/filebrowser/filebrowser.db",
    
    "address": "127.0.0.1",
    "port": 29920,

    "perm.admin": true,
    "perm.download": true,
    "perm.execute": false,
    "perm.modify": true,
    "perm.share": true
    
}
```
And recreate a container(delete and create), I got these:
![info](https://user-images.githubusercontent.com/22969604/52173088-8339e100-2731-11e9-8386-428eb74e491b.png)

**How to reproduce?**
Redo my steps...

**Files**
No file.

**Comment by eine** [comment]
Hi @wozuishuai13768! There is nothing wrong here. That is the expected behaviour of docker. When you try to bind a path on the host with `-v <HOST_PATH>:/<CONTAINER_PATH>`, if `<HOST_PATH` does not exist, a directory is created. You need to ensure that `.filebrowser.json` and `filebrowser.db` exist, if you want to bind them as files. See https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior.

However, note that there is already a `.filebrowser.json` file inside the container (`/etc/filebrowser/.filebrowser.json`). You don't need to provide another (empty) one. You only need to provide it if you want to use yours. The same applies to the database: unless you want to provide your own, it is not required to bind it. Moreover, if you bind the parent directory (`/srv/test/filebrowser`), you don't need to bind each file explicitly.

Last, you don't need to use `/srv` as the folder on the host. That parameter corresponds to filebrowser inside the container. For example, to bind a subdir of wherever you are:

``` bash
$ mkdir -p filebrowser_data
$ sudo docker run \
  -v $(pwd)/filebrowser_data:/srv
  -p 21190:80 \
  filebrowser/filebrowser
```

**EDIT**

Note that there are three relevant paths inside the container:

- The config file.
- The database file.
- The directory where the content to be served is saved.

The config file and the database file need not to be in the directory which is to be served. Otherwise, any user would have access to them. That's why the example in the docs provides three different binds. Nevertheless, it can also be achieved with a single bind. For example:

```
- filebrowser_dir
  - data
  - filebrowser.db
  - .filebrowser.json
```

``` bash
$ sudo docker run \
  -v $(pwd)/filebrowser_data:/srv
  -p 21190:80 \
  filebrowser/filebrowser -c /srv/.filebrowser.json -d /srv/filebrowser.db -r /srv/data
```

**Comment by Mosney** [comment]
But this [tuition](https://docs.filebrowser.xyz/installation ) gives a sample include  

>     -v /path/filebrowser.db:/database.db \  
>     -v /path/.filebrowser.json:/.filebrowser.json \  
I think it will be lead to a misunderstand

**Comment by eine** [comment]
@Mosney, we expect docker users to be aware of how docker volumes and mounts work. Nonetheless, a PR for the docs would be very welcome!
