### ISSUE TITLE
Some txt file can be preview and edit, but some can not.

### ISSUE THREAD

**Issue by chinanoahli** [filebrowser/filebrowser#681]
**Description**
Some txt file can be preview and edit, but some can not.

**Expected behaviour**
All txt file can be preview? Otherwise why preview and edit function?

**What is happening instead?**
Some txt file can be preview and edit, but some can not.
Like I have a file.txt in ./files, it just can be download, it can not being preview and edit.
But test.txt in ./files/test can being preview and edit, and of course download too.

**Additional context**
I am using filebrowser in ubuntu 18.04 lts x86_64, launch it by a custom server:
```
#/etc/systemd/system/filebrowser.service

[Unit]
Description=File Browser v2 Service
After=network.target
Wants=network.target

[Service]
Type=simple
PIDFile=/var/run/filebrowser.pid
ExecStart=/usr/local/bin/filebrowser -c=/home/filebrowser/config.json -d=/home/filebrowser/filebrowser.db -r=/home/filebrowser
RemainAfterExit=no
Restart=on-failure
RestartPreventExitStatus=23

[Install]
WantedBy=multi-user.target
```
file /home/filebrowser/config.json (seem does not have effect at all):
```
{
  "settings": {
    "signup": false,
    "defaults": {
      "scope": "./files",
      "locale": "zh-tw",
      "viewMode": "list",
      "sorting": {
        "by": "name",
        "asc": false
      },
      "perm": {
        "admin": false,
        "execute": false,
        "create": false,
        "rename": false,
        "modify": true,
        "delete": false,
        "share": false,
        "download": true
      },
      "commands": []
    },
    "authMethod": "json",
    "branding": {
      "name": "Magical Space J1",
      "disableExternal": false,
      "files": "/home/filebrowser"
    },
    "commands": {
      "after_copy": [],
      "after_delete": [],
      "after_rename": [],
      "after_save": [],
      "after_upload": [],
      "before_copy": [],
      "before_delete": [],
      "before_rename": [],
      "before_save": [],
      "before_upload": []
    },
    "shell": [],
    "rules": []
  },
  "server": {
    "root": ".",
    "baseURL": "",
    "tlsKey": "",
    "tlsCert": "",
    "port": "8080",
    "address": "127.0.0.1",
    "log": "stdout"
  },
  "auther": {
    "recaptcha": null
  }
}
```

**How to reproduce?**
I don't know yet. There's no specific pattern.

**Comment by eine** [comment]
> Like I have a file.txt in ./files, it just can be download, it can not being preview and edit.
> But test.txt in ./files/test can being preview and edit, and of course download too.

Is it `./files/test` or `./files/test.txt`? What's the size of both `test[.txt]` files? Is it the same?

**Comment by chinanoahli** [comment]
> > Like I have a file.txt in ./files, it just can be download, it can not being preview and edit.
> > But test.txt in ./files/test can being preview and edit, and of course download too.
> 
> Is it `./files/test` or `./files/test.txt`? What's the size of both `test[.txt]` files? Is it the same?

Emmmm, my fault, wrong typing, it should be `./files/test.txt` and `./files/test/test.txt`.

This description just for issue example. It is not truly existence.

Those file are not the same size. But they are text files.

I though if you can login to my server, you can try it your self.
Please contact me via [telegram](https://t.me/chinanoahli) if you can.
I can create an user for you on testing.

**Comment by eine** [comment]
> Emmmm, my fault, wrong typing, it should be `./files/test.txt` and `./files/test/test.txt`.

It is ok. Filebrowser does check the extension of the files, so it could have been relevant.
 
> This description just for issue example. It is not truly existence.
> 
> Those file are not the same size. But they are text files.

The size is relevant. There were some recent 'fixes' to precisely avoid loading large text files. See #558 and #531.

> I though if you can login to my server, you can try it your self.
> Please contact me via [telegram](https://t.me/chinanoahli) if you can.
> I can create an user for you on testing.

Unfortunately, we are just volunteer students in our spare time, and we cannot offer this kind of service. We need you to debug you own platform and provide enough information, context and example files here so that other users can reproduce the issue on their own. This helps us focus on issues/bugs in the code base, and not on user-specific settings.

**Comment by chinanoahli** [comment]
The files that can be edit and preview, size are 1.46KB and 1.03KB.
Located in `./files/剪贴板导入/由iOS_Quantumult导出.txt`
and `./files/剪贴板导入/由PC_V2RayN导出.txt`
URL is `https://xxxx/files/files/%E5%89%AA%E8%B4%B4%E6%9D%BF%E5%AF%BC%E5%85%A5/%E7%94%B1iOS_Quantumult%E5%AF%BC%E5%87%BA.txt`
and `https://xxxx/files/files/%E5%89%AA%E8%B4%B4%E6%9D%BF%E5%AF%BC%E5%85%A5/%E7%94%B1PC_V2RayN%E5%AF%BC%E5%87%BA.txt`

The file can not be edit and preview, size is 1.08KB. No matter in what location, It just can not be edit and preview.
Located in `./files/客户端手动设置/USA_Oregon.txt`.
URL is `https://xxxx/files/files/%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%89%8B%E5%8A%A8%E8%AE%BE%E7%BD%AE/USA_Oregon.txt`

And I am using the standalone version with nginx proxy_pass:
```
server {

  listen 443 http2 ssl;
  listen [::]:443 http2 ssl;

  ssl on;

  ssl_certificate fullchain.pem;
  ssl_certificate_key privkey.pem;

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  ssl_ecdh_curve X25519:P-256:P-384:P-224:P-521;
  ssl_ciphers 'EECDH+AESGCM:balabala';
  ssl_prefer_server_ciphers on;

  # filebrowser location
  location / {
    proxy_redirect off;
    proxy_pass http://127.0.0.1:8080;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
  }
}
```

**Comment by eine** [comment]
Is any error shown in either the log of the backend or the console of the browser (frontend)?

**Comment by chinanoahli** [comment]
> Is any error shown in either the log of the backend or the console of the browser (frontend)?

Both not.

**Comment by ttys3** [comment]
maybe your txt file is not UTF-8 encoded.
I've found this issue too.
But I do not think it is a Filebrowser problem.

**Comment by chinanoahli** [comment]
> maybe your txt file is not UTF-8 encoded.
> I've found this issue too.
> But I do not think it is a Filebrowser problem.

It is an UTF-8 file.

**Comment by ttys3** [comment]
> > maybe your txt file is not UTF-8 encoded.
> > I've found this issue too.
> > But I do not think it is a Filebrowser problem.
> 
> It is an UTF-8 file.

UTF-8 with BOM or not ?

**Comment by chinanoahli** [comment]
> > > maybe your txt file is not UTF-8 encoded.
> > > I've found this issue too.
> > > But I do not think it is a Filebrowser problem.
> > 
> > 
> > It is an UTF-8 file.
> 
> UTF-8 with BOM or not ?

I runed hexdump and file for those file that has problem:
```
$ hexdump -n 3 -C file.txt
hexdump -n 3 -C file.txt
00000000  e7 a6 81                                          |...|
00000003
$ file file.txt
file.txt: UTF-8 Unicode text
```

It seems they are not a UTF-8 file with BOM.

I even tried to using Filebrowser create the file and copy the content in to the file and save it. After that reopen it in Filebrowser. It just not working.

The content contain sensitive data, I can not post it here.

**Comment by ttys3** [comment]
maybe there is bug in func `isBinary()`
https://github.com/filebrowser/filebrowser/blob/master/files/utils.go#L3
if a txt file detected by this func and it return true, the txt file will not be editable.

**Comment by chinanoahli** [comment]
> maybe there is bug in func `isBinary()`
> https://github.com/filebrowser/filebrowser/blob/master/files/utils.go#L3
> if a txt file detected by this func and it return true, the txt file will not be editable.

Emmm, I see, Is there something I can do to avoid this issue. Like add some character before the file?

**Comment by eine** [comment]
@442hz thanks a lot for the finding. That's a very good hint, indeed. It seems a naive implementation that we can probably improve.

---

@chinanoahli have you ever tried building filebrowser yourself instead of using the released bineries? If so, you can just replace [`utils.go#L4-L11`](https://github.com/filebrowser/filebrowser/blob/master/files/utils.go#L4-L11) with `return false`. That would let us confirm that issue is with that function.

Alternatively, you can scan the offending file and check if any of the char has a decimal value of `65533` or `<= 8`. If found, try removing just those chars from the file and opening it with filebrowser.

**Comment by chinanoahli** [comment]
> @442hz thanks a lot for the finding. That's a very good hint, indeed. It seems a naive implementation that we can probably improve.
> 
> @chinanoahli have you ever tried building filebrowser yourself instead of using the released bineries? If so, you can just replace [`utils.go#L4-L11`](https://github.com/filebrowser/filebrowser/blob/master/files/utils.go#L4-L11) with `return false`. That would let us confirm that issue is with that function.
> 
> Alternatively, you can scan the offending file and check if any of the char has a decimal value of `65533` or `<= 8`. If found, try removing just those chars from the file and opening it with filebrowser.

I will try this this later. I have to having a long trip tomorrow. I will report the result ASAP.

**Comment by eine** [comment]
According to https://groups.google.com/forum/#!topic/golang-nuts/YeLL7L7SwWs, I wrote a fix that uses [net/http.DetectContentType](https://golang.org/pkg/net/http/#DetectContentType) to detect the type. See [this commit](https://github.com/filebrowser/filebrowser/commit/68943d33b5d2a279523d91c3fb5dde5e3a17c6e1). This is available in branch [fix-isbinary](https://github.com/filebrowser/filebrowser/tree/fix-isbinary). Also, a docker image with this fix is available: [filebrowser/filebrowser:issue-681](https://hub.docker.com/r/filebrowser/filebrowser/tags).

@442hz, @chinanoahli, please let us know it works for you, whenever you have time to test it.

**Comment by ttys3** [comment]
@1138-4EB this fix (branch [fix-isbinary](https://github.com/filebrowser/filebrowser/tree/fix-isbinary)) will not work as expected.
becuase text files which non-UTF-8 encoded, will also result in "text" format,  which makes filebrowser 
thinks this text file is editable. 

for example.  a GBK encoded srt file:
![image](https://user-images.githubusercontent.com/41882455/53479017-1d801100-3ab3-11e9-9908-82d9737655b1.png)

this iconv comand can show it it a GBK file:
![image](https://user-images.githubusercontent.com/41882455/53479050-2ffa4a80-3ab3-11e9-8534-8874c063f16b.png)

and  `http.DetectContentType()` will result in a wrong  mime:
```
"text/plain; charset=utf-8"
```

Linux `file` command also returned a wrong type: `Non-ISO extended-ASCII text`
![image](https://user-images.githubusercontent.com/41882455/53479405-f8d86900-3ab3-11e9-8365-dd5c159c2cbb.png)


[The.Secret.in.Their.Eyes.2009.BluRay.1080p.x265.10bit.MNHD-FRDS.chs.zip](https://github.com/filebrowser/filebrowser/files/2909408/The.Secret.in.Their.Eyes.2009.BluRay.1080p.x265.10bit.MNHD-FRDS.chs.zip)

@chinanoahli you'd better attach your sample txt file to this issue, so that we can test it.

**Comment by eine** [comment]
@442hz, I think it is better in this use case to have false positives, rather than having false negatives, as we have now.

The GBK encoded SRT file seems to be a very specific example, as neither MIME nor file return the value you expect. Certainly, it seems to be a valid text, indeed, since the first three lines are shown equally with or without `iconv`. That means that it is not a non-text file, but a text file with some encoded content inside.

Which do you think that should be the correct MIME type? https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by hacdias** [comment]
@1138-4EB I think we shouldn't rely on mimetypes since they might not be available on all devices and might not consistent across devices. That's what we did before and we also had a lot of issues and even an array with allowed file names or extensions because a lot didn't work

**Comment by eine** [comment]
I don't really know which are the requirements for mimetypes to be available in a device. Isn't it possible that the golang implementation does it on it's own and does not rely on any resource on the host? I say it because the function does not return any error. Otherwise, we can just check if it is available and fall back to another method.

Do you have any further reference about this?

**Comment by hacdias** [comment]
`DetectContentType` always returns a value and it returns `application/octet-stream` if it couldn't detect any file type (https://golang.org/src/net/http/sniff.go?s=646:688#L11). Looking at the algorithm it doesn't seem to rely on any external mime types but its own. Perhaps it was MimeFromExtension which needed a 3rd party value.

Although, the current function for testing if a file contains text doesn't seem wrong and I'd really like to know the contents of the file that are causing this troubles.

**Comment by chinanoahli** [comment]
Sorry for disappear such a long time, so what should I test?
[USA_Oregon_1.txt](https://github.com/filebrowser/filebrowser/files/2991928/USA_Oregon_1.txt)
This is the file, that can be download but not edit in utf-8 coding.

**Comment by ttys3** [comment]
@chinanoahli  thanks for the sample txt file. that's very helpful.

```
 ll USA_Oregon_1.txt
-rw-r--r-- 1 hacklog hacklog 1052 Mar 23 13:46 USA_Oregon_1.txt
```
this file is UTF-8 nobomb and valid. nothing wrong.

finally , I've found the bug code on line 167 in files/file.go :
https://github.com/filebrowser/filebrowser/blob/master/files/file.go#L167

func `isBinary()` is OK, but the call to it is wrong.
```
        buffer := make([]byte, 512)
	n, err := reader.Read(buffer)
//since our file size is 1052, so in this case, n = 512

//here is the problem: string(buffer[:n])
	case isBinary(string(buffer[:n])) || i.Size > 10*1024*1024: // 10 MB
		i.Type = "blob"
		return nil
```
we can simplify the code to `string(buffer[:512])``

I've wrote some test code to determine the problem:
```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"
)

func isBinary(content string) bool {
	for index, b := range content {
		log.Printf("start check index:%x, b: %x , %#U", index, b, b)
		// 65533 is the unknown char
		// 8 and below are control chars (e.g. backspace, null, eof, etc)
		if b <= 8 {
			log.Printf("b <= 8, index:%x, b: %x , %#U", index, b, b)
			return true
		}

		if b == 65533 {
			log.Printf("b == 65533, index:%x, %x , %#U", index, b, b)
			return true
		}

	}
	return false
}

func main() {
	filename := "./USA_Oregon_1.txt"
	c, _ := ioutil.ReadFile(filename)
//result: false
	fmt.Printf("isBinary(string(c)): %#v \n", isBinary(string(c)))

//result: true
	fmt.Printf("isBinary(string(c[:512])): %#v \n", isBinary(string(c[:512])))
}
```

![image](https://user-images.githubusercontent.com/41882455/54868973-5d45ca00-4dcd-11e9-8d13-f319f841e770.png)

index 1fe (decimal is 510, and 510%3 == 0), so, the last Chinese word should be `U+95F4 '间'`,
95F4 is Hex code point
the correct Hex UTF-8 bytes is `E9 97 B4`
(you can use this tool to convert http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=95F4&mode=hex )

since the code only take 512 bytes, so it just took  E9 97 and golang thinks this is not a valid Unicode code point, so it convert it to  `U+FFFD` ( see golang doc: https://godoc.org/golang.org/x/text/encoding#Encoding) 
and FFFD actually is 65533 in `func isBinary` (in here, I suggest to use FFFD in `func isBinary` not 65533, because 65533 is hard to understand.)

according to golang doc:

> Replacement is the replacement encoding. Decoding from the replacement encoding yields a single '\uFFFD' replacement rune. Encoding from UTF-8 to the replacement encoding yields the same as the source bytes except that invalid UTF-8 is converted to '\uFFFD'.
> 
> It is defined at http://encoding.spec.whatwg.org/#replacement

**Comment by hacdias** [comment]
@ttys3 thanks a lot for the research. If you have time, a PR would be really helpful 😃

**Comment by ttys3** [comment]
```go
package main

import (
	"fmt"
	"io/ioutil"
	"unicode/utf8"
	"log"
)

func isBinary(content []byte, n int) bool {
	maybeStr := string(content)
	runeCnt := utf8.RuneCount(content)
	runeIndex := 0
	var gotRuneErrCnt = 0
	var firstRuneErrIndex = -1
	for index, b := range maybeStr {
		log.Printf("start check index:%d, b: %x , %#U", index, b, b)
		// 65533 is the unknown char
		// 8 and below are control chars (e.g. backspace, null, eof, etc)
		if b <= 8 {
			log.Printf("b <= 8, index:%d, b: %x , %#U", index, b, b)
			return true
		}

		if b == 0xFFFD {
			//if it is not the last utf8.UTFMax (4) rune
			if runeCnt > utf8.UTFMax && runeIndex < runeCnt - utf8.UTFMax {
				log.Printf("got b == 0xFFFD, index:%d, %x , %#U, runeIndex: %d, runeCnt: %d", index, b, b, runeIndex, runeCnt)
				return true
			} else {
				//else it is the last utf8.UTFMax (4) rune
				//there maybe Vxxx, VVxx, VVVx, thus, we may got max 3 0xFFFD rune (asume V is the byte we got)
				//for Chinese, it can only be Vxx, VVx, we may got max 2 0xFFFD rune
				gotRuneErrCnt++
				log.Printf("byte content index %d: %x , %#U\n", 
				index, content[index:index+1],content[index:index+1])

				//mark the first time
				if firstRuneErrIndex == -1 {
					firstRuneErrIndex = runeIndex
				}
			}
		}
		runeIndex++
	}

	if firstRuneErrIndex != -1 && gotRuneErrCnt != runeCnt - firstRuneErrIndex {
		return true
	}
	return false
}

func main() {
	filename := "./USA_Oregon_1.txt"
	n := 512
	c, _ := ioutil.ReadFile(filename)
//result: false
	// fmt.Printf("isBinary(c): %#v \n\n", isBinary(c, n))

//result: false
	fmt.Printf("isBinary(c[:%d])): %#v \n", n, isBinary(c[:n], n))
}
```

**Comment by ttys3** [comment]
![image](https://user-images.githubusercontent.com/41882455/57321317-a6f73380-7133-11e9-9d67-096137662b4c.png)

![image](https://user-images.githubusercontent.com/41882455/57321340-b1193200-7133-11e9-9304-a47a14adb9e4.png)

![image](https://user-images.githubusercontent.com/41882455/57321349-b8404000-7133-11e9-93d7-18c55314f302.png)


![image](https://user-images.githubusercontent.com/41882455/57321367-c2623e80-7133-11e9-8eab-3c923322e810.png)

![image](https://user-images.githubusercontent.com/41882455/57321388-cbeba680-7133-11e9-92ec-174849297ace.png)

**Comment by ttys3** [comment]
test ELF file:
![image](https://user-images.githubusercontent.com/41882455/57321474-fdfd0880-7133-11e9-8624-dc9bb9d22839.png)
