### ISSUE TITLE
How to close localhost port as webpage is still open.

### ISSUE THREAD

**Issue by dylanlogann** [filebrowser/filebrowser#684]
I ran the .exe a while ago, and I since want to stop it from being displayed on one of my ports. 

Can anyone supply some help to how I would stop this so its no longer on my network?

**Comment by eine** [comment]
There are multiple options:

- The service did stop at some point but the cache in your browser is showing the frontend. If you try to login, it should fail. If so, just clear the cache or use private mode.
- If the computer where filebrowser was executed has not been restarted since then, just do it.
- If the service is running and you don't want to restart the computer, find it in the list of active processes and kill it.

**Comment by hacdias** [comment]
Yes, @1138-4EB is right. As soon as you stop the `.exe`, File Browser stops running.

**Comment by dylanlogann** [comment]
@1138-4EB @hacdias 

Yeah I have just tested this and a quick CTRL+F5 done the job.

Sorry for any inconveniences.

Thanks.
