### ISSUE TITLE
When will armv9 be supported? Other arm versions are too old

### ISSUE THREAD

**Issue by niceran** [filebrowser/filebrowser#688]
When will armv9 be supported? Other arm versions are too old

**Comment by eine** [comment]
Up to my knowledge `armv9` does not exists. The latest architecture is `armv8`, which includes `AArch64`, `AArch32` (similar but not equal to `armv7` and `armhf`) and `Thumb`. Please, see https://en.wikipedia.org/wiki/ARM_architecture#64/32-bit_architecture.

What do you mean with *Other arm versions are too old*? RPi3B, for example, is 2-3 years old and it is armv8.

**Comment by eine** [comment]
You might mean `ARM9`, instead of `armv9`. If so, the device is probably old (before 2006), but it might still be supported. According to https://en.wikipedia.org/wiki/ARM9, the armv5 version ([linux-armv5-filebrowser.tar.gz](https://github.com/filebrowser/filebrowser/releases/download/v2.0.3/linux-armv5-filebrowser.tar.gz)) might work. Otherwise, I don't think we can do anything, because earlier versions are not supported by golang: https://github.com/golang/go/wiki/GoArm#supported-architectures.
