### ISSUE TITLE
Enhancements for media preview

### ISSUE THREAD

**Issue by ww7** [filebrowser/filebrowser#755]
- exit from preview with ESC key and after click outside media zone
- option for Play next automatically
- option for play "Repeat one" mode
- slideshow 
- zooming images
- 360 video support bu inject videojs-vr

**Comment by vitaliy-kuzmich** [comment]
@ww7 hey, I've done some part of this ticket,  just need to gen docker with dependencies. https://github.com/vitaliy-kuzmich/filebrowser. Also add windows support.

upd:
https://github.com/browsefile/backend just better for media, you can download media files as m3u, and run it on local player, just to note, after some time, you would have to download it again, because of auth timeout.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
