### ISSUE TITLE
What's the database format of filemanager.db?

### ISSUE THREAD

**Issue by rigious** [filebrowser/filebrowser#779]
I want to modify the share URL in the database , but I didn't know the format of the database. How could I open that?

**Comment by nambrosch** [comment]
I believe it's bolt.  Let me know if you figure this out, I'd be interested in doing something similar.

**Comment by RMuskovets** [comment]
Maybe it's SQLite?

**Comment by hacdias** [comment]
As @nambrosch said, it is BoltDB. We use [`bbolt` fork](https://github.com/etcd-io/bbolt) since the original was archived. It has the same API and some improvements.

Some interesting tools:

- [BoltGUI](https://github.com/nisboo/BoltGUI)
- [boltdweb](https://github.com/evnix/boltdbweb)
- [boltbrowser](https://github.com/br0xen/boltbrowser)
