### ISSUE TITLE
希望能统一管理分享链接

### ISSUE THREAD

**Issue by ying001ch** [filebrowser/filebrowser#819]
**Is your feature request related to a problem? Please describe.**
如果我分享出去很多文件，当我想取消一批文件的分享时，我很难记住所有自己已经分享的文件。

**Describe the solution you'd like**
希望能有一个入口来同一管理分享链接，比如取消分享、改变分享时间等等。

**Describe alternatives you've considered**
或者在已经分享过的文件上做明显的标记

**Additional context**

**Comment by ttys3** [comment]
maybe this can help you: https://github.com/ttys3/filebrowser-enhanced/releases/tag/v2.2.8

**Comment by hacdias** [comment]
@ttys3 thanks for linking that. Could you give me some hint about what's this issue about? :)

**Comment by Yuanuo** [comment]
What he wants is that there is a dedicated page to display/manage all sharing links. Because if you share too many documents, after a long time, they can not remember which documents have been shared, want to cancel sharing there is no way.

Or, if there is no such page, he wants a special flag to appear on the file icon for files that have already been shared.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
