### ISSUE TITLE
Moving Hugo executable... open : no such file or directory

### ISSUE THREAD

**Issue by icyleaf** [filebrowser/filebrowser#85]
i used a hugo [docker image](https://github.com/icyleaf/docker-images/tree/master/caddy) include hugo feature by default, but it does not running in normal:

``` bash
$ docker run -d -P 2015:2015 -v /path/to/hugo:/site -v /path/to/Caddyfile:/etc/Caddyfile icyleafcn/caddy

Activating privacy features... done.
Unable to find Hugo on your computer.
Downloading Hugo from GitHub releases... downloaded.
Checking SHA256...checked!
Unzipping... done.
Moving Hugo executable... open : no such file or directory
```

Caddyfile:

```
0.0.0.0
root /site/public
basicauth /admin user pass
hugo
```

**Comment by hacdias** [comment]
Hello @icyleaf!

That was already fixed and in the meanwhile I've also changed how caddy-hugo installs hugo. The problem is that the version on caddyserver.com is not up to date with this repository yet.

What you can do right now is build it from source OR download the hugo binary to $HOME/.caddy/bin/hugo. 

Thanks :)

**Comment by icyleaf** [comment]
That's great, thanks :)
