### ISSUE TITLE
About preview MS Office document

### ISSUE THREAD

**Issue by Nicked639** [filebrowser/filebrowser#880]
I am using Chrome to manage Filebrowser. When it comes to MS Office documents, Filebrowser can only show up a download GUI but cannot preview the content. 

So I googled for solutions. Finally I found a  [chrome extension](https://chrome.google.com/webstore/detail/office-editing-for-docs-s/gbkeegbaiigmenfmjfclcdgdpimamgkj) which is published by google that can preview MS Office documents online. It works perfect in google.com when searching with something like  "filetype: doc test", with one click you can preview the document rather than download it. 

But when I turn to Filebrowser it fails, and the download GUI pops up again.
Could you please have a check?

**Comment by sabatale** [comment]
Hello,

I haven't tried to fix your issue but from what I see in the code, only the .pdf extension can be previewed as a document. All other formats (= "blob") are only available for download, which is why your plugin is ineffective.

At the minimum you would need to modify **/frontend/src/components/Preview.vue** and try adding a new **v-else-if** for .doc*:

```
      <object v-else-if="req.extension == '.pdf'" class="pdf" :data="raw"></object>
      <object v-else-if="req.extension == '.docx' || '.doc'" class="pdf" :data="raw"></object>
      <a v-else-if="req.type == 'blob'" :href="download">
        <h2 class="message">{{ $t('buttons.download') }} <i class="material-icons">file_download</i></h2>
      </a>
    </div>
```

This should allow your extension to kick in. If so, then you can start from there and fix potential bugs.
Again, I haven't tried it myself. Also, from a development perspective, a possible solution for implementation would be [Gotenberg](https://github.com/thecodingmachine/gotenberg).

'luck!

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
