### ISSUE TITLE
Filebrowser is not loading after a refresh

### ISSUE THREAD

**Issue by dalazx** [filebrowser/filebrowser#965]
**Description**
Filebrowser stops loading after refreshing its tab.

**Expected behaviour**
The file browser is loaded properly.

**What is happening instead?**
The loading icon on the blank page is stuck there forever.

**How to reproduce?**
Run a new instance of the file browser in a docker container:
```shell
docker run --rm -it -p 8989:80 filebrowser/filebrowser --noauth -r / 
```

Open the file browser in a new tab.
```shell
open http://localhost:8989
```

The web browser tab gets redirected to `http://localhost:8989/files/`

Then just hit `Cmd-R` to refresh the tab.

**Comment by peterbuga** [comment]
@dalazx I experience the same problem :(

something broke before last & before-last version because v2.0.16 seems to be working as expected. the reason is that html code is dumped into .css/.js resources (at least on my side) rendering the files useless.

unfortunately i'm not familiar with go and i don't even know where to start :/

**Comment by nambrosch** [comment]
@peterbuga I think 2.1.0 was a hasty build that merged in all of the open PRs before the project was frozen.  2.0.16 is the last stable build which is what I've been using since November 2019.

**Comment by peterbuga** [comment]
@nambrosch thanks for the clearing thinks up! 
i've read various posts about archiving the project and then picking it up again and to be honest i'm a bit confused of its state right now 😅 great work nonetheless, i'd be cool for the project to stay alive!
