### ISSUE TITLE
request origin not allowed by Upgrader.CheckOrigin

### ISSUE THREAD

**Issue by oakboat** [filebrowser/filebrowser#967]
500 127.0.0.1 websocket: request origin not allowed by Upgrader.CheckOrigin
hope you can solve this
you can add this:
var upgrader = websocket.Upgrader{
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}

**Comment by o1egl** [comment]
@mrwoowoo Can you please add information on how to reproduce this error?

**Comment by lifegpc** [comment]
> @mrwoowoo Can you please add information on how to reproduce this error?

1. Use nginx or apache2 to reverse proxy.
Nginx's configure file:
```nginx
server {
    listen       80;
    server_name localhost;
    location / {
        proxy_pass   http://127.0.0.1:8080;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
    }
}
```
2. Open `localhost:80` in browser and try using shell. 
You will get that error.

**Comment by leafee98** [comment]
## If we fix this by code

I think I found the reason, the error message is shown by a third party dependency `websocket`, and the code printing message is bellow:

https://github.com/gorilla/websocket/blob/69d0eb9187b6dead8fe84b2423518475e5cc535c/server.go#L148-L154

```
	checkOrigin := u.CheckOrigin
	if checkOrigin == nil {
		checkOrigin = checkSameOrigin
	}
	if !checkOrigin(r) {
		return u.returnError(w, r, http.StatusForbidden, "websocket: request origin not allowed by Upgrader.CheckOrigin")
	}
```

Since the `CheckOrigin` isn't setup in filebrowser's code:

https://github.com/filebrowser/filebrowser/blob/2b2c1085fb50ad68612ad438e527fd316d8aafee/http/commands.go#L21-L24

The websocket module will use `checkSameOrigin`, which check the equalization of `Origin` and `Host` in a HTTP request

https://github.com/gorilla/websocket/blob/69d0eb9187b6dead8fe84b2423518475e5cc535c/server.go#L89-L99

```
func checkSameOrigin(r *http.Request) bool {
	origin := r.Header["Origin"]
	if len(origin) == 0 {
		return true
	}
	u, err := url.Parse(origin[0])
	if err != nil {
		return false
	}
	return equalASCIIFold(u.Host, r.Host)
}
```

There's an issue https://github.com/gorilla/websocket/issues/367#issuecomment-402479632 talking about this, it can be fixed by giving an "always returning true function" but I don't know if this way is appropriate enough.

## if we fix this by config reverse proxy

In practice, add `ProxyPreserveHost on` just around the `ProxyPass` directive, in my case, it work when setup as follow (note that my instance listen on 8009)

```
        ProxyPass               / http://[::1]:8009/ nocanon upgrade=WebSocket
        ProxyPassReverse        / http://[::1]:8009/
        ProxyPreserveHost on
```

By the way, I'm suffering from `Command not Allowed` now.

**Comment by leafee98** [comment]
Figured out, but it may be related with security and I reported a security vulnerability, so I won't public it, sorry for this.

**Comment by oakboat** [comment]
@leafee98 @o1egl 
This can be sloved by editing nginx's configure file.
```
    server {
        listen       80;
        server_name  localhost;

        location / {
            proxy_pass   http://127.0.0.1:8080;
            proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header Connection Upgrade;
        }
    }
```
Cause error:
2022/11/26 13:28:18 /: 500 127.0.0.1 websocket: request origin not allowed by Upgrader.CheckOrigin
2022/11/26 13:28:18 http: superfluous response.WriteHeader call from github.com/filebrowser/filebrowser/v2/http.handle.func1 (data.go:74)

But:
```
    server {
        listen       80;
        server_name  localhost;

        location / {
            proxy_pass   http://127.0.0.1:8080;
            proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header Connection Upgrade;
	    proxy_set_header Host $host;
        }
    }
```
Work well:
![0d938be6b5af872a3735f215657b1b3f](https://user-images.githubusercontent.com/27909321/204073926-96831f6e-ed8f-40f4-84e2-3c0047906f11.png)

Therefore, add "proxy_set_header Host $host;" to nginx's confiregure to slove this problem.
