### ISSUE TITLE
Show available directories

### ISSUE THREAD

**Issue by tionis** [filebrowser/filebrowser#998]
Example:
When no user is allowed to access '/' and I allow a User to access '/books' and '/movies', then the user should when he navigates to '/' see both '/books',  '/movies' but nothing else. At the moment he would see nothing.

**Comment by o1egl** [comment]
@tionis the bug is fixed in [v2.2.0](https://github.com/filebrowser/filebrowser/tree/v2.2.0) 
To achieve the result you want, you can apply the following settings:

<img width="602" alt="Screenshot 2020-06-22 at 18 50 03" src="https://user-images.githubusercontent.com/966539/85316360-ec53fd00-b4bc-11ea-98c6-5f2dfaf0d1b4.png">

**Comment by tionis** [comment]
I experimented with the options in the picture and can report, that it only works if I specify the regex disallow rule as last one.

**Comment by o1egl** [comment]
That was fixed in the new version. Please upgrade your app

**Comment by tionis** [comment]
Weird, I installed by piping to bash as stated in the website. I will try it out with a release binary from github

**Comment by o1egl** [comment]
I guess you did it before the new release was published

**Comment by tionis** [comment]
I installed it again (v2.2.0/4c20772) and now it works as intended, thanks!
